### ISSUE TITLE
Proposal: de-namespace vcard ontology properties in the normative json-ld context

### ISSUE THREAD

**Issue by jasnell** [jasnell/w3c-socialwg-activitystreams#102]
Currently, the normative JSON-LD context for Activity Streams 2.0 includes a namespaced reference to vcard, allowing things like:

```json
{
  "@context": "http://www.w3.org/ns/activitystreams#",
  "@type":  ["Person", "vcard:Individual"],
  "vcard:fn": "Jane Jones"
}
```

While this is helpful, the use of the namespace prefix is irritating. Given that there are currently no naming conflicts between AS2 and VCard terms, I would like to propose that we de-namespace the VCard terms within the AS2 normative context. That would mean allowing and implementer to do:

```json
{
  "@context": "http://www.w3.org/ns/activitystreams#",
  "@type":  ["Person", "Individual"],
  "fn": "Jane Jones"
}
```

**Comment by jasnell** [comment]
Actually.. there is one overlapping vcard term... `Video`... which would conflict with `as:Video`... that seems minor

**Comment by bcomnes** [comment]
:+1:
