### ISSUE TITLE
"Organization": "vcard:Organization" or "org:Organization"?

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#106]
Why do we put preference on "vcard:Organization" over "org:Organization"?

```ttl
org:Organization a owl:Class, rdfs:Class;
    rdfs:subClassOf  foaf:Agent;
    owl:equivalentClass foaf:Organization;
    rdfs:label "Organization"@en;
```
http://www.w3.org/ns/org#

**Comment by jasnell** [comment]
VCard is currently being used by existing Social platform providers. I'm not aware of a single existing Social platform provider currently using the org ontology.

**Comment by elf-pavlik** [comment]
@der could you please offer us some feedback on how you see alignment between org:Organization and vcard:Organization? Thanks you!

**Comment by der** [comment]
In the new vcard then vcard:Organization and org:Organization are probably equivalent classes.

In earlier versions of vcard in RDF it appeared that vcard:Organization didn't represent the organization itself but represented a record about the organization. I believe that the updated modelling done last year changed/clarified that though haven't followed the details.

**Comment by elf-pavlik** [comment]
Thanks @der! After verifying it we can close that issue :smile: 
Where should I propose adding another equivalence triple to org:Organization?

```ttl
org:Organization a owl:Class, rdfs:Class;
    rdfs:subClassOf  foaf:Agent;
    owl:equivalentClass foaf:Organization, vcard:Organization;
    rdfs:label "Organization"@en;
```

**Comment by der** [comment]
Send to public-gld-comments@w3.org

There is currently no working group to review and discuss so will get added to the errata page for future consideration.

Though I don't think that would be the right place, I think it would be up to vcard to be clear what vcard:Organization means now, especially since org was published before the vcard update.

**Comment by akuckartz** [comment]
I know the W3C Organization ontology since a rather long time but was not even aware of `vcard:Organisation`. Where is it used in the Web of Data?

**Comment by jasnell** [comment]
Given the WG decision to remove all non AS2 terms from the context, this no longer appears to be relevant. Closing
