### ISSUE TITLE
 Syntax error in turtle definition of the Activity Streams 2.0 vocabulary.

### ISSUE THREAD

**Issue by muratseyhan** [jasnell/w3c-socialwg-activitystreams#109]
[The provided turtle serialization](http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams2.owl) seems to have a syntax error.

Line 368 reads:

    rdfs:range rdf:Property ;

where it should be:

    rdfs:range rdf:Property .

**Comment by jasnell** [comment]
@muratseyhan thank you for spotting that. would you mind submitting a quick PR to correct?

**Comment by elf-pavlik** [comment]
I need to add automated validation of vocab to #65
