### ISSUE TITLE
use as:Profile as secondary type, similar to mf2:h-cite

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#112]
We could use [as:Profile](http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams2-vocabulary.html#dfn-profile) in a similar way as I proposed to use [mf2:h-cite](http://microformats.org/wiki/h-cite) - https://github.com/converspace/webmention/issues/40

For example, I use https://wwelves.org/perpetual-tripper as my identity

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@id": "https://wwelves.org/perpetual-tripper",
  "@type": "Person",
  "displayName": "elf Pavlik"
}
```

I could than create a profile/account in other systems using something like 

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@id": "http://indiewebcamp.com/elf-pavlik",
  "@type": ["Profile", "Person"],
  "describes": {
    "@id": "https://wwelves.org/perpetual-tripper",
    "@type": "Person",
    "displayName": "elf Pavlik"
  }
}
```
or in a way *override* default properties from described object

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@id": "http://indiewebcamp.com/elf-pavlik",
  "@type": ["Profile", "Person"],
  "displayName": "el Elfo",
  "describes": {
    "@id": "https://wwelves.org/perpetual-tripper",
    "@type": "Person",
    "displayName": "elf Pavlik"
  }
}
```

@tantek do people combine rel="me" into rel="me canonical" ? how can I mark in http://indiewebcamp.com/elf-pavlik that it just serves as local profile of my actual identity https://wwelves.org/perpetual-tripper
In simlar way one could mark https://aaronparecki.com/events/2015/03/17/1/socialwg-2015 & https://www.facebook.com/events/444025702419735/ as profiles of canonical event https://www.w3.org/wiki/Socialwg/2015-03-17

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@id": "https://aaronparecki.com/events/2015/03/17/1/socialwg-2015",
  "@type": ["Profile", "Event"],
  "describes": {
    "@id": "https://www.w3.org/wiki/Socialwg/2015-03-17",
    "@type": "Event",
    "displayName": "W3C Social: F2F2"
  }
}
```

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@id": "https://www.facebook.com/events/444025702419735/",
  "@type": ["Profile", "Event"],
  "describes": {
    "@id": "https://www.w3.org/wiki/Socialwg/2015-03-17",
    "@type": "Event",
    "displayName": "W3C Social: F2F2"
  }
}
```

**Comment by jasnell** [comment]
Having a `http://www.w3.org/ns/activitystreams#describes` property on `as:Profile` works for me. Should it be a functional property or not? That is, does a profile only describe a singular object?

**Comment by elf-pavlik** [comment]
+1 *owl:FunctionalProperty*, thinking of a single ```as:Profile``` describing many different ```as:Object``` makes it look pretty confusing.

What do you think about recommending to give profile also a type of object it describes? e.g. `"@type": ["Profile", "Event"]`, especially if one uses only URI as value of describes and dosn't embed the with information about described object type.
