### ISSUE TITLE
Suggest dropping "Watch" from vocabulary

### ISSUE THREAD

**Issue by cwebber** [jasnell/w3c-socialwg-activitystreams#113]
Watch is a subclass of view, but there's no clear reason to me what kind of things you can watch where "view" isn't a subclass enough... it's already more than granular enough that view subclasses experience, IMO.

**Comment by jasnell** [comment]
+1 ... simplification is good

**Comment by elf-pavlik** [comment]
I plan to use distinct *View* and *Watch/Listen/Read*. While I can just *View* video/audio/book first, I may create future Activity to actually Watch/Liste/Read it #93 

Anyhow :+1: moving all the non core grammar terms somewhere else...
