### ISSUE TITLE
Confirm vs Accept

### ISSUE THREAD

**Issue by cwebber** [jasnell/w3c-socialwg-activitystreams#115]
Both the Confirm and Accept vocab seem pretty similar, as you might use them to accept an invitation... the only difference I can think of is "confirmed that your statement is correct" (which is a very different thing from "accepting" an invitation), but the example given is "confirming a reservation", which is very similar to "accept".  There might be differences between them but I can't really tell.  Thoughts @jasnell?

**Comment by jasnell** [comment]
The difference is subtle but important, I think. The real question, however, is whether we need both in the core vocabulary. `Confirm` can likely be dropped.

**Comment by cwebber** [comment]
@jasnell How about adding a "confirm" property to the accept verb?  That may have its own issues.

I agree that there is a subtle difference.  I'm hold no strong opinion on this one.

**Comment by jasnell** [comment]
I'd be happy just to drop `Confirm` entirely unless our agreed upon user stories depend on it.
