### ISSUE TITLE
Iconsistency wrt indirect object (target) and multiple actors

### ISSUE THREAD

**Issue by alexanderkjeldaas** [jasnell/w3c-socialwg-activitystreams#131]
The "target" attribute of an Activity is documented as an "indirect object".

For "actor", I think something similar is needed.  I want to express "John put the movie X on a shelf, using an iPad".  The shelf is the "indirect object"/target, and iPad is the "indirect actor" in this case.

Using two actors is not a good way to represent what is going on, since the iPad did not do this by itself.  Similarly, I don't see any "via", or "using" attribute on Person, or the reverse on Device.

**Comment by jasnell** [comment]
For a while we had an experimental notion of an "instrument" property (similar to http://schema.org/instrument) for exactly this purpose but removed it due to lack of clear, coherent use cases. We could potentially add it back in or it can be implemented via an extension.

**Comment by jasnell** [comment]
@alexanderkjeldaas ... did my response address your concern? Do you believe we need to add the `instrument` property back in?

**Comment by alexanderkjeldaas** [comment]
Yes this addresses my concern perfectly.  The specific relation that is pretty central to me is the Device, which in AS is an Actor, but it is, in my use-case commonly used together with a Person.  So the range of instrument would, in my case, include Device at least.  A Device is potentially a pretty passive object, a kind of instrument.

**Comment by jasnell** [comment]
Ok, I've added "instrument" back. However, be advised that the "Device" object has been removed from the extended vocabulary. If you need "Device" as an object, you'll want to define your own ID for it. e.g. `"@type": "http://example.org/Device"`
