### ISSUE TITLE
Create Examples With input and output of Common Posts to various platforms

### ISSUE THREAD

**Issue by abigdreamer** [jasnell/w3c-socialwg-activitystreams#133]
1. Facebook image post with picture description
2. Tweet with GPS location and picture
3. Foursquare Checkin
4. Facebook Like
5. Youtube Video Post of Popular Song done as a Cover by another Musician
6. Linkedin Post Coming from a Known Person 
7. Ted Talk with Video
8. LLOT (internet of things) Thermostat pulling in motion, door sensor, temperature, lat long

**Comment by elf-pavlik** [comment]
:+1: @abigdreamer maybe you would like to start a [gist](http://gist.github.com) for each of those examples, update your list above with links to them?

**Comment by jasnell** [comment]
Given that none of these services currently support AS2, I'm not sure what this achieves other than theoretical comparison. I agree that examples like this would be useful, just not in the core documents. Perhaps a separate Note that takes a kind of "Cookbook" approach would be more useful?

**Comment by abigdreamer** [comment]
It just seems like a Gazillion Amount of Tweets, Facebook posts, Instagram Pics -- bla bla bla -- Should someday contain Linked Data and be searchable and all this knowledge should end up in Some sort of Jason-Ld - Ontology -- ETC format. And by not Going Here Sooner rather than later with expert help from those that know how this would work ... we are not including a HUGE portion of all web content.

**Comment by abigdreamer** [comment]
If you took Common Social Media Posts and categorized them into a rating system of some sort and focused on the TOP 10 and made sure technology like jason-ld was headed in the direction to include this kind of data, we would all get somewhere faster. Of course -- my opinion. If Jason-ld is not the Correct format -- and this Streams project is not the correct project -- then point me somewhere please.

**Comment by rhiaro** [comment]
Hi Mike, if you haven't already seen it you might want to look at
<https://github.com/snarfed/activitystreams-unofficial>https
<https://github.com/snarfed/activitystreams-unofficial>://
<https://github.com/snarfed/activitystreams-unofficial>github.com
<https://github.com/snarfed/activitystreams-unofficial>/
<https://github.com/snarfed/activitystreams-unofficial>snarfed
<https://github.com/snarfed/activitystreams-unofficial>/
<https://github.com/snarfed/activitystreams-unofficial>
activitystreams-unofficial
<https://github.com/snarfed/activitystreams-unofficial> for major social
sites to AS1 which could be helpful if you wanted to start writing a
converter for them to AS2

If you took Common Social Media Posts and categorized them into a rating
system of some sort and focused on the TOP 10 and made sure technology like
jason-ld was headed in the direction to include this kind of data, we would
all get somewhere faster. Of course -- my opinion. If Jason-ld is not the
Correct format -- and this Streams project is not the correct project --
then point me somewhere please.

—
Reply to this email directly or view it on GitHub
<https://github.com/jasnell/w3c-socialwg-activitystreams/issues/133#issuecomment-109881652>
.

**Comment by jasnell** [comment]
Based on discussion on the conf call, this is fine but we need volunteers to help work up the specific examples.

**Comment by evanp** [comment]
Per discussion, I'll break this omnibus issue into 8 separate issues, one for each example type, and then close this issue.
