### ISSUE TITLE
introduce QualifiedRelation and adjust Connection accordingly

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#135]
I find current modeling of *[as:Connection](http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams2-vocabulary.html#dfn-connection)* possibly confusing, especially with cryptic *[as:a](http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams2-vocabulary.html#dfn-a-term)* and *[as:b](http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams2-vocabulary.html#dfn-b-term)* properties.

We could introduce generic **QualifiedRelation** based on [Qualified Relation Pattern](http://patterns.dataincubator.org/book/qualified-relation.html), [N-ary Relations](http://www.w3.org/TR/swbp-n-aryRelations/) and [Reification](http://www.w3.org/TR/rdf-schema/#ch_reificationvocab) with **Relationship** sub class.

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "Connection",
  "a": {
    "@type": "Person",
    "displayName": "Sally"
  },
  "relationship": "http://purl.org/vocab/relationship/closeFriendOf",
  "b": {
    "@type": "Person",
    "displayName": "John"
  }
```

would become

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "Relationship",
  "subject": {
    "@type": "Person",
    "displayName": "Sally"
  },
  "property:": "http://purl.org/vocab/relationship/closeFriendOf",
  "object": {
    "@type": "Person",
    "displayName": "John"
  }
```

1. *as:subject* sounds like a good match to already defined *as:object* and *as:actor*
2. *as:property* might sound more familiar than possible alternative - *as:predicate*
3. *as:Relationship* matches more closely current description of *as:Connection* and suggested use of properties from [RELATIONSHIP vocab](http://vocab.org/relationship/.html) `Describes a connection between two individuals. The a and b properties are used to identify the connected individuals.`
4. we could keep *as:relationship* as *rdfs:subPropertyOf as:property*
5. we could define *as:rel* as *rdfs:subPropertyOf as:property*

I slowly start gathering examples of other possibly useful Qualified (Nary) Relation sub classes here:
https://github.com/w3c-social/social-vocab#qualified-relation

for example

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "Attendance",
  "subject": {
    "@type": "Event",
    "displayName": "Social WG: F2F3"
  },
  "property:": "http://schema.org/attendee",
  "object": {
    "@type": "Person",
    "displayName": "John"
  }
```

![Attendance](https://docs.google.com/drawings/d/1WQaXja2Q6cu_jVLf60umYdbbY1XBjBpJWUIdgSbNHUU/pub?w=1016&h=556)

**Comment by jasnell** [comment]
I'm generally fine with this really. It doesn't change the model just renames things to be a bit clearer. However, this overloads the `object` property in a way I'm not comfortable with. `object` is currently a property of `Activity` and has very clear semantics. Using it hear would muddy that a bit. It's better to use a different term. Also, `rel` really has nothing to do with this particular object so let's leave that one out.

**Comment by elf-pavlik** [comment]
> However, this overloads the object property in a way I'm not comfortable with. object is currently a property of Activity and has very clear semantics. 

IMO using as:object makes perfect sense here, this diagram of *Follow* Activity and *Following* Qualified relation illustrates it nicely. In practice *object* of an Activity should always match *object* of matching QualifiedRelation (while actor of Activity becomes a subject of QualifiedRelation)

![Follow & Following](https://docs.google.com/drawings/d/1zFWdjo_phs60Lr7dyoXyd4PQ9hOBxadlU8FZDQIAPHg/pub?w=960&h=540)

https://github.com/w3c-social/social-vocab/blob/master/activity/Follow/README.md

I currently think about going again to modeling which uses *verb*/*action* (rdf:Property) instead of rdfs:subClassOf Activity. This way one can use same *verb*/*action* for unqualified relation *likes*/*follows*, Activity *likes*/*follows* and QualifiedRelation *likes*/*follows*. Hopefully will do proper write up about it and share with the group in next week or two!

**Comment by jasnell** [comment]
I have made these changes into the current editor's draft. I went ahead and used `object` for now. We can change it later if necessary.

**Comment by elf-pavlik** [comment]
awesome! thanks @jasnell
