### ISSUE TITLE
Lack of @id in examples

### ISSUE THREAD

**Issue by alexanderkjeldaas** [jasnell/w3c-socialwg-activitystreams#138]
Maybe this is the wrong tracker, but the lack of `@id` attributes in the vocabulary examples bothers me a bit.  I'm especially struggling with the Page example where the url property is specified instead of `@id`. 

Why would a Page have a list of one secondary representations, but no global identifier?  All these examples are to me like rows in a table with no primary key.

How about documenting the `url` property as *additional*, secondary representations of the object.  I am personally advocating using the URL as primary key for a Page object and the example is giving me second thoughts.

**Comment by jasnell** [comment]
We can add `@id` to the examples. A PR is helpful :-)

**Comment by gobengo** [comment]
@alexanderkjeldaas The simplest way to give everything in the vocab doc a valid `@id` is to give each of them a UUID URN like `urn:uuid:04459406-03f5-11e5-8668-7831c1cf2c8e`. I could make a PR for that.

<blockquote>
All these examples are to me like rows in a table with no primary key.
</blockquote>
You may find it valuable to align your mental model more with thinking about graphs than "rows in a table". For example, any of the examples in the vocabulary could validly have multiple `@id` values (e.g. a UUID URN and a URL). The concept of 'primary key' doesn't fit so well, or at least it's just one application of the expressivity of this syntax/semantics.

<blockquote>How about documenting the url property as additional, secondary representations of the object.</blockquote>
I think the current "Identifies one or more links to representations of the object" is better than the loosely-defined notion of 'additional' and 'secondary' representations. Not all web-browser-friendly Pages have public URLs (e.g. `file://...`).

**Comment by akuckartz** [comment]
> any of the examples in the vocabulary could validly have multiple @id values (e.g. a UUID URN and a URL).

_Thats_ interesting. I would consider it pathological to have multiple @id with URLs and think that this should perhaps be excluded in the spec. But perhaps one URN and one dereferencable URL _might_ make sense in some context: any use cases?

**Comment by alexanderkjeldaas** [comment]
@gobengo  Thinking in terms of graphs does not really solve the issue.  There are two problems for me:

1. It is not specified whether the example specifies the full set of edges out from the Page object.
2. It is not specified whether a property _should_ have only a single edge or multiple.

Without knowing those two things, it is easy to reason about what `@id` represents.  It is much easier to see what properties are singletons and which ones are sets when `@id` is specified.

**Comment by alexanderkjeldaas** [comment]
I guess my question can be asked like this:  Why is a web page not identified by an URL?

**Comment by jasnell** [comment]
The @id and url serve two distinct purposes. It's perfectly valid to have a non-dereferenceable @id. It's also possible to have more than one url value and for that url value to be a qualified reference (as:Link). There's nothing stopping the url and @id from specifying the same URL reference, however.


Example:
```
{
  "@id": "http://example.com/img",
  "@type": "Image",
  "url": [
    {
      "href": "http://example.com/img",
      "mediaType": "image/png"
    },
    {
      "href": "http://example.com/img",
      "mediaType": "image/jpeg"
    }
  ]
}
```

**Comment by gobengo** [comment]
@akuckartz <blockquote>I would consider it pathological to have multiple @id with URLs and think that this should perhaps be excluded in the spec. But perhaps one URN and one dereferencable URL might make sense in some context: any use cases?</blockquote>
I did some research and learned that I was wrong about this. In JSON-LD, the value of "@id" must be a string, whereas most (all?) other keys (e.g. "@type") can be an array. ([playground example](http://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40id%22%3A%5B%22urn%3Auuid%3A0%22%2C%22urn%3Auuid%3A1%22%5D%7D)). Sorry all for any confusion this caused.

A use case for non-dereferencable IDs is if the author of the data is not the owner of the domain/URLs that currently point to the 'Pages' or other objects that the dataset wants to describe. For example, maybe I'm describing today's contents of the homepage of CNN with URL `http://cnn.com/` including the stories, headlines, people mentioned. The stuff at that URL is changing all the time, but it may be useful to give today/now/my snapshot of it a permanent id of a URN so it can be referred to for all time.

**Comment by gobengo** [comment]
@alexanderkjeldaas 
<blockquote>It is not specified whether the example specifies the full set of edges out from the Page object.</blockquote>
They aren't the full set, at least becase Page extends [Document](http://www.w3.org/TR/2015/WD-activitystreams-vocabulary-20150129/#dfn-document) extends [Content](http://www.w3.org/TR/2015/WD-activitystreams-vocabulary-20150129/#dfn-content), which has duration, height, and width properties defined that are not in the Page example.

<blockquote>It is not specified whether a property should have only a single edge or multiple</blockquote>
AFAICT, any property can have one or more values, which is specified in [the JSON-LD syntax](http://www.w3.org/TR/json-ld/#sets-and-lists). The only mention of cardinality limits is in the [Non-normative Ontology Definition](http://www.w3.org/TR/2015/WD-activitystreams-vocabulary-20150129/#non-normative-ontology-definition) of as:IntransitiveActivity, which basically just clarifies that those can't have an object.

<blockquote>Without knowing those two things, it is not easy to reason about what @id represents.</blockquote>
I think the most canonical definition from [here](http://www.w3.org/TR/json-ld/#syntax-tokens-and-keywords)

**Comment by gobengo** [comment]
<blockquote>I mean, it is unreasonable to have a web page not be identified by something I can write into an url bar in a browser.</blockquote>

See the use case [above](https://github.com/jasnell/w3c-socialwg-activitystreams/issues/138#issuecomment-111218331) of describing a snapshot of a Page in time that may not always be accessible at the same URL. e.g. homepages are frequently personalized or changed every few minutes/hours.

Also: Intranet pages, pages accessible over nonstandard protocols (e.g. [tor](https://www.torproject.org/), [ipfs](http://ipfs.io/)). I'd argue that it is 'unreasonable' to do any of these things or want the web vocabulary to be able to apply to them.

**Comment by jasnell** [comment]
Closing. Does not appear to be anything further to do here.
