### ISSUE TITLE
Re-add `Organization` Actor Type

### ISSUE THREAD

**Issue by jasnell** [jasnell/w3c-socialwg-activitystreams#153]
The `Organization` Actor Type was removed from the vocabulary due to lack of use cases. There is a proposal to reintroduce it based on new use cases (see: https://lists.w3.org/Archives/Public/public-socialweb/2015Jul/0002.html). I'm +1 on reintroducing it.

/cc @evanp

**Comment by evanp** [comment]
I definitely agree on this. Many social network systems have special account types for brands and companies; for example, Facebook and Google+. I think it makes sense to have an Organization type to represent companies and other organizations.
