### ISSUE TITLE
Vocabulary item for "Blog" type

### ISSUE THREAD

**Issue by evanp** [jasnell/w3c-socialwg-activitystreams#157]
The core document, in example 6, uses "urn:example:types:blog" as the type for a blog. Since this is a pretty core type which we're using for one of the first examples, it should probably be a Vocabulary class instead.

I'd compare the Album type in example 7. They're very similar types.

**Comment by jasnell** [comment]
I'm not convinced actually. A blog is essentially an ordered collection of articles or notes. It can easily be represented using either `as:Collection` or `as:OrderedCollection`. One could even use `as:Story` to represent this.

**Comment by jasnell** [comment]
Landed this change: https://github.com/jasnell/w3c-socialwg-activitystreams/commit/0e3d4fa98bc8fd6cb0fe36c6c01b59ab9b24eae1

It replaces the use of `urn:example:types:blog` with `OrderedCollection`.

Going to keep this issue open, however, so we can deal with the question of whether we need a specific object type for Blog.

**Comment by akuckartz** [comment]
:+1: for using OrderedCollection.

**Comment by csarven** [comment]
I think `as:Collection` is appropriate. An order need not be imposed. Collection containing any combination of the available Object Types seems reasonable to me for a Blog.

**Comment by jasnell** [comment]
@evanp ... are you fine with me closing this? Is this something you wanted to pursue further?

**Comment by evanp** [comment]
So, will we keep Album but not Blog? It really feels like we're missing a fundamental social data type.

That said, I'm willing to grit my teeth and bare it, if we change the janky URN type in the example to the recommended type. Collection-of-Articles, I guess?

**Comment by jasnell** [comment]
Given that (a) there is zero consensus around even the fundamental aspects of the social API and (b) zero notion of what the key social data types the API will be dealing with are, it's likely better to stick with the fairly minimal set we have now or even pair back on the ones we do have (I'd be amenable to removing Album, for instance).

**Comment by rpeinl** [comment]
+1 for using OrderedCollection. Otherwise we end up with a dozen different container objects like Wiki library, discussion forum, ...
I'm also not sure about Story. Seems strange to me, but that should probably discussed in a different issue.

**Comment by elf-pavlik** [comment]
What property/properties do we use to 'follow our nose' from Actor to its Collections eg. Blog or Album?
@rhiaro [mentions it in SocialAPI Editor's Draft](http://w3c-social.github.io/SocialAPI/socialapi#discovery) but relating Actor with relevant collections seems like Data Model responsibility.

See also:
* #191  
* #221 & https://github.com/w3c-social/SocialAPI/issues/1

>  (I'd be amenable to removing Album, for instance)
:+1: 

SIOC Types Module already defines various relevant types - http://rdfs.org/sioc/spec/#sec-modules

**Comment by jasnell** [comment]
On Nov 3, 2015 4:08 AM, "elf Pavlik" <notifications@github.com> wrote:
>
> What property/properties do we use to 'follow our nose' from Actor to its
Collections eg. Blog or Album?

These aren't properties, they are object types, so the question does not
make sense.

> @rhiaro mentions it in SocialAPI Editor's Draft but relating Actor with
relevant collections seems like Data Model responsibility.
>

The basic mechanism is there already. I had a PR that suggested adding a
handful of properties for this purpose but it didn't get consensus.

- James

> See also:
>
> #191
> #221 & w3c-social/SocialAPI#1
>>
>> (I'd be amenable to removing Album, for instance)
>
> SIOC Types Module already defines various relevant types -
http://rdfs.org/sioc/spec/#sec-modules

**Comment by wilkie** [comment]
Removing Album makes a little bit of sense in this context, doesn't it? A Collection of images/media is an Album, then a Collection of Articles are a Blog... but if a Collection is good enough for Blog, then it is good enough for Album, yes? Maybe a solution is having a Collection that has some metadata describing what types of objects are within it instead of all of these potential fairly-specific subclasses of that behavior... but maybe that's what calling something an "Album" says... but maybe "Collection of Images" or "Collection of Articles" says a little bit more.

**Comment by jasnell** [comment]
@evanp ... here's an alternative proposal: https://github.com/jasnell/w3c-socialwg-activitystreams/issues/239#issuecomment-153896264

**Comment by elf-pavlik** [comment]
>  > What property/properties do we use to 'follow our nose' from Actor to its Collections eg. Blog or Album?

> These aren't properties, they are object types, so the question does not
make sense.

usually we don't *follow our nose* using types but **properties** so the question stays valid, to explain it further

1. I fetch profile document describing instance of as:Person
2. Which property (attribute), with this person as subject (entity), has various collections published by this person, which one can subscribe to, as objects (values)?

for example http://microformats.org/wiki/existing-rel-values includes *feed*
which i see in use on https://ben.thatmustbe.me by @dissolve

**Comment by azaroth42** [comment]
:+1: to OrderedCollection in the example
