### ISSUE TITLE
"strongly discouraged" -> SHOULD NOT

### ISSUE THREAD

**Issue by evanp** [jasnell/w3c-socialwg-activitystreams#159]
In section 3.2, it says:

 > While Activity Streams 2.0 implementations MAY use JSON-LD value objects in this manner, doing so is strongly discouraged. 

We should probably use RFC 2119 terminology:

> Activity Streams 2.0 implementations SHOULD NOT use JSON-LD value objects in this manner.

**Comment by akuckartz** [comment]
:+1:

**Comment by jasnell** [comment]
PR? :smile:
