### ISSUE TITLE
Strongly recommend vCard for Person and Group for interoperability

### ISSUE THREAD

**Issue by evanp** [jasnell/w3c-socialwg-activitystreams#160]
In section 3.4, vCard is lightly recommended for extensions to Actor classes:

> This specification intentionally defines Actors in only the most generalized way, stopping short of defining semantically specific properties for each. All Actor objects are specializations of Object and inherit all of the core properties common to all Object's. External vocabularies (VCard for instance) can be used to express additional detail not covered by the Activity Vocabulary. 

For interoperability, it'd be great to strongly encourage vCard for Person and Group:

> External vocabularies can be used to express additional detail not covered by the Activity Vocabulary. VCard SHOULD be used for contact information for Person and Group instances.

**Comment by jasnell** [comment]
:+1:
