### ISSUE TITLE
automated testing for results of parsing all examples as JSON-LD

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#17]
I just tried parsing [example Action](http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams2.html#actions) using provided [Non-Normative JSON-LD @context](http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams2.html#json-ld-context). We can see [results on JSON-LD Playground](http://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%5B%7B%22dc%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2F%22%2C%22dct%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%22%2C%22dctypes%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fdcmitype%2F%22%2C%22foaf%22%3A%22http%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%22%2C%22vcard%22%3A%22http%3A%2F%2Fwww.w3.org%2F2006%2Fvcard%2Fns%23%22%2C%22org%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Forg%23%22%2C%22prov%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fprov%23%22%2C%22geo%22%3A%22http%3A%2F%2Fld.geojson.org%2Fvocab%23%22%2C%22link%22%3A%22http%3A%2F%2Fwww.iana.org%2Fassignments%2Flink-relations%23%22%7D%2C%7B%22as%22%3A%22http%3A%2F%2Factivitystrea.ms%2F2.0%2F%22%2C%22deprecated%22%3A%22http%3A%2F%2Factivitystrea.ms%2F1.0%2F%22%2C%22id%22%3A%22%40id%22%2C%22language%22%3A%22%40language%22%2C%22objectType%22%3A%7B%22%40id%22%3A%22as%3AobjectType%22%7D%2C%22displayName%22%3A%7B%22%40id%22%3A%22as%3AdisplayName%22%2C%22%40container%22%3A%22%40language%22%7D%2C%22rel%22%3A%22as%3Arel%22%2C%22mediaType%22%3A%22as%3AmediaType%22%2C%22verb%22%3A%7B%22%40id%22%3A%22as%3Averb%22%7D%2C%22actor%22%3A%7B%22%40id%22%3A%22as%3Aactor%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22object%22%3A%7B%22%40id%22%3A%22as%3Aobject%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22target%22%3A%7B%22%40id%22%3A%22as%3Atarget%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22result%22%3A%7B%22%40id%22%3A%22as%3Aresult%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22instrument%22%3A%7B%22%40id%22%3A%22as%3Ainstrument%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22participant%22%3A%7B%22%40id%22%3A%22as%3Aparticipant%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22priority%22%3A%7B%22%40id%22%3A%22as%3Apriority%22%2C%22%40type%22%3A%22xsd%3Afloat%22%7D%2C%22status%22%3A%7B%22%40id%22%3A%22as%3Astatus%22%2C%22%40type%22%3A%22%40vocab%22%7D%2C%22completed%22%3A%7B%22%40id%22%3A%22as%3ACompletedStatus%22%7D%2C%22active%22%3A%7B%22%40id%22%3A%22as%3AActiveStatus%22%7D%2C%22canceled%22%3A%7B%22%40id%22%3A%22as%3ACanceledStatus%22%7D%2C%22pending%22%3A%7B%22%40id%22%3A%22as%3APendingStatus%22%7D%2C%22tentative%22%3A%7B%22%40id%22%3A%22as%3ATentativeStatus%22%7D%2C%22to%22%3A%7B%22%40id%22%3A%22as%3Ato%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22bto%22%3A%7B%22%40id%22%3A%22as%3Abto%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22cc%22%3A%7B%22%40id%22%3A%22as%3Acc%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22bcc%22%3A%7B%22%40id%22%3A%22as%3Abcc%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22alias%22%3A%7B%22%40id%22%3A%22as%3Aalias%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22author%22%3A%7B%22%40id%22%3A%22as%3Aauthor%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22content%22%3A%7B%22%40id%22%3A%22as%3Acontent%22%2C%22%40container%22%3A%22%40language%22%7D%2C%22duplicates%22%3A%7B%22%40id%22%3A%22as%3Aduplicates%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22icon%22%3A%7B%22%40id%22%3A%22as%3Aicon%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22image%22%3A%7B%22%40id%22%3A%22as%3Aimage%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22location%22%3A%7B%22%40id%22%3A%22as%3Alocation%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22published%22%3A%7B%22%40id%22%3A%22as%3Apublished%22%2C%22%40type%22%3A%22xsd%3AdateTime%22%7D%2C%22generator%22%3A%7B%22%40id%22%3A%22as%3Agenerator%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22provider%22%3A%7B%22%40id%22%3A%22as%3Aprovider%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22summary%22%3A%7B%22%40id%22%3A%22as%3Asummary%22%2C%22%40container%22%3A%22%40language%22%7D%2C%22updated%22%3A%7B%22%40id%22%3A%22as%3Aupdated%22%2C%22%40type%22%3A%22xsd%3AdateTime%22%7D%2C%22startTime%22%3A%7B%22%40id%22%3A%22as%3AstartTime%22%2C%22%40type%22%3A%22xsd%3AdateTime%22%7D%2C%22endTime%22%3A%7B%22%40id%22%3A%22as%3AendTime%22%2C%22%40type%22%3A%22xsd%3AdateTime%22%7D%2C%22validFrom%22%3A%7B%22%40id%22%3A%22as%3AvalidFrom%22%2C%22%40type%22%3A%22xsd%3AdateTime%22%7D%2C%22validUntil%22%3A%7B%22%40id%22%3A%22as%3AvalidUntil%22%2C%22%40type%22%3A%22xsd%3AdateTime%22%7D%2C%22validAfter%22%3A%7B%22%40id%22%3A%22as%3AvalidAfter%22%2C%22%40type%22%3A%22xsd%3AdateTime%22%7D%2C%22validBefore%22%3A%7B%22%40id%22%3A%22as%3AvalidBefore%22%2C%22%40type%22%3A%22xsd%3AdateTime%22%7D%2C%22rating%22%3A%7B%22%40id%22%3A%22as%3Arating%22%2C%22%40type%22%3A%22xsd%3Afloat%22%7D%2C%22tags%22%3A%7B%22%40id%22%3A%22as%3Atags%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22title%22%3A%7B%22%40id%22%3A%22as%3Atitle%22%2C%22%40container%22%3A%22%40language%22%7D%2C%22duration%22%3A%7B%22%40id%22%3A%22as%3Aduration%22%7D%2C%22height%22%3A%7B%22%40id%22%3A%22as%3Aheight%22%2C%22%40type%22%3A%22xsd%3AnonNegativeInteger%22%7D%2C%22width%22%3A%7B%22%40id%22%3A%22as%3Awidth%22%2C%22%40type%22%3A%22xsd%3AnonNegativeInteger%22%7D%2C%22inReplyTo%22%3A%7B%22%40id%22%3A%22as%3AinReplyTo%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22actions%22%3A%7B%22%40id%22%3A%22as%3Aactions%22%2C%22%40container%22%3A%22%40index%22%7D%2C%22scope%22%3A%7B%22%40id%22%3A%22as%3Ascope%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22totalItems%22%3A%7B%22%40id%22%3A%22as%3AtotalItems%22%2C%22%40type%22%3A%22xsd%3AnonNegativeInteger%22%7D%2C%22itemsPerPage%22%3A%7B%22%40id%22%3A%22as%3AitemsPerPage%22%2C%22%40type%22%3A%22xsd%3AnonNegativeInteger%22%7D%2C%22startIndex%22%3A%7B%22%40id%22%3A%22as%3AstartIndex%22%2C%22%40type%22%3A%22xsd%3AnonNegativeInteger%22%7D%2C%22items%22%3A%7B%22%40id%22%3A%22as%3Aitems%22%2C%22%40container%22%3A%22%40list%22%7D%2C%22itemsAfter%22%3A%7B%22%40id%22%3A%22as%3AitemsAfter%22%2C%22%40type%22%3A%22xsd%3AdateTime%22%7D%2C%22itemsBefore%22%3A%7B%22%40id%22%3A%22as%3AitemsBefore%22%2C%22%40type%22%3A%22xsd%3AdateTime%22%7D%2C%22first%22%3A%7B%22%40id%22%3A%22link%3Afirst%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22last%22%3A%7B%22%40id%22%3A%22link%3Alast%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22prev%22%3A%7B%22%40id%22%3A%22link%3Aprev%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22previous%22%3A%7B%22%40id%22%3A%22link%3Aprev%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22next%22%3A%7B%22%40id%22%3A%22link%3Anext%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22current%22%3A%7B%22%40id%22%3A%22link%3Acurrent%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22self%22%3A%7B%22%40id%22%3A%22link%3Aself%22%2C%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22replies%22%3A%7B%22%40id%22%3A%22as%3Areplies%22%2C%22%40container%22%3A%22%40index%22%7D%2C%22url%22%3A%7B%22%40id%22%3A%22as%3Aurl%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22downstreamDuplicates%22%3A%7B%22%40id%22%3A%22deprecated%3AdownstreamDuplicates%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22upstreamDuplicates%22%3A%7B%22%40id%22%3A%22deprecated%3AupstreamDuplicates%22%2C%22%40type%22%3A%22%40id%22%7D%7D%5D%2C%22%40graph%22%3A%5B%7B%22objectType%22%3A%22video%22%2C%22id%22%3A%22http%3A%2F%2Fexample.org%2Fcats.mpg%22%2C%22actions%22%3A%7B%22watch%22%3A%22movie%3A%2F%2Fexample.org%2Fcats.mpg%22%2C%22share%22%3A%7B%22id%22%3A%22http%3A%2F%2Fexample.net%2Fshare%22%2C%22objectType%22%3A%22service%22%2C%22displayName%22%3A%22My%20Sharing%20Service%22%7D%2C%22embed%22%3A%5B%22http%3A%2F%2Fexample.org%2Fgadgets%2Fvideo.xml%3Fv%3Dcats.mpg%22%2C%7B%22objectType%22%3A%22inline-html%22%2C%22content%22%3A%22%3Cvideo%20...%20%2F%3E%22%7D%5D%7D%7D%5D%7D&context=%7B%7D)

```js
{
  "@id": "http://example.org/cats.mpg",
  "http://activitystrea.ms/2.0/actions": [
    {
      "@index": "embed",
      "@value": "http://example.org/gadgets/video.xml?v=cats.mpg"
    },
    {
      "@index": "embed",
      "http://activitystrea.ms/2.0/content": "<video ... />",
      "http://activitystrea.ms/2.0/objectType": "inline-html"
    },
    {
      "@id": "http://example.net/share",
      "@index": "share",
      "http://activitystrea.ms/2.0/displayName": "My Sharing Service",
      "http://activitystrea.ms/2.0/objectType": "service"
    },
    {
      "@index": "watch",
      "@value": "movie://example.org/cats.mpg"
    }
  ],
  "http://activitystrea.ms/2.0/objectType": "video"
}
```

I would like to help with automating parsing **all examples** as JSON-LD and verifying if they match hand written expected results.

**Comment by akuckartz** [comment]
:+1: Which tools can be used?

**Comment by elf-pavlik** [comment]
please see #32 where I use https://github.com/zazukoians/rdf-ext

**Comment by elf-pavlik** [comment]
moved to #65
