### ISSUE TITLE
"It is strongly recommended" -> "SHOULD"

### ISSUE THREAD

**Issue by evanp** [jasnell/w3c-socialwg-activitystreams#171]
In the last paragraph of section 3.6, it says:

 > Therefore, it is strongly recommended that OrderedCollection instances that use paging always include the first, next, prev and last paging properties.

We should use RFC 2119 terminology here:

 > OrderedCollection instances that use paging SHOULD include the first, next, prev and last paging properties.

**Comment by akuckartz** [comment]
:+1:

**Comment by jasnell** [comment]
:+1: PR?

**Comment by evanp** [comment]
Will do
