### ISSUE TITLE
What is an Activity Streams Document for?

### ISSUE THREAD

**Issue by evanp** [jasnell/w3c-socialwg-activitystreams#172]
Section 4 says:

>  Activity Streams Document

> An Activity Streams Document is a JSON-LD document whose root value is a Collection and whose MIME media type is "application/activity+json".

It's not clear why we define this. Is this the fundamental document type? Do we have to define the term in order to register the media type?

By this definition, a JSON-LD document with a single Note as a root value, for example, would not be an ASD. This kind of document is great for RESTful CRUD APIs. Should it not use the "application/activity+json" media type?

**Comment by jasnell** [comment]
I've been considering removing the `whose root value is a Collection` and replacing it with `whose root value is an as:Object of any type`

**Comment by evanp** [comment]
That'd be great with me. The other question, though, is why are we defining it? In order to do the media type registration?

**Comment by jasnell** [comment]
Yes.
