### ISSUE TITLE
Use HTML for content in example 130

### ISSUE THREAD

**Issue by evanp** [jasnell/w3c-socialwg-activitystreams#173]
Example 130 is about not having to parse microsyntax. It includes a content property with microsyntax:

 > "content": "Thank you @sally for all your hard work! #givingthanks"

It would be clearer that the consumer can safely ignore the microsyntax by instead using HTML in the content property:

> "content": "Thank you &lt;a href="http://example.org/people/sally">@sally&lt;/a> for all your hard work! &lt;a href="http://example.org/tags/givingthanks">#givingthanks&lt;/a>"

**Comment by jasnell** [comment]
Edited the above to correct the example content
