### ISSUE TITLE
Should we put some daylight between "Favorite" and "Like"?

### ISSUE THREAD

**Issue by evanp** [jasnell/w3c-socialwg-activitystreams#174]
Traditionally, with AS1, "Favorite" and "Like" have been synonyms. However, they're not always strictly synonymous on social systems.

On some social systems, to "Like" an object is an indication to the author and others that the liker approves of the object. An example from Facebook:

![comment-with-likes](https://cloud.githubusercontent.com/assets/6770/8553850/2d6ea018-24b4-11e5-8d3c-1ccec2f2a65f.png)

To "Favorite" an object usually encompasses the "Like" action, as here on Twitter:

![favorite-on-twitter](https://cloud.githubusercontent.com/assets/6770/8553862/4671895e-24b4-11e5-8512-0aff9ee0cc67.png)

... *plus* saving the object to a collection of "favorites".

![favorites-stream](https://cloud.githubusercontent.com/assets/6770/8553888/7b0a9c82-24b4-11e5-8a8a-965af6158198.png)

I'm ambivalent about making this distinction. If I really needed to do it, I'd probably make it two actions: one to `Like` and another to `Add` to a `Collection` called "Favorites".

**Comment by jasnell** [comment]
+1. I think having `as:Like` and `as:Favorite` as two separate Activity types is confusing and unnecessary. I'd rather remove `as:Favorite` in favor of the alternative approach of adding the item to a favorites collection.

(which, btw, brings up a related question: we currently have no mechanism by which to semantically differentiate the purposes of various collections. e.g. how do I know that a collection is my "favorites" collection)

**Comment by jasnell** [comment]
Removed favorite from the current editor's draft. Largely because of the overlap and the lack of any real justification for having it. Typically, one's "favorites" are really a collection of items that have been liked.
