### ISSUE TITLE
Should we have a type for the object of an "Offer" activity?

### ISSUE THREAD

**Issue by evanp** [jasnell/w3c-socialwg-activitystreams#175]
Example 106 in AS2 Vocabulary is for the Offer activity type. It uses the type "urn:examples:types:ProductOffer" for the object of the activity.

It may be worthwhile to expand this schema to cover one or more real types for offers.

**Comment by jasnell** [comment]
This would depend entirely on use cases. There are many different kinds of offers and there are other existing vocabularies that deal with those semantics (e.g. http://www.heppnetz.de/ontologies/goodrelations/v1.html#Offering). How much would we actually need to pull in?

**Comment by elf-pavlik** [comment]
Does `as:Invite` == `as:Offer` with `as:Join` as its object?
Can one offer someone to `as:Read` something or any other `as:Activity`? (following https://github.com/jasnell/w3c-socialwg-activitystreams/issues/162#issuecomment-135491490 )

**Comment by azaroth42** [comment]
:+1: to drop
