### ISSUE TITLE
Example for "Invite" activity is confusing

### ISSUE THREAD

**Issue by evanp** [jasnell/w3c-socialwg-activitystreams#176]
Example 111, for the Invite activity, has a `Person` `Invite` a `urn:example:types:Present` to a `Person`. This is confusing to me.

I think that inviting a `Person` to an `Event` or `Group` or both would make a lot more sense and be a clearer example.

**Comment by jasnell** [comment]
That may have just been a copy bug in the example. Can get that example fixed up.
