### ISSUE TITLE
Is "Announce" the new "Share"?

### ISSUE THREAD

**Issue by evanp** [jasnell/w3c-socialwg-activitystreams#179]
It doesn't seem like it's as good a name as "Share", which is used for several social networks to indicate re-amplifying some content by sharing to your followers.

That said, if it is the new Share, maybe it should be pointed out that the `object` should usually be an `Activity`.

**Comment by jasnell** [comment]
`as:Announce` is intended to provide separation between one particular activity and the act of announcing that activity to the world. For instance, previously in AS1, we used the "post" verb to identify the dual action of creating and publishing an object. In AS2, we could represent the same actions using separate `as:Create` and `as:Announce` actions.

One of the challenges with `as:Share` is that any Object or Activity that mentions another Object or Activity could technically be considered a share.
