### ISSUE TITLE
Represent bidirectional connections

### ISSUE THREAD

**Issue by evanp** [jasnell/w3c-socialwg-activitystreams#180]
The "Follow" Activity type lets us model unidirectional connections -- Evan following James means that Evan gets updates of James's activities, but not necessarily vice versa.

Many social networks (Facebook, LinkedIn) have bi-directional connections - one user "requests" friendship from another user, who then "accepts" or "rejects" it. Afterwards, both users get updates of each other's activities.

It would be good to be able to model this schema, since it's pretty common on social networks.

**Comment by jasnell** [comment]
```json
{
  "@context": [
    "http://www.w3.org/ns/activitystreams",
    {"colleagueOf": "http://purl.org/vocab/relationship/colleagueOf"}
  ],
  "@id": "http://example.org/connection-requests/123",
  "@type": "Offer",
  "actor": "acct:evan@example.org",
  "object": {
    "@id": "http://example.org/connections/123",
    "@type": "Relationship",
    "subject": "acct:evan@example.org",
    "relationship": "colleagueOf",
    "object": "acct:james@example.org"
  },
  "target": "acct:james@example.org"
}
```

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "Collection",
  "items": [
    {
      "@type": "Accept", 
      "actor": "acct:james@example.org",
      "object": "http://example.org/connection-requests/123"
    },
    {
      "@type": "Follow",
      "actor": "acct:james@example.org",
      "object": "acct:evan@example.org"
    },
    {
      "@type": "Follow",
      "actor": "acct:evan@example.org",
      "object": "acct:james@example.org"
    },
    {
      "@type": "Add", 
      "actor": "acct:james@example.org",
      "object": "http://example.org/connections/123",
      "target": {
        "@type": "Collection",
        "displayName": "James' Connections"
      }
    },
    {
      "@type": "Add", 
      "actor": "acct:evan@example.org",
      "object": "http://example.org/connections/123",
      "target": {
        "@type": "Collection",
        "displayName": "Evan's Connections"
      }
    }
  ]
}
```

**Comment by elf-pavlik** [comment]
I see major difference with a way how we verify both sides of given connection within silo and in decentralized network. Given 

```json
{
  "@id": "https://evan.example/connections/123",
  "@type": "Relationship",
  "subject": "https://evan.example",
  "relationship": "colleagueOf",
  "object": "https://james.example"
}
```

One needs a way to verify it from 'the other side', and not consider claim above as valid unless confirmed by something like:

```json
{
  "@id": "https://james.example/network/123",
  "@type": "Relationship",
  "subject": "https://james.example",
  "relationship": "colleagueOf",
  "object": "https://evan.example"
}
```

Of course we still need a way to verify authorship of claims above. For example with something like rev="author"

```json
{
  "@id": "https://james.example/",
  "@type": "Person",
  "@reverse": {
    "author": [
      "https://james.example/network/123"
    ]
  }
}
```

This comes very relevant to work happening in [W3C Credentials CG](https://www.w3.org/community/credentials/). Example above works similar to 'hosted credential' while more focus seems to go into 'signed credential' lately. Above scenario you could consider as sort of **FriendshipCredential**

Also very relevant conversation with @fosterlynn and @ahdinosaur with an example from a platform under development available in https://github.com/hackers4peace/plp-docs/issues/12#issuecomment-78043877

**Comment by elf-pavlik** [comment]
I illustrated it [in social-vocab repo](https://github.com/w3c-social/social-vocab/tree/master/verb/friends)

![friendship](https://docs.google.com/drawings/d/19ec81cfmoDwGjnQSADEduO7PpdacO0Y8k2YGgepyW_c/pub?w=1161&h=584)
