### ISSUE TITLE
Update example URLs to use different TLDs for each profile

### ISSUE THREAD

**Issue by aaronpk** [jasnell/w3c-socialwg-activitystreams#182]
There are four reserved domains that can be used in docs:

* example.com
* example.org
* example.net
* example.edu

Using these domains in the documentation will help demonstrate that the various actors are using separate websites and separate software. To make the examples a little more personal, they could use subdomains of these, such as alice.example.com, bob.example.org.

**Comment by aaronpk** [comment]
It looks like there is at least 2 occurrences of an object with both example.org and example.com domains, so apologies if there are no other examples that need this added.

**Comment by elf-pavlik** [comment]
bob.example , alice.example , acme.example etc.
https://en.wikipedia.org/wiki/.example

**Comment by jasnell** [comment]
@aaronpk ... closing this due to lack of action. If this is something you'd like to pursue, please open a PR with the requested changes. Thank you!
