### ISSUE TITLE
An Object's Purpose

### ISSUE THREAD

**Issue by jasnell** [jasnell/w3c-socialwg-activitystreams#188]
Certain aspects of the API proposals imply that a user will have multiple collections of objects, each with a distinct purpose. For instance, a collection of items posted, a collection of items favorited, a collection of items saved, a collection of blocked users, etc. 

The current vocabulary currently allows us to describe collections, but does not give us a way of identifying the purpose of the collection. That is, I cannot look at a collection and determine that it's intent is to contain favorited objects. I could look at the containing items and infer the intent, but that's not always reliable.

There are two approaches we can take to allow *explicit* indication of purpose: 

1. We can use `@type`. E.g. `"@type": ["Collection", "ex:Favorites"]`
2. We can introduce a `purpose` or `role` property. E.g. `"purpose": "ex:Favorites"`

Using Type:
```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": ["Collection", "http://example.org/Favorites"],
  "items": [] 
}
```
Using Purpose:
```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "Collection",
  "purpose": "http://example.org/Favorites",
  "items": [] 
}
```
In the former, the interpretation is "This is is a Favorites Collection". In the latter, the interpretation is "This is a Collection with the purpose of containing Favorited items".

Either would suffice. 

The secondary challenge with this is whether we need to come up with an initial, minimal core set of "purpose" identifiers.

/cc @evanp

**Comment by jasnell** [comment]
The concept of purpose here is very similar to the Web Annotation model's concept of a motivation. It essentially answers the question "Why does this exist" and therefore helps us to understand the context in which the thing exists.

**Comment by tantek** [comment]
Based on today's call, I think it makes more sense (simpler design) to just have discoverability of collections, e.g. rel values, rather than collections have any kind of special type/purpose properties themselves.

**Comment by jasnell** [comment]
If we take the discoverability approach instead, we can either use link rels or follow the pattern used by pump.io (https://github.com/e14n/pump.io/blob/master/API.md#collection-properties). If we use the pump.io approach, then we need to define the properties either in the normative context as part of the vocabulary or use an extension context. If we use the link rel approach, we'd be reusing as:Link and would need a property to anchor to.

In other words, using the pump.io approach, we'd end up with something like (assuming the collection properties are defined in our core vocabulary):
```json
{
  "@context": "http://www.w3.org/ns/activitystreams"
  "@type": "Person",
  "followers": "http://example.org/followers",
  "following": "http://example.org/following",
  "lists": "http://example.org/lists"
}
```

Using the link rel approach, we'd end up with something like:
```json
{
  "@context": "http://www.w3.org/ns/activitystreams"
  "@type": "Person",
  "collection": [
    {
      "@type": "Link",
      "href": "http://example.org/followers",
      "rel": "followers"
    },
    {
      "@type": "Link",
      "href": "http://example.org/following",
      "rel": "following"
    },
    {
      "@type": "Link",
      "href": "http://example.org/lists",
      "rel": "lists"
    }
  ]
}
```

My preference is for the latter, but it means going through the overhead of defining a core minimal set of collection properties (we already have precedence for this in the vocabulary with the `replies` property)

**Comment by elf-pavlik** [comment]
some existing relevant work documented on our wiki:
https://www.w3.org/wiki/Socialwg/Collection_Comparison

especially:
* https://www.w3.org/community/hydra/wiki/Collection_Design
* http://www.w3.org/TR/ldp/#ldpdc

some notes also in
* https://github.com/w3c-social/social-vocab/tree/master/container/DirectContainer
