### ISSUE TITLE
as:Collection semantics

### ISSUE THREAD

**Issue by azaroth42** [jasnell/w3c-socialwg-activitystreams#193]
The Collection object's properties appear to merge both properties from the page (next, self, startIndex, etc) and from the complete set (totalItems, itemsPerPage, etc).

* Should there be a distinction between the full Collection, and the individual pages?
* Is itemsPerPage actually useful? If it's not consistent, then it's not valid to assert against the collection (as it differs per response) and if it is, then it's just items.length or orderedItems.length as appropriate.
* Assuming that the semantics of startIndex are: the position of the first item in items within the complete Collection ... it would only be valid on OrderedCollection? Should this be specified at the vocabulary level?
* What is the range of the items term?  If it can take both an rdf:List and any arbitrary resource, isn't the ordering case ambiguous between an OrderedCollection with a single item that happens to be a list of 3 resources, and an OrderedCollection of three resources?  The class doesn't determine the semantics of items. Suggest mapping to two separate predicates in the underlying vocabulary... the JSON-LD will end up the same, but it'll make the RDF clearer.
* What's the rationale for the self relation rather than just using @id?
* Per personal correspondence, any resource can be used as members of the Collection. It would be nice to make that explicit in the text rather than the current implication of the first sentence that it can only be as:Object or as:Link.

Happy to split these out to individual issues if you would prefer.
(Interop trackers: w3c/web-annotation#50 and IIIF/iiif.io#500)

**Comment by jasnell** [comment]
One idea I would entertain is to view the Collection and OrderedCollection object types as distinct pages of a logical collection. To link multiple pages back to a common logical collection, we can introduce a `partOf` or `pageOf` type of property.

```json
{
  "@context": "http://www.w3.org/ns/activitystreams#",
  "@type": "Collection",
  "@id": "http://example.org/collections/123?page=0",
  "pageOf": "http://example.org/collections/123",
  "items": [ ... ]
}
```

**Comment by azaroth42** [comment]
:+1:

**Comment by jasnell** [comment]
Ok, so thinking it over, here's a proposal:

Currently, we have `Collection` and `OrderedCollection` that have these somewhat strangely placed page properties included. The proposal is:

1. Introduce new `PagedCollection`, `CollectionPage` and `OrderedCollectionPage` types; `OrderedCollectionPage` extends from `CollectionPage`. 
2. Allow `first`, `last` and `current` properties on `PagedCollection` to indicate the first, last and current pages of the Paged Collection. (`current` identifies the page with the most recently published/updated items).
3. Allow `first`, `last`, `next`, `prev` and `current` properties on `CollectionPage`.
4. Make `itemsPerPage` a property on `PagedCollection`
5. Move `startIndex` to `OrderedCollectionPage`
6. Introduce as:pageOf as a property on `CollectionPage` to allow a page to point back to it's 

Specifically:

```turtle
as:PagedCollection a owl:Class ;
  rdfs:subClassOf as:Collection .

# A Collection Page is essentially a collection containing a 
# subset of members from a full logical collection.
as:CollectionPage a owl:Class ;
  rdfs:subClassOf as:Collection .

as:OrderedCollectionPage a owl:Class ;
  rdfs:subClassOf as:OrderedCollection, as:CollectionPage .

as:pageOf a owl:FunctionalProperty, 
           owl:ObjectProperty ;
  rdfs:label "pageOf"@en;
  rdfs:domain as:CollectionPage ;
  rdfs:range [
    a owl:Class ;
    owl:unionOf (as:Collection as:Link )
  ] .

as:first a owl:FunctionalProperty ,
           owl:ObjectProperty ;
  rdfs:label "first"@en ;
  rdfs:domain [
    a owl:Class ;
    owl:unionOf (as:PagedCollection as:CollectionPage )
  ] ;
  rdfs:range [
    a owl:Class ;
    owl:unionOf ( as:CollectionPage as:Link )
  ] .

as:last a owl:FunctionalProperty ,
           owl:ObjectProperty ;
  rdfs:label "last"@en ;
  rdfs:domain [
    a owl:Class ;
    owl:unionOf (as:PagedCollection as:CollectionPage )
  ] ;
  rdfs:range [
    a owl:Class ;
    owl:unionOf ( as:CollectionPage as:Link )
  ] .

as:current a owl:FunctionalProperty ,
           owl:ObjectProperty ;
  rdfs:label "current"@en ;
  rdfs:domain [
    a owl:Class ;
    owl:unionOf (as:PagedCollection as:CollectionPage )
  ] ;
  rdfs:range [
    a owl:Class ;
    owl:unionOf ( as:CollectionPage as:Link )
  ] .

as:next a owl:FunctionalProperty ,
           owl:ObjectProperty ;
  rdfs:label "prev"@en ;
  rdfs:domain as:CollectionPage ;
  rdfs:range [
    a owl:Class ;
    owl:unionOf ( as:CollectionPage as:Link )
  ] .

as:prev a owl:FunctionalProperty ,
           owl:ObjectProperty ;
  rdfs:label "prev"@en ;
  rdfs:domain as:CollectionPage ;
  rdfs:range [
    a owl:Class ;
    owl:unionOf ( as:CollectionPage as:Link )
  ] .

as:itemsPerPage a owl:DatatypeProperty ,
          owl:FunctionalProperty ;
  rdfs:label "itemsPerPage"@en ;
  rdfs:comment "The maximum number of items per page in a logical Collection"@en ;
  rdfs:range xsd:nonNegativeInteger ;
  rdfs:domain as:PagedCollection .

as:startIndex a owl:DatatypeProperty ,
        owl:FunctionalProperty ;
  rdfs:label "startIndex"@en ;
  rdfs:comment "In a strictly ordered logical collection, specifies the index position of the first item in the items list"@en ;
  rdfs:range xsd:nonNegativeInteger ;
  rdfs:domain as:OrderedCollectionPage .
```

Example: Simple Unpaged Collection (exactly what we have now, except without paging properties)

```json
{
  "@type": "Collection",
  "@id": "http://example.org/collection",
  "totalItems": 75,
  "items": [ ... ]
}
```

Example: Simple Paged Collection

```json
{
  "@type": "PagedCollection",
  "@id": "http://example.org/collection",
  "first": "http://example.org/collection?page=0",
  "last": "http://example.org/collection?page=2",
  "itemsPerPage": 25,
  "totalItems": 75
}
```
```json
{
  "@type": "CollectionPage",
  "@id": "http://example.org/collection?page=0",
  "pageOf": "http://example.org/collection",
  "next": "http://example.org/collection?page=1"
  "first": "http://example.org/collection?page=0",
  "last": "http://example.org/collection?page=2",
  "totalItems": 25,
  "items": [ ... ]
}
```
```json
{
  "@type": "CollectionPage",
  "@id": "http://example.org/collection?page=1",
  "pageOf": "http://example.org/collection",
  "prev": "http://example.org/collection?page=0",
  "next": "http://example.org/collection?page=2",
  "first": "http://example.org/collection?page=0",
  "last": "http://example.org/collection?page=2",
  "totalItems": 25,
  "items": [ ... ]
}
```
```json
{
  "@type": "CollectionPage",
  "@id": "http://example.org/collection?page=2",
  "pageOf": "http://example.org/collection",
  "prev": "http://example.org/collection?page=1",
  "first": "http://example.org/collection?page=0",
  "last": "http://example.org/collection?page=2",
  "totalItems": 25,
  "items": [ ... ]
}
```

Example: Paged Ordered Collection

```json
{
  "@type": ["PagedCollection", "OrderedCollection"],
  "@id": "http://example.org/collection",
  "first": "http://example.org/collection?page=0",
  "last": "http://example.org/collection?page=2",
  "itemsPerPage": 25,
  "totalItems": 75
}
```
```json
{
  "@type": "OrderedCollectionPage",
  "@id": "http://example.org/collection?page=0",
  "pageOf": "http://example.org/collection",
  "next": "http://example.org/collection?page=1"
  "first": "http://example.org/collection?page=0",
  "last": "http://example.org/collection?page=2",
  "totalItems": 25,
  "startIndex": 0,
  "items": [ ... ]
}
```
```json
{
  "@type": "OrderedCollectionPage",
  "@id": "http://example.org/collection?page=1",
  "pageOf": "http://example.org/collection",
  "prev": "http://example.org/collection?page=0",
  "next": "http://example.org/collection?page=2",
  "first": "http://example.org/collection?page=0",
  "last": "http://example.org/collection?page=2",
  "totalItems": 25,
  "startIndex": 25,
  "items": [ ... ]
}
```
```json
{
  "@type": "OrderedCollectionPage",
  "@id": "http://example.org/collection?page=2",
  "pageOf": "http://example.org/collection",
  "prev": "http://example.org/collection?page=1",
  "first": "http://example.org/collection?page=0",
  "last": "http://example.org/collection?page=2",
  "totalItems": 25,
  "startIndex": 50,
  "items": [ ... ]
}
```

**Comment by azaroth42** [comment]
> * Introduce new `PagedCollection`, `CollectionPage` and `OrderedCollectionPage` types; `OrderedCollectionPage` extends from `CollectionPage`.

As soon as there's paging, there must be some inherent order to determine which item ends up on page 1 versus page 2? I assume that it's the difference between a Set and a List, where the recieving system should not assume there are any implications of the current order imposed by the serialization?
Clarifying the semantics of this distinction would be valuable for implementers to know when to use them.  

> * Allow `first`, `last` and `current` properties on PagedCollection to indicate the `first`, `last` and `current` pages of the Paged Collection. (current identifies the page with the most recently published/updated items).

:+1: Current would only be on OrderedCollection, where the order is by date?

> * Allow `first`, `last`, `next`, `prev` and current properties on `CollectionPage`.

:+1: 

> * Make `itemsPerPage` a property on `PagedCollection`

Thoughts on the utility of itemsPerPage? If it's consistent, then you can get it by looking at the number of items in the current response.  Or if it's not consistent, then I'm unsure of the value?  I guess it would be optional to include so there's no harm in defining it.

> * Move `startIndex` to `OrderedCollectionPage`

:+1: This makes the semantics of CPage vs OCPage clearer.

> * Introduce `as:pageOf` as a property on `CollectionPage` to allow a page to point back to its `Collection`

:+1:  subPropertyOf dcterms:isPartOf (or similar?)

Thanks James!

**Comment by jasnell** [comment]
> Current would only be on OrderedCollection, where the order is by date?

Not necessarily. The items in the current page are not necessarily ordered, they are just the ones that have been most recently updated. As a best practice, current *should* (not *must*) point to an OrderedCollectionPage, but that doesn't necessarily mean that the underlying logical collection is ordered (think of a folder that is generally unsorted but that provides a listing of the most recently updated files).

`itemsPerPage` is useful as informational metadata. Some may find it useful, others may not, but it doesn't hurt having it.

**Comment by azaroth42** [comment]
Sounds good to me :)

**Comment by csarven** [comment]
Leaving http://www.w3.org/TR/ldp-paging/ here for related reference. Will look at the commonalities.

**Comment by akuckartz** [comment]
See also https://github.com/HydraCG/Specifications/issues/36

**Comment by jasnell** [comment]
@azaroth42 ... ok, #199 proposes the revised collection model. It goes ahead and removes `itemsPerPage` and the `self` properties as those really aren't needed anymore with this proposal (`self` was always questionable anyway). The easiest way to view the proposed changes is to clone the repo and checkout of the `refactor-paging` branch then view the two index.html files in the browser. Please let me know if this addresses the issue you had.

**Comment by azaroth42** [comment]
Looks great! Especially the discussion about paging, very clear and concise. :+1:

**Comment by jasnell** [comment]
Resolved.
