### ISSUE TITLE
Remove (or clarify) Announce

### ISSUE THREAD

**Issue by rhiaro** [jasnell/w3c-socialwg-activitystreams#196]
I've been trying to fathom the use case for Announce, and can't come up with anything that isn't met by other activity types. The example in the vocab document is the announcement of Sally's arrival at a location, for which it seems to me posting an Arrive activity would suffice. The description of announce mentions alerting the `target`, but the example has no `target`, and I would've thought direct addressing via `cc`, `inReplyTo` or some other mention would do that.

I have read the explanation in #179 but I can't think of a case where I have seen this in any social networks I have used. The closest I can come to is something like 'pinned' posts on a forum, but this is a stretch. Please do say if I'm missing something obvious.

My proposal is to remove Announce, or improve the description and example to clarify its purpose based on use cases or observations from existing/past systems.

**Comment by csarven** [comment]
I've purposed `as:Announce` for _reposts_. Is there a more suitable activity?

As I understand `target`, its presence is not mandatory. A repost for example may be directed or not.

**Comment by jasnell** [comment]
Definitely -1 on removing Announce. The use case for Announce is to make the intent to notify explicit. For instance, a system may keep track of events such as Arrive, but not actually notify anyone that the event occurred. The Announce allows the notification activity to be performed separately from the thing being Announced.

**Comment by rhiaro** [comment]
Who/what is it being announced to though, if `target` is optional?

Does regular audience targeting *not* indicate an explicit intent to notify?

**Comment by jasnell** [comment]
The targeted audience can be explicit or implicit based on context (in other words, the implementation gets to choose).

**Comment by evanp** [comment]
@jasnell so, is it like a "retweet" or "share"?

**Comment by jasnell** [comment]
@evanp ... in a sense. The semantics of `Announce` are simply: `Call attention to this thing...`

**Comment by rhiaro** [comment]
And *how* attention is called is an implementation detail? Would `Announce`ing a `Note` of your own be expected to be treated the same way as `Announce`ing a `Note` by someone else? Or, by other object types? I'm trying to figure the practical implications.

**Comment by rhiaro** [comment]
Isn't "call attention to this thing" inconsistent with "the AS2 payload itself does not carry any behavioral semantics or expectations whatsoever." (https://lists.w3.org/Archives/Public/public-socialweb/2015May/0022.html) or am I misunderstanding?

**Comment by jasnell** [comment]
No. The part you quote refers to expectations on *implementations*. `Announce` specifies that the actor is calling special attention to the object.

**Comment by rhiaro** [comment]
That makes more sense.

**Comment by evanp** [comment]
So, we have "share" in AS1. I assumed since it's not in AS2, and Announce seems to have the same semantics, it's about the same.

**Comment by csarven** [comment]
As I see it, `Announce` comes across as a  super class to repost, share and other activities alike. The properties (and maybe even classes) in which it is used with gives more context.

**Comment by jasnell** [comment]
@csarven ... in a sense, yes.

**Comment by jasnell** [comment]
Closing as there does not appear to be anything to do here. Can reopen if necessary
