### ISSUE TITLE
Add repostOf property

### ISSUE THREAD

**Issue by rhiaro** [jasnell/w3c-socialwg-activitystreams#197]
Since the Share activity was removed, there's a gap in the market for reposting things, which is a common activity across many existing social networks.

Reposting could include additional original commentary, or just be a straight copy. Twitter, Tumblr and (I think) Facebook have now brought these options very close in terms of UI, ie. you hit retweet/reblog/share and have the option to add a comment or not; the process is very similar as far as the author is concerned; they don't have to choose the route they want to take in advance of deciding to share something. The difference in output compared with some other kind of mention is that the original post is rendered, along with additional content if provided.

As this is very close to Create (which is why I think Share was removed in the first place), my suggestion is to add a repostOf *property*, which would indicate the related post should be displayed in full, along with any additional `content` etc. 

The other option of course is a Repost activity type which is like Create but indicates the `object` should be displayed in full. Up for discussion.

**Comment by csarven** [comment]
re: Create, some relevant info: http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams-core/index.html#deprecated-syntax -- Specifically point 8.

Perhaps `as:Announce` with `as:content` may be sufficient for reposts?

**Comment by rhiaro** [comment]
What would the value of `content` be?

**Comment by jasnell** [comment]
-1 to adding `repostOf`. 

There are a variety of ways to do what you are suggesting.

1. Using `Announce` to call attention to the post being reshared:

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "Announce",
  "actor": "acct:sally@example.org", 
  "content": "I really like this note that Joe wrote! You should read it too!",
  "object": {
    "@type": "Note",
    "@id": "http://example.org/notes/123",
    "url": "http://example.org/notes/123",
    "attributedTo": "acct:joe@example.org",
    "displayName": "A note that Joe wrote",
    "content": "This is the note"
  }
}
```

2. Creating your own note and using `inReplyTo`:

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "Create",
  "actor": "acct:sally@example.org", 
  "object": {
    "@type": "Note",
    "@id": "http://example.org/notes/321",
    "url": "http://example.org/notes/321",
    "attributedTo": "acct:sally@example.org",
    "displayName": "A quick note",
    "content": "I really like Joe's comments in his note!",
    "inReplyTo": {
      "@type": "Note",
      "@id": "http://example.org/notes/123",
      "url": "http://example.org/notes/123",
      "attributedTo": "acct:joe@example.org",
      "displayName": "A note that Joe wrote",
      "content": "This is the note"
    }
  }
}
```

**Comment by rhiaro** [comment]
I'm not sure I can see how either of those indicate the contents of the original post ought to also be displayed.

A repost is semantically different from a reply.

I'm still not sure about the practical implications of Announce. What if you just want to repost something and have it behave the same way as any other post you create, not 'announce' it explicitly? (Which is the behaviour I see elsewhere).

**Comment by jasnell** [comment]
Whether or not to display the original post is entirely up to the implementer. If you simply want to repost something without wrapping it into an announce, then you simply repost it as is.

**Comment by rhiaro** [comment]
As in, just a `Create` activity where the `object` is [the URI of] an existing post?

**Comment by jasnell** [comment]
No, because you're not creating it. You could use `Add` tho:

```json
{
  "@context": "http://www.w3.org/ns/activitystreams#",
  "@type": "Add",
  "actor": "acct:sally@example.org",
  "object": {
    "@type": "Note", 
    "@id": "http://example.org/notes/123",
    "displayName": "A note that Joe wrote",
    "content": "This is a note that Joe wrote"
  }
}
```

**Comment by jasnell** [comment]
Closing as there does not appear to be anything to do here.
