### ISSUE TITLE
An example using AS and OA

### ISSUE THREAD

**Issue by csarven** [jasnell/w3c-socialwg-activitystreams#200]
Besides examples like `as:Place` and `gr:Location`, and `as:Like` and `schema:LikeAction`, which hover around the same concepts, it would be good to have an example that is slightly different. I'd like to propose: `as:Note` and `oa:Annotation`. I've described that and its purpose here: https://lists.w3.org/Archives/Public/public-socialweb/2015Aug/0050.html as it was derived from an inquiry made here: http://socialwg.indiewebcamp.com/irc/social/2015-08-13#t1439480142472 .  I can create a PR if agreed.

**Comment by jasnell** [comment]
PR's are always welcome :-)

**Comment by jasnell** [comment]
Associated PR was closed. Closing this. Can address in a new PR if one is submitted.
