### ISSUE TITLE
Is AS2 intended to be backwards-compatible with AS1?

### ISSUE THREAD

**Issue by csarven** [jasnell/w3c-socialwg-activitystreams#203]
Some discussion here:
https://github.com/jasnell/w3c-socialwg-activitystreams/issues/14#issuecomment-58206871
https://github.com/jasnell/w3c-socialwg-activitystreams/issues/23#issuecomment-58833788

Anything else to add to that base don current state of things?

**Comment by csarven** [comment]
Some discussion here: https://github.com/jasnell/w3c-socialwg-activitystreams/issues/23#issuecomment-58833788

Anything else to add to that base don current state of things?

**Comment by jasnell** [comment]
The answer is somewhat. It diverges from AS1 in a number of ways but defines clear rules for how to process AS1 documents as AS2.

**Comment by jasnell** [comment]
Closing as it is not clear that there's anything to do here. Can reopen if necessary
