### ISSUE TITLE
Object parameter "@id": Mandatory or not?

### ISSUE THREAD

**Issue by sgoendoer** [jasnell/w3c-socialwg-activitystreams#206]
What I noticed when digging into the specification of AS2:

"Object" is the "base" class for most other AS classes. It is even explicitly stated, that e.g. "Activity" extends "Object". Yet even though "Object" has a mandatory parameter "@id" (being an IRI), this "@id" never shows up in any examples or specifications of subclasses such as "Activity".

http://www.w3.org/TR/activitystreams-core/, Section 3.1 states that 
> In addition to having a global identifier (expressed as an absolute IRI using the JSON-LD @id keyword) and an "object type" (expressed using the JSON-LD @type keyword), all instances of the Object class share a common set of properties normatively defined by the Activity Vocabulary.

Is "@id" actually a mandatory thing? I think either it should be marked as optional or added to the examples.

**Comment by jasnell** [comment]
Not mandatory but I see that the spec does not make that clear. I'll see if I can add some clarifying text.

**Comment by jasnell** [comment]
Ok, I've got an edit pending for this in a batch of other edits, if those do not land as a whole, I'll separate this edit out: https://github.com/jasnell/w3c-socialwg-activitystreams/pull/220
