### ISSUE TITLE
expanding CURIEs to full URIs

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#207]
**CURIE Syntax 1.0**: http://www.w3.org/TR/curie/

In data I publish I start using CURIE heavily, eg. [in JSON-LD Playground](http://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%5B%22http%3A%2F%2Fwww.w3.org%2Fns%2Factivitystreams%22%2C%7B%22schema%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22url%22%3A%7B%22%40id%22%3A%22schema%3Aurl%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22h4p%22%3A%22https%3A%2F%2Fgraph.hackers4peace.net%2F%22%2C%22page%22%3A%22https%3A%2F%2Fplp.hackers4peace.net%2F%22%7D%5D%2C%22%40id%22%3A%22h4p%3Aef093385-8906-4c78-9a69-9217c76013a8%22%2C%22url%22%3A%22page%3Aelf-pavlik%22%2C%22displayName%22%3A%22elf%20Pavlik%22%7D&context=%7B%22%40context%22%3A%5B%22http%3A%2F%2Fwww.w3.org%2Fns%2Factivitystreams%22%2C%7B%22schema%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22url%22%3A%7B%22%40id%22%3A%22schema%3Aurl%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22h4p%22%3A%22https%3A%2F%2Fgraph.hackers4peace.net%2F%22%2C%22page%22%3A%22https%3A%2F%2Fplp.hackers4peace.net%2F%22%7D%5D%7D)

```json
{
  "@context": [
    "http://www.w3.org/ns/activitystreams",
    { 
      "schema": "http://schema.org/",
      "url": { "@id": "schema:url", "@type": "@id" },
      "h4p": "https://graph.hackers4peace.net/",
      "page": "https://plp.hackers4peace.net/"
    }
  ],
  "@id": "h4p:ef093385-8906-4c78-9a69-9217c76013a8",
  "url": "page:elf-pavlik",
  "displayName": "elf Pavlik"
}
```
I expect that AS2.0 processors will use prefixes provided in JSON-LD context and expand CURIEs to full URIs

**Comment by jasnell** [comment]
So what's the actual issue here? The current context definition already handles this.

**Comment by elf-pavlik** [comment]
http://www.w3.org/TR/activitystreams-core/#examples
> This section is non-normative.
> [...]
> Note that the Activity Streams JSON-LD @context maps the prefix "as:" to the base URI "http://www.w3.org/ns/activitystreams#". This means that terms such as "as:Activity" are equivalent to the expanded form "http://www.w3.org/ns/activitystreams#Activity". In order to best illustrate that implementors must support both forms, both the compact and expanded forms are used interchangeably by the examples in this document.

I don't find mention of [CURIE](http://www.w3.org/TR/curie/) neither requirement to use [http://www.w3.org/TR/json-ld-api/#expansion-algorithms](JSON-LD Expansion Algorithms)
1) What guarantees me that **both properties and values** (of properties defined as `"@type": "@id"` will use expanded version of URIs? 
2) How can I include above example in test suite and verify proper [CURIE -> IRI conversion](http://www.w3.org/TR/curie/#s_syntax)?
