### ISSUE TITLE
owl:Class vs. rdf:Property (for verbs and roles)

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#208]
Detailed explanation (with proper version control) on wiki page
[https://github.com/w3c-social/social-vocab/wiki/Verbs---owl:Class-vs.-rdf:Property](https://github.com/w3c-social/social-vocab/wiki/Verbs---owl:Class-vs.-rdf:Property)

at revision when creating this issue: 55f0be96c3d0ca9d82257d8d21664d9ec1e7514b

I also created [example data with various verbs and roles in both directions and straight forward counters!](https://github.com/hackers4peace/plp-test-data/blob/master/w3c-social.jsonld) with heavy use of [ldp:DirectContainer](http://www.w3.org/TR/ldp/#ldpdc) (heavily aliased in JSON-LD context). Examples show use of

### verbs
* like
* read
* visit

### roles
* member
* chair
* staff
* attendee
* speaker
* organizer

**Comment by jasnell** [comment]
-1. The design around this was discussed and settled over a year ago. There's no new information that I've seen that would justify revisiting this and I'm not interested in bikeshedding any more over the fundamental design.

**Comment by elf-pavlik** [comment]
> There's no new information that I've seen that would justify revisiting this

Can you please point me to past conversation which include [proposed usage of verbs to link agents with collections of object on which they performed certain Activity](https://github.com/w3c-social/social-vocab/wiki/Verbs---owl:Class-vs.-rdf:Property#collections)? This provides alternative to PR #191 which you have just withdrawn! + counters of activities performed on objects! #89 

It also [proposes usage usage of roles to link Objects to certain groups of Agents](https://github.com/hackers4peace/plp-test-data/blob/master/w3c-social.jsonld#L209-L229) which provides strong foundation for [setting ACL rules](https://www.w3.org/wiki/WebAccessControl)

**Comment by rpeinl** [comment]
I'd also like to see the conversation before deciding on that. To me it always made a lot of sense to use a verb instead of an activity type in AS 1.0 and the logical mapping of the actor verb object construct of AS 1.0 is subject property object in RDF.

**Comment by elf-pavlik** [comment]
Some examples of verbs defined as rdf:Property

* [foaf:knows](http://xmlns.com/foaf/spec/#term_knows)
* [sioc:follows](http://rdfs.org/sioc/spec/#term_follows)
* [cito:likes](http://www.essepuntato.it/lode/http://purl.org/spar/cito#d4e1122)

It also makes design of Activity and Relationship very similar to one other. Both have object and in Activity subject becomes actor. It makes sense to me that actor after activity has verb based relationship with the object, which defining verbs as properties allows to express!
