### ISSUE TITLE
Remove use of Language-Map properties

### ISSUE THREAD

**Issue by jasnell** [jasnell/w3c-socialwg-activitystreams#212]
The core spec currently takes some pains to support certain language tagged properties (namely title, displayName, summary and content). There was some push back on that and I was asked to document the use case (http://www.w3.org/Social/track/actions/69).

While there is a solid justification for the mechanism, and Activity Streams implementers have gone down the route of adding this capability into their applications (see x-API for example), looking it over again now, language tagged values are not critical to the basic function of the specification and add unnecessary complexity to implementations in the most common case. If implementations want to pursue language tagged values, they can do so via extension or alternative serializations. 

So I would like to propose removing Section 3.2 (http://www.w3.org/TR/activitystreams-core/#naturalLanguageValues) from the spec and removing the `titleMap`, `summaryMap`, `contentMap` and `displayNameMap` properties from the normative JSON-LD context.

**Comment by cwebber** [comment]
I'm +1 on this.

**Comment by jasnell** [comment]
Btw, I'm +0 on this personally. I'm fine with keeping the language tagged properties and feel that the use case is valid. Removing them is a significant simplification tho.. so it really comes down to what implementers want to do here.

**Comment by dissolve** [comment]
just mailed the list, but i figured i would comment here as well, 
Sandro shared a link to a doc from W3C on designing for internationalization.
http://www.w3.org/International/techniques/developing-specs-dynamic

My reading of it would suggest removing things like ContentMap and instead have an @lang property on Object.  Anything can then define an @lang for itself.  The API should then support some system of requesting data in your preferred @lang

**Comment by jasnell** [comment]
The language map mechanism tends to be a bit more developer friendly. It also allows us to easily include both the translated content and the original content... e.g. 
```json
{
  "@context": ["http://www.w3.org/ns/activitystreams#", {"@language": "en-US"}],
  "displayNameMap": {
    "en": "The Title",
    "es": "El título"
  }
}
```
When accessing the JSON directly:
```javascript
console.log(obj.displayNameMap.en)
console.log(obj.obj.displayNameMap.es)
```

When accessing via my Node.js impl:
```
console.log(obj.displayName.get('en'));
console.log(obj.displayName.get('es'));
```

**Comment by dissolve** [comment]
I see very few actual cases where a social system would need both languages at the same time.  If we did this the result for a system that has language translators to other languages is to provide EVERY language, which seems absolutely ridiculous to me.  

HTML does this the same way by providing a rel="alternate" not providing ALL languages in the same document.

**Comment by jasnell** [comment]
True, but, how often are we going to have a situation where the @context declares a global default language but an individual field declares something entirely different? 

Plus, I would contend that the following is still more developer friendly than using the `@language` within the value itself... (though they are exactly equivalent after JSON-LD expansion)

```json
{
  "@context": ["http://www.w3.org/ns/activitystreams#", {"@language": "en-US"}],
  "displayNameMap": {
    "es": "El título"
  }
}
```
```javascript
console.log(obj.displayNameMap.es);
```
vs. 
```json
{
  "@context": ["http://www.w3.org/ns/activitystreams#", {"@language": "en-US"}],
  "displayName": {
   "@language": "es"
   "@value": "El título"
  }
}
```
```
console.log(obj.displayName['@value']);
```

**Comment by jasnell** [comment]
Btw, FWIW, the original use case for this when I introduced it was not to use the language map form to include *every* possible translation, but to allow the implementation to provide both the original and localized versions of the content within a response. e.g. 

```
GET /es/thing HTTP/1.1
Host: example.com
Accept: application/activity+json
```

```
HTTP/1.1 200 OK
Content-Type: application/activity+json
Content-Length: nnnn

{
  "@context": ["http://www.w3.org/ns/activitystreams#", {"@language": "en-US"}],
  "displayNameMap": {
    "en": "The Title",
    "es": "El título"
  }
}
```

Both the original and localized content are included in the response. The implementation would not be expected to include every possible translation -- just the one actually requested.

**Comment by dissolve** [comment]
That would probably be good to make that explicit, or at least note it.  Figure 8 on the core shows and example with 3 languages for displayName.

**Comment by jasnell** [comment]
Perhaps. Either way, I think given the new established guidelines, I'm retracting this proposal.
