### ISSUE TITLE
Limit 'duration' property to ISO8601 durations only

### ISSUE THREAD

**Issue by jasnell** [jasnell/w3c-socialwg-activitystreams#213]
The `duration` property on the `Content` and `Link` classes currently allows two possible values: either an integer indicating the number of seconds or an ISO8601 duration. This adds complexity for implementers. The original integer value was used in AS 1.0 and is kept only for backwards compatibility reasons. Implementers of AS 2.0 should be using the ISO8601 format instead. I'd like to propose restricting `duration` to the ISO8601 format.

**Comment by elf-pavlik** [comment]
:+1:

**Comment by cwebber** [comment]
I have a bit of a preference for seconds over another string serialization to know how to parse, especially because iirc seconds is what gstreamer hands back to us, but I agree either way that it's best to support one and only one format.  If ISO8601 is what's chosen, at least it's easy to parse, and I'm fine with it!

**Comment by elf-pavlik** [comment]
I've found something that speaks in defense of using seconds for duration
http://www.w3.org/TR/mediaont-10/

> The actual duration of the resource. The units are defined to be seconds.
```ttl
:duration a owl:DatatypeProperty;
    rdfs:comment "Corresponds to 'duration' in the Ontology for Media Resources.";
    rdfs:domain [ a owl:Class;
            owl:intersectionOf ( :MediaResource [ a owl:Class;
                        owl:complementOf :Image ] ) ];
    rdfs:range xsd:decimal .
```

**Comment by jaywink** [comment]
> I'd like to propose restricting duration to the ISO8601 format.

@jasnell what is your rationale to using ISO8601 format instead of seconds. Definitely, only one should be "allowed", but I tend to weigh on the seconds side, like @cwebber . So interested in the "why" ISO8601.

**Comment by akuckartz** [comment]
My opinion:
- _either_ one _or_ the other (or use an additional property for the other)
- ISO8601 needs to be supported because it is the relevant international standard.

**Comment by jasnell** [comment]
The ISO8601 format (a) is an International Standard, (b) is far more concise and readable, and (c) takes leap years/seconds into consideration. Take the following examples for instance:

* 1 year: `"duration":"P1Y"` vs `"duration": 31536000`
* 1 year, 2 months, 3 days: `"duration":"P1Y2M3D"` vs `"duration": 37075613` (note that the integer form is defined using non-fractional seconds, the actual equivalent duration in seconds would be 37,075,613.6 seconds
* 2 hours, 15 minutes: `"duration":"PT2H15M"` vs `"duration": 8100` 

We also already normatively require adherence to ISO 8601 in the date-time fields

**Comment by jaywink** [comment]
Thanks, sounds good to me then :+1:

**Comment by wilkie** [comment]
+1 Atom feeds and such will require ISO8601 and other fields certainly gain something from the standardization. Fairly good language support if needed, and less ambiguity (the whole point of standardizing a date format and using that standard).

**Comment by jasnell** [comment]
WG approved this change
