### ISSUE TITLE
[Proposal] Remove Question object

### ISSUE THREAD

**Issue by jasnell** [jasnell/w3c-socialwg-activitystreams#216]
The Question object can likely be better handled via an extension.

**Comment by cwebber** [comment]
Probably true.  As we discussed on IRC, StatusNet / GNU Social [had a polling extension](https://github.com/foocorp/gnu-social/blob/0bd0c65b876656ff86e7aadd4aae354842f3a92c/plugins/Poll/PollPlugin.php) that people liked to use when I was using it.  However, I don't think it's critical.

Also, one side effect of when that plugin became introduced was my inbox would flood with poll responses, so remembering minor irritation surrounding that, maybe it's a-ok to remove.

**Comment by cwebber** [comment]
What timing!  [Twitter is now going to add poll support](https://twitter.com/twitter/status/656832713781936128) right as we're considering removing it. :)

**Comment by dissolve** [comment]
I'm still for removing it, The only user story supporting it has a few -1s and several 0's 

@cwebber just because one silo supports something, doesn't mean its something we need to support other than as an extension.

**Comment by jasnell** [comment]
I've received feedback that there are implementers interested in using Question. Given that, I'm going to withdraw this proposal.

**Comment by tantek** [comment]
Which implementations? Can we cite/document this publicly? Ideally have they blogged about it?

Also, "implementers interested in using Question" is a good justification for an extension rather than keeping it in the spec.

Better to drop it and make those implementers speak up publicly on IRC / email / here in the issue.

**Comment by jasnell** [comment]
Feel free to open your own issue proposing that it be dropped. I'll make sure that all open proposal issues are suggested for the next call agenda. As for implementers, here's one in particular: https://lists.w3.org/Archives/Public/public-socialweb/2015Oct/0191.html

Based on discussions with members of the WG who have voiced intent to implement AS2 and Question, I'm -1 on dropping it.
