### ISSUE TITLE
[Proposal] Remove Priority

### ISSUE THREAD

**Issue by dissolve** [jasnell/w3c-socialwg-activitystreams#218]
I can't see any user story that really has a requirement on priority.  
I would expect a consumer to set priority based on its own heuristic (prioritized friends, etc)
Perhaps someone can enlighten me.

**Comment by jasnell** [comment]
This is one that I've flagged also for possible removal. I've seen it put to good use but it definitely is not critical to core

**Comment by wilkie** [comment]
+1

**Comment by jasnell** [comment]
WG approved this change
