### ISSUE TITLE
Introduce property src and explicit type for binary data e.g Blob

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#223]
Currently AS has IMO confusing way of describing binary resources (image, audio, video etc.)

* [as:image](http://www.w3.org/TR/activitystreams-vocabulary/#dfn-image-term) recommends [as:Image](http://www.w3.org/TR/activitystreams-vocabulary/#dfn-image) or [as:Link](http://www.w3.org/TR/activitystreams-vocabulary/#dfn-link) as its value.
* *as:Image* uses [as:url](http://www.w3.org/TR/activitystreams-vocabulary/#dfn-url) which in turn recommends xsd:anyURI or *as:Link* as it's value.

This way to find binary source of someone's avatar one needs to stay prepare for traversing

as:Person - as:image -> as:Image - as:url -> as:Link - as:href -> ???

With simplest case

as:Person - as:image -> as:Link - as:href -> ???

Given instance of as:Link

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "Link",
  "href": "http://example.org/album/my_fluffy_cat.png",
  "mediaType": "image/png"
}
```

Currently we don't have a type which we could use of object with `@id` same as value of `href` above

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@id": "http://example.org/album/my_fluffy_cat.png",
  "@type": "???",
  "mediaType": "image/png"
}
```

While as:Object acts as top level class for structured resources as:Blob could act as similar for binary resources. It could go in similar direction as [LDP Non-RDF Source](http://www.w3.org/TR/ldp/#ldpnr). In example above we could use `"@type": "ImageBlob"`

In HTML `<img> <audio> <video>` tags, all have **src** attribute

If we add *as:src* with recommendation to use instances of Blob (and it's subclasses) as its value. And recommend ImageBlob as possible value of *as:image*, we would have:

as:Person - as:image -> as:ImageBlob
instead of
as:Person - as:image -> as:Link - as:href -> ???

and 

as:Person - as:image -> as:Image - as:src -> ImageBlob
instead of
as:Person - as:image -> as:Image - as:url -> as:Link - as:href -> ???

I believe many people can find it more intuitive than always having to deal with
as:Link - as:href -> ???

*as:Link* has this exceptional magic future where subject of *mediaType* becomes denoted by the value of *href* and not the link entity (blank node) itself. This proposal would allow using *mediaType* in the same way as other properties.

![as:Object vs. as:Link diagram](https://docs.google.com/drawings/d/1dKbBNuD4rfDa6MBr32vY6VI4_IuRx5u2rAf_RsxWoF0/pub?w=964&h=1006)

I also find it similar to [schema:contentUrl](http://schema.org/contentUrl)

We could also explain now subtypes of as:Blob relate to media types
* as:ImageBlob - common mediaType: image/png, image/jpeg, image/gif [IANA image/*](http://www.iana.org/assignments/media-types/media-types.xhtml#image)
* as:AudioBlob - common mediaType: audio/ogg, audio/mp3 [IANA audio/*](http://www.iana.org/assignments/media-types/media-types.xhtml#audio)
* as:VideoBlob - common mediaType: video/mp4, video/webm, video/ogg [IANA video/*](http://www.iana.org/assignments/media-types/media-types.xhtml#video)

**Comment by jasnell** [comment]
-1, adding an `as:src` property is not needed. We already have `Image`, `Video` and others as object types, those already have `url` properties that can be used to point to the actual data. If you want to encapsulate the binary data within the object, you can easily use base64 encoded content or data urls. The *most* I think we'd want to do is allow `mediaType` on `Content` objects as well as `Link`.

**Comment by elf-pavlik** [comment]
> The most I think we'd want to do is allow mediaType on Content objects as well as Link

I thought that all instances of *as:Object* and its sub classes have implicit
`"mediaType": "application/activity+json"`

And as:Link pretty much serves purpose or handling other media types than this one. If we compare *as:Object* to *ldp:RDFSource*, suggested *as:Blob* would make equivalent of *ldp:NonRDFSource*.

This way we have consistent EAV/SPO
* `"@id":` sets subject (which entity we describe)
* `"someProperty":` predicate (which attribute of that entity)
* ` : "some value"` object (value of that attribute)

Currently *as:Link* seems to have identity crisis (also see illustration in issue description):
* properties which use link entity itself as subject: *as:href*, *as:rel*, *as:displayName*, *as:title*
* properties which use entity denoted by value of *href* property as subject: *as:mediaType* *as:hreflang*, *as:height*, *as:width*,  *as:duration*

If no introducing *as:Blob* ~= *ldp:NonRDFSource*. (or whatever we want to name resources with other media types than *application/activity+json* ~= *ldp:RDFSource*)., than maybe renaming properties which use value of href property as subject to follow *as:hreflang* approach - *as:hrefmediatype*, *as:hrefheight*, *as:hrefwidth*,  *as:hrefduration*

**Comment by jasnell** [comment]
> I thought that all instances of as:Object and its sub classes have implicit
"mediaType": "application/activity+json"

Nope.

**Comment by elf-pavlik** [comment]
I just came across http://www.w3.org/TR/mediaont-10/ @cwebber 

@jasnell If I use as:Link, can I write following

```json
{
  "@context": [
    "http://www.w3.org/ns/activitystreams",
    { "ma": "http://www.w3.org/ns/ma-ont#" }
  ],
  "@type": "Link",
  "href": {
    "@id": "http://example.org/videos/b-day.ogg",
    "@type": "ma:VideoTrack",
    "ma:duration": 763
  },
  "mediaType": "video/ogg"
}
```
?

**Comment by azaroth42** [comment]
Propose that this is solved by dropping Content type and clarification of Link semantics.
