### ISSUE TITLE
[Proposal] Remove 'alias'

### ISSUE THREAD

**Issue by jasnell** [jasnell/w3c-socialwg-activitystreams#225]
The 'alias' property is useful but likely not critical to have in the core vocabulary. It can easily be provided via extension

**Comment by elf-pavlik** [comment]
:+1: #25

**Comment by wilkie** [comment]
+1 yeah, alias isn't necessary. I'm not really understanding why people want multiple identifiers, but you certainly don't need them when you have a global ID (which you can resolve and pull out a displayName for human readable name) for core implementation.

**Comment by jasnell** [comment]
WG approved this change
