### ISSUE TITLE
[Proposal] Remove 'Process' actor type

### ISSUE THREAD

**Issue by jasnell** [jasnell/w3c-socialwg-activitystreams#227]
The `Process` and `Service` actor types are each used to identify activities carried out by automated software or processes. Their definitions are somewhat ambiguous and largely determined by context. To help simplify the vocabulary, we can drop `Process` and just use `Service` 

(Note: this had originally proposed removing `Service` in favor of `Process` but was reversed due to the feedback in the comments below)

**Comment by silverbucket** [comment]
Why drop `Service` and use `Process`? `Service` seems much more clear to me, and is what I've been using for a year or so.

**Comment by jaywink** [comment]
:+1: for `Service` instead of `Process`

**Comment by jasnell** [comment]
Ok, either way, we just need one :-)

**Comment by jasnell** [comment]
WG approved this change
