### ISSUE TITLE
[Proposal] Remove 'Mention' object type

### ISSUE THREAD

**Issue by jasnell** [jasnell/w3c-socialwg-activitystreams#228]
While the `Mention` object type is likely quite useful, it's not critical and can easily be done via extension.

**Comment by jaywink** [comment]
Have to give a big -1 to this. Mentions are a very big concept in the more traditional social network space, not only important in places like Facebook, but the ones who are interested in implementing AS2, like diaspora* and Friendica. Both support mentions but with different syntax.

Being able to, like [indicated here](http://www.w3.org/TR/activitystreams-core/#microsyntaxes) in the example, to collect mentions as Mention objects specific to for example a Note, seems ideal to me. I'd very much like it to be considered a core concept that doesn't need be brought in as an extension.

**Comment by jasnell** [comment]
@jaywink ... Ok. Thank you for weighing in on it. If the mechanism as currently defined is useful to implementers then let's keep it in there, by all means. 

FWIW, removing `Mention` wouldn't eliminate the ability to use mentions with AS2, it would just mean changing the way we do it. But I'm perfectly fine with leaving it in

**Comment by jasnell** [comment]
Given that feedback, I'll withdraw this proposal
