### ISSUE TITLE
[Proposal] Support for free definable annotations

### ISSUE THREAD

**Issue by annando** [jasnell/w3c-socialwg-activitystreams#231]
Please have a look at the app.net reference for annotations: https://developers.app.net/reference/meta/annotations/

Annotations in app.net are described as: "immutable attributes that describe the entire post"

They are mostly used for everything that isn't standardized. If - for example - a system would like to add the current mood of a user to a post then it could be done in that way:

````
{
  "type": "tld.your.network",
  "value": {
    "mood": "happy"
  }
}
````

It is important that these annotations only contain *additional* stuff and that they aren't mandatory for the activity. They could also be used to transport stuff that is only important for the communication between the same network. 

It could be used for this issue as well: https://github.com/jasnell/w3c-socialwg-activitystreams/issues/229

Here the non-standard content (Markdown, BBCode, ...) could be wrapped in such an annotation.

Important: These annotations musn't be removed nor modified even if the post was relayed by a system that doesn't interpret them.

**Comment by jasnell** [comment]
These kinds of things can already be defined within an AS2 document, whether declared in the JSON-LD `@context` or not... for instance:

```
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "Person",
  "displayName": "James",
  "mood": "grumpy"
}
```
For implementations that use JSON-LD processing, the undefined `mood` property is mapped to the "blank node" `_:mood` which is preserved in the data and would be reserialized but isn't ideal for RDF level processing. 

Ideally, for full interoperability, you'd want something like:

```
{
  "@context": [
    "http://www.w3.org/ns/activitystreams", 
    {"mood": "http://tld.your.network/mood"}],
  "@type": "Person",
  "displayName": "James",
  "mood": "grumpy"
}
```

So that it works for regular JSON, JSON-LD and RDF style implementations.

**Comment by gobengo** [comment]
Yeah the extension story is covered by JSON-LD contexts

-1

**Comment by jasnell** [comment]
Closing this due to the fact that extensions are already handled by the spec

**Comment by rhiaro** [comment]
Hey @annando, does this answer your question? As AS2 is approaching CR, we just want to check that all the closed issues were handled okay. If you don't reply by 1300 EST Tuesday 28 June (the next WG meeting) we're going to assume you're satisfied and it will remain closed.

**Comment by annando** [comment]
You can keep the issue closed. Sorry for not answering in time.
