### ISSUE TITLE
[Proposal] Remove @context from all examples

### ISSUE THREAD

**Issue by dissolve** [jasnell/w3c-socialwg-activitystreams#233]
https://lists.w3.org/Archives/Public/public-socialweb/2015Oct/0170.html
http://www.w3.org/TR/annotation-model/ does this quite successfully only bringing up @context in specific JSON-LD considerations section.

**Comment by jasnell** [comment]
hmm... just thinking through any interoperability concerns with this one... I think this is fine. Implementations that do JSON-LD processing really ought to be injecting the default normative `@context` if it doesn't exist so I think we should be good. This needs to be made more explicit in the core spec tho.

**Comment by jasnell** [comment]
Marking this one as editorial.

**Comment by BigBlueHat** [comment]
So the Annotation WG is discussing going the other way. It's helpful if you find the JSON later to understand what the contents are. Without the context it could be anything, so having a direct URL to the description info is very helpful 

Related, we plan to include documentation in our context file.

**Comment by dissolve** [comment]
@bigbluehat.  Digressing a little.  I'm guessing documentation as lines starting with // 
I've found that breaks json-ld.org/playground's parser.

**Comment by elf-pavlik** [comment]
*application/ld+json* requires explicit `@context`, removing it from examples pretty much ends conversation in #52 

http://www.w3.org/TR/json-ld/#interpreting-json-as-json-ld
> Please note that JSON-LD documents served with the application/ld+json media type must have all context information, including references to external contexts, within the body of the document. Contexts linked via a http://www.w3.org/ns/json-ld#context HTTP Link Header must be ignored for such documents.

**Comment by akuckartz** [comment]
:-1:

**Comment by jasnell** [comment]
Given that, I doubt this one is going to find consensus supporting it and having the @context is useful. I don't think the @context should be required tho.

**Comment by jasnell** [comment]
Given that this is an editorial proposal and given the thumbs down, I'm closing. If anyone feels that it needs to be opened, the issue can be brought up on the call.

**Comment by melvincarvalho** [comment]
See also the text from web annotations:

> The RECOMMENDED serialization format is [JSON-LD]. The JSON-LD context presented below is RECOMMENDED to ensure consistency between implementations, and SHOULD be referenced as http://www.w3.org/ns/anno.jsonld. It has a profile URI that SHOULD be used: http://www.w3.org/TR/annotation-model/jsonLdProfile.

http://www.w3.org/TR/annotation-model/#json-ld-considerations

You'd need to add something like that too.  

IMHO, this isnt quite a pure editorial change as I think it breaks JSON LD inteorp without extra out of band knowledge.

At this point in time it's hard to establish whether AS2 gives us anything JSON LD doesnt, in terms of adoption / features / simplicity, and whether it will interop with generic tooling.  Id like to see that case being made.  IMHO, even if closed now, it may reasonably come up going to PR and REC again.

**Comment by melvincarvalho** [comment]
Sorry, I think I argued the opposite case!  I see this proposal was closed, and the consensus was to *keep* @context ... that makes sense, and provides important interop imho

+1 closing

**Comment by jasnell** [comment]
WG rejected this change

**Comment by BigBlueHat** [comment]
@dissolve sorry for the late reply. JSON-LD will ignore "extra" keys and values found in the `@context` document, so we can include JSON Schema (or whatever) style descriptions as JSON in the context file.

The details are still pending, but that's what @azaroth42 and I've discussed so far.
