### ISSUE TITLE
Vocabulary type for "accounts"

### ISSUE THREAD

**Issue by kleiinnn** [jasnell/w3c-socialwg-activitystreams#235]
Shouldn't there be a object type with attributes usually stored for user accounts?
I think of fields like email address, password, ...

**Comment by akuckartz** [comment]
At least this could be dealt with in an FAQ or Best Practice document.

**Comment by jasnell** [comment]
I'd considered this but the way many systems handle accounts tend to be very different and we need to be careful about not promoting bad practice (such as putting password into an AS object ;-) ...). What I would suspect is that implementers who are looking to solve that particular problem with either adopt an existing vocabulary or create an extension for this specific purpose.

**Comment by jaywink** [comment]
Why would AS2 need to map accounts? These are normally local data. Wondering what is the use case behind this proposal?

**Comment by kleiinnn** [comment]
I don't unterstand why accounts are local data. They are like every other type of data stores for a web service. 

One use case would be an API for a web service. Then you would want your API consumers to be able to create new accounts.

**Comment by jaywink** [comment]
> They are like every other type of data stores for a web service.
> 
> One use case would be an API for a web service. Then you would want your API consumers to be able to create new accounts.

Sure, but are we not talking of social data here, not mapping everything needed for a web service under a vocabulary? I think the key word here is "activity". A user account is an object, for sure, but it is not social activity.

**Comment by kleiinnn** [comment]
I agree with you that we don't need to map everything for a web service under a vocabulary but I think a user account (which is actually an Person object with some extra attributes) is a very important component of an activity just like the activity's content.

**Comment by rpeinl** [comment]
I agree with @jaywink and @jasnell that it would be bad practice to store account details inside the subject or object of an activity. Therefore, we should not include that. Please keep in mind, @kleiinnn, that  the activity is usually only communicating meta data about things that happened, e.g., user XYZ created an account in system ABC. However, it should not communicate sensitive data like passwords.

**Comment by gobengo** [comment]
When I tried to map my problem domain to AS2 in June, it had Identity, which appears to now be gone? https://livefyre.github.io/activity-vocabulary/#livefyre:Identity

The closest thing remaining is Person.... which is different. It is good to have something like Identity or Account for all the same reasons that this exists: https://en.wikipedia.org/wiki/Facebook_real-name_policy_controversy

As a Product Manager, I've had this real-world thing come up. Customer runs websites for sports communities. A given Person is a fan of both Ohio State and Michigan (rivals). They are one Person with different Identities on each site. They will be trolled to oblivion if other Identities can find out that it is the same Person.

In liu of some class like Identity, Account, I would just map my domain's subclass to Actor (and it looks like I wouldn't really be missing out on any properties that only exist on Person)

**Comment by jasnell** [comment]
I'm looking at creating a supplemental vocabulary that includes some of the
terms removed from core... Including Identity

**Comment by gobengo** [comment]
@jasnell Good to know. I remember asking you about this in June in IRC too. When in doubt foaf is good too, and IIRC the non-normative OWL used to state that equivalency to as:Identity.

**Comment by azaroth42** [comment]
:+1: to drop
