### ISSUE TITLE
[Proposal] Drop `context` from AS Vocabulary to avoid confusion with `@context`

### ISSUE THREAD

**Issue by BigBlueHat** [jasnell/w3c-socialwg-activitystreams#238]
See [this comment](https://github.com/jasnell/w3c-socialwg-activitystreams/issues/232#issuecomment-153398566) for context (heh).

Given that it's vague and the key has conflicting meanings in the document, it seems prudent to remove it and replace it's usage with Tags--which seem to serve the purpose of grouping/relating activities.

**Comment by jasnell** [comment]
-1. `context` has proven quite useful in implementation and is used in very closely related specs (see https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#context).

**Comment by BigBlueHat** [comment]
@jasnell ah. Didn't realize it was already in use "in the wild."

FWIW, we've discussed the introduction of an `audience` object for Annotation which would work similarly--though not as broadly.

I do wish there was another name for it...but I'll close my own proposal as I'd rather see AS1 content (and things based on it like xAPI) have a smoother path to upgrading.

Thanks for the link!

**Comment by jasnell** [comment]
In the AS2 vocabulary, there is a `scope` property that is used generally
to identify the audience. The targeting properties `to`, `bto`, `cc` and
`bcc` indicate the audience subsets within that identified scope. The
`context` is really intended to allow objects and activities to be
logically grouped. For instance, in an enterprise setting, the context may
group activities by project while the scope would identify one or more
teams for which the activity is considered relevant, while the to/cc fields
are used to indicate specific individuals to notify.

**Comment by BigBlueHat** [comment]
@jasnell makes sense, and thanks for the background/info! I'll dig deeper before posting more proposals. :smile_cat:

**Comment by jasnell** [comment]
no worries :+1:
