### ISSUE TITLE
Remove object type Story

### ISSUE THREAD

**Issue by rpeinl** [jasnell/w3c-socialwg-activitystreams#239]
As we are about to make the spec less complex and found good reasons not to create a new object type for Blog (#157), because it would mean that we would also need all kinds of other specialized collections like Wiki, Forum, ... I see no reason why we should have Story as a specialized Collection. It doesn't provide additional semantic meaning from my point of view and I don't see a use case for such a construct (in contrast to Blog or Wiki).

**Comment by jasnell** [comment]
I'm -1 on removing this one. There are many examples of ordered collections. You can look at things like Google Photo Stories (https://support.google.com/photos/answer/6135210?hl=en) and Facebook photo stories (https://support.google.com/photos/answer/6135210?hl=en) and see a very clear use case.

**Comment by rpeinl** [comment]
acknowledged @jasnell, but you did also see the Blog use case, didn't you? Still you voted against it. I think we should make some general rules on how to decide on certain things like specializations of collections. If we say we want Album and Story included, then I find it hard to argue why Blog and Wiki and Forum should be not. The other way around, if we don't want' to include Blog and Wiki and Forum then what's the reason to keep Story and Album? 
Another aspect: you are frequently arguing that certain things should not be included because "they can be easily implemented as an extension". This argument can be applied here as well, especially when the specializations do not have any specific properties like Story. Again, we should think of a general rule, when we say: "make your own extension" and when not. From my perspective it's all about interoperability. If one implementation can make sense out of the object by falling back to the standardized super type instead of using the specialized sub type then I would argue that the sub type is superfluous in the standard.

**Comment by jasnell** [comment]
At this point in the process I'm generally biased against *additive* changes that would introduce new object types that can be covered by the existing types. Part of the challenge with `Blog` is that, realistically, any collection of articles/notes/photos/videos can be considered a blog these days. The term has become quite generalized -- to the point that there's no clear advantage to have a distinct `Blog` type (at least in my opinion). For `Story`, on the other hand, there is a distinct use case that implies a narrative intent. Not all ordered collections can be considered a `Story` so the term is not as generalized as `Blog`.

I would be open to considering `Forum` and `Wiki` as object types actually. However, I'm hesitant to add new object types to the vocabulary and have held off and proposing anything specific around these to see what was going to happen with the Social API. At this point, I'm not overly optimistic that the API work will produce anything usable any time soon so it may be worthwhile going ahead and considering adding these additional terms. Aside from `Blog`, `Wiki` and `Forum`, what others do you feel should be considered?

**Comment by dissolve** [comment]
"There are many examples of ordered collections."  yes, thats why there is Ordered Collection type,  I would think this would be an obvious :+1: since it is exactly the same argument as Blog.   You can put a summary (description) on a collection correct?  I feel like that would cover most use cases and extensions can cover the rest.  It is at this point the only class that inherits from Ordered Collection (other than for Paging) and it does not introduce anything new.

I wonder if a "collectionType" property might make more sense since there are so many possible options that really don't effect at all the processing of the object.  Album and Folder certainly have the same issue.

**Comment by jasnell** [comment]
Not convinced that a `collectionType` property buys us anything as all it does is shift the issue from one field to another. Thinking it over, I would be open to dropping `Album`, `Folder` and `Story` from the core vocabulary but they're so common that I think the first thing an implementer is going to do is add them right back in as extensions... Perhaps in this case, adding `Blog`, `Wiki` and `Forum` would just be the better option.

**Comment by jasnell** [comment]
Discussing it on IRC, another possibility is that we move `Folder`, `Album`, `Story`, `Blog`, `Wiki` and `Forum` to an extension vocabulary and remove `Folder`, `Album` and `Story` from the core. That would provide the most flexibility as we go. I'll be drafting up a proposal.

**Comment by rpeinl** [comment]
+1 to that suggestion

**Comment by akuckartz** [comment]
:+1: to that last suggestion by @jasnell

**Comment by jasnell** [comment]
Here's a start... 
* http://ns.jasnell.me/socialwg/
* http://ns.jasnell.me/socialwg/socialobject.jsonld
* http://ns.jasnell.me/socialwg/socialobject.owl (really a turtle file, not owl)

**Comment by jasnell** [comment]
WG decision on the call yesterday was to pursue this. Will remove `Story`, `Folder` and `Album` in the next update.
