### ISSUE TITLE
as:Link from Linked Data perspective + comparing with hydra:Link

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#24]
This issue comes from observation I made on mailing list
http://lists.w3.org/Archives/Public/public-socialweb/2014Sep/0143.html

I see it also relevant to hydra:Link and hope that @lanthaler could support us in clarifying it
http://www.hydra-cg.com/spec/latest/core/#adding-affordances-to-representations

Looking at examples from @jasnell original email
http://lists.w3.org/Archives/Public/public-socialweb/2014Sep/0139.html

```js
  "actor": {
    "@type": "urn:example:objectType:person",
    "displayName": "Sally"
  }
```
```js
  "actor": {
    "@type": "http://activitystrea.ms/2.0/Link",
    "@id": "http://example.org/profiles/sally",
    "mediaType": "text.html"
  }
```

As I understand it

* first states that *actor* has *@type* *urn:example:objectType:person*
* second states that *actor* has *@type* *as:Link*

Next example which 'mixes' first two

```js
  "actor": [
    {
      "@type": "urn:example:objectType:person",
      "displayName": "Sally"
    },
    {
      "@type": "http://activitystrea.ms/2.0/Link",
      "@id": "http://example.org/profiles/sally",
      "mediaType": "text.html"
    }
  ]
```

I could interpret it as: **two** *actors*, first one ([blank node](http://www.w3.org/TR/rdf11-concepts/#section-blank-nodes)!) has type *urn:example:objectType:person* second one (node identified by IRI) has type *as:Link*

I get quite confused if I try to 'mix' it differently, similar as in one of my emails on that thread:
http://lists.w3.org/Archives/Public/public-socialweb/2014Sep/0141.html

```js
 "actor": {
   "@type": ["urn:example:objectType:person", "http://activitystrea.ms/2.0/Link"]
   "displayName": "Sally",
   "@id": "http://example.org/profiles/sally",
   "mediaType": "text.html"
}
```

which for me states that *person name Sally has mediaType "text.html"*

I must admit that I feel confused about such 'mixing' of types like *schema:Person* and *as:Link*.

While *hydra:Link* gets defined as:

```js
{
  "@id": "hydra:Link",
  "@type": "hydra:Class",
  "comment": "The class of properties representing links.",
  "label": "Link",
  "subClassOf": [
    "hydra:Resource",
    "rdf:Property"
  ],
  "status": "testing"
}
```
*as:Link* has definition:

```js
{
  "@id": "as:Link",
  "@type": "owl:Class",
  "rdfs:subClassOf": "owl:Thing"
}
```

I have impression that defining *hydra:Link* as subClassOf *rdf:Property* and using it this way might make some significant difference...
Possibly also relevant to [my email about using object keys in JSON-LD](http://lists.w3.org/Archives/Public/public-socialweb/2014Oct/0008.html)

**Comment by elf-pavlik** [comment]
Relevant conversation on Hydra CG list proposing removal of hydra:Resource (similar in definition to as:Link) and hydra:Class http://lists.w3.org/Archives/Public/public-hydra/2015Jan/0022.html
One can find there various comments about how to assume (or not) that we can dereference something. @gkellogg mentioned that in scenarios he works with hydra:Link ( defined differently then in AS, as rdfs:subClassOf rdf:Property) http://www.hydra-cg.com/spec/latest/core/#hydra:Link

**Comment by elf-pavlik** [comment]
discussion continues in Hydra CG https://github.com/HydraCG/Specifications/issues/91 which also links to accompanying thread on mailing list

**Comment by elf-pavlik** [comment]
I created issue in Social WG tracker for as:Link
https://www.w3.org/Social/track/issues/14

**Comment by jasnell** [comment]
WG decision to keep as:Link as defined.
