### ISSUE TITLE
Bring back activity type assign from AS1.0 

### ISSUE THREAD

**Issue by rpeinl** [jasnell/w3c-socialwg-activitystreams#240]
My use case is social business process management (BPM) but the vocabulary used would be also applicable for issue trackers. We have a BPM system that is generating activities for typical actions within such a system. 
Examples for such activities include
* User 1 assigns task A to user 2
* User 2 changed the status of task A from new to "in progress"
* User 2 updated the progress of task A to 70%
* User 2 completed task A 
While I can imagine using the Update activity type for the examples 2-4, I don't see a proper activity type for the first example. One could argue that Offer is similar, but from my point of view there is enough semantic difference to justify an Assign activity type.

**Comment by jasnell** [comment]
-0 on this one. I definitely see the use case but it's something that can be easily accomplished in an extension vocabulary built on top of the core.

**Comment by wilkie** [comment]
I believe it should be in an extension, for sure. Anything you wouldn't really expect in a majority of social sites should be in an extension.
