### ISSUE TITLE
Use `url` instead of `href`

### ISSUE THREAD

**Issue by aaronpk** [jasnell/w3c-socialwg-activitystreams#245]
It seems that the property `url` is used for Objects, whereas [`href` is used for Links](http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams-core/index.html#link). ActivityStreams 1 also used to call this `url`. From the AS1 spec:

```
          "image": {
            "url": "http://example.org/album/my_fluffy_cat_thumb.jpg",
            "width": 250,
            "height": 250
          }
```

For consistency's sake, can this be changed to `url` everywhere?

**Comment by jasnell** [comment]
There are two key reasons for having separate `url` and `href`: (a) `href` is always expected to be *just* a URL string and (b) `href` is what is used most commonly in other places (e.g. http links, atom links, rfc5988, etc). 

Using `url` in both cases would make the value of `url` ambiguous. In objects, `url` allows for multiple values (URL string, as:Link or array of either). 

The AS1 approach you give works perfectly well in AS2, and is likely to be the most common use:

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Image",
  "url": "http://example.org/album/my_fluffy_cat_thumb.jpg"
}
```

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Image",
  "url": [
    {
      "@type": "Link",
      "mediaType": "image/jpeg",
      "href": "http://example.org/album/my_fluffy_cat_thumb.jpg"
    },
    {
      "@type": "Link", 
      "mediaType": "image/png",
      "href": "http://example.org/album/my_fluffy_cat_thumb.png"
    }
  ]
}
```

**Comment by aaronpk** [comment]
Interesting, I think I see where this is coming from.

I don't think the AS2 example you gave is equivalent. More accurately it would be:

```
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Image",
  "url": {
    "type": "Link",
    "href": "http://example.org/album/my_fluffy_cat_thumb.jpg",
    "mediaType": "image/jpeg",
    "width": 250,
    "height": 250
  }
}
```

**Comment by jasnell** [comment]
Nope, the example I gave was correct, I just omitted the `width` and `height`:

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Image",
  "width": 250,
  "height": 250,
  "url": "http://example.org/album/my_fluffy_cat_thumb.jpg"
}
```

Another example, this time showing an image associated with another object:
```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Person",
  "displayName": "John Doe",
  "image": {
    "type": "Image",
    "url": "http://example.org/album/my_fluffy_cat_thumb.jpg",
    "width": 250,
    "height": 250
  }
}
```

The only time you'd need to use the `Link` in this is if you needed to specify additional properties about the linked resource (such as it's media type), or wanted to offer multiple representations:

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Person",
  "displayName": "John Doe",
  "image": {
    "type": "Image",
    "displayName": "Picture of my fluffy cat",
    "url": [
      {
        "type": "Link",
        "width": 250,
        "height": 250,
        "mediaType": "image/jpeg",
        "href": "http://example.org/album/my_fluffy_cat_thumb.jpg"
      },
      {
        "type": "Link",
        "width": 500,
        "height": 500,
        "mediaType": "image/png",
        "href": "http://example.org/album/my_fluffy_cat_full.png"
      }
    ]
  }
}
```

**Comment by jasnell** [comment]
Note that depending on your requirements, you could also skip use of the `Image` object entirely and make the value of the `image` property a `Link`:

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Person",
  "displayName": "John Doe",
  "image": {
    "type": "Link",
    "mediaType": "image/jpeg",
    "href": "http://example.org/album/my_fluffy_cat_thumb.jpg",
    "width": 250,
    "height": 250
  }
}
```
The choice would hinge on whether or not you need the additional Object properties or not... which, in this case, you likely would not.

**Comment by gobengo** [comment]
What is the difference between

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Person",
  "displayName": "John Doe",
  "image": {
    "type": "Link",
    "mediaType": "image/jpeg",
    "href": "http://example.org/album/my_fluffy_cat_thumb.jpg",
    "width": 250,
    "height": 250
  }
}
```

and

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Person",
  "displayName": "John Doe",
  "image": {
    "@id": "http://example.org/album/my_fluffy_cat_thumb.jpg",
    "mediaType": "image/jpeg",
    "width": 250,
    "height": 250
  }
}
```

?

**Comment by aaronpk** [comment]
My understanding is that `@id` (or now `id`) is not guaranteed to be a URL, which is the purpose of this attribute.

**Comment by akuckartz** [comment]
I do not see the need for either `href` or `url` in addition to `@id`. Was that already discussed in another issue or elsewhere?

**Comment by gobengo** [comment]
@aaronpk ah good point.

Is this insufficient?
```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Person",
  "displayName": "John Doe",
  "image": {
    "id": ["urn:provider.com:blah", "http://example.org/album/my_fluffy_cat_thumb.jpg"],
    "mediaType": "image/jpeg",
    "width": 250,
    "height": 250
  }
}
```

**Comment by gobengo** [comment]
@aaronpk good point.

I think `href` is appropriate for links.

[`url`](http://www.w3.org/TR/activitystreams-vocabulary/#dfn-url) is currently
> Identifies one or more links to representations of the object

`url` would be the representation of the Link (as would id be the id of the link).

... but I still think in the case where you don't need an ["indirect, qualified reference"](http://www.w3.org/TR/activitystreams-vocabulary/#dfn-link), many implementations are likely to just do

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Person",
  "displayName": "John Doe",
  "image": {
    "id": "http://example.org/album/my_fluffy_cat_thumb.jpg",
    "width": 250,
    "height": 250
  }
}
```

**Comment by jasnell** [comment]
Resolved to keep both `url` and `href`
