### ISSUE TITLE
mediaType of title/summary/content is ambiguous

### ISSUE THREAD

**Issue by aaronpk** [jasnell/w3c-socialwg-activitystreams#246]
The definition of properties such as content allow for HTML markup to be included. However, the spec does not require that the media type be specified. This leads to inconsistent results when the consumer doesn't know what to expect. 

For example, if the "content" property *can* contain HTML, a consumer will be either stripping the HTML, sanitizing it, or displaying it directly. However, if a user enters something like "I had a great time at the View Source conference &lt;o&gt;", (&lt;o&gt; being an ascii representation of the conference logo), the consumer would need to HTML escape that before rendering it otherwise it would disappear from display. However there is no way to know whether the value is meant to be the literal text or interpreted as HTML.

Additionally, the current spec does not allow for different media types for summary and content, since the mediaType property lives next to those properties. The following example demonstrates the problem:

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Note",
  "mediaType": "text/html",
  "summary": "Hello <o>!",
  "content": "<b>Hello &lt;o&gt;!</b>"
}
```

My suggestion is to require that string values can *only* be plaintext, and if you want to have HTML for a value, then you enclose it in an object where you can specify mediaType. This would look something like the following, I'm open to suggestions on names:

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Note",
  "summary": "Plaintext summary, always HTML escaped <o> before displaying",
  "content": {
    "type": "Object",
    "mediaType": "text/html",
    "value": "<p>HTML content goes <b>here</b></p>"
  }
}
```

**Comment by jasnell** [comment]
This was addressed in the edits that were approved yesterday. The `mediaType` property is now permitted on objects to define the media type of the `content` property.

The existing breakdown is this:

* `displayName` -- always plaintext
* `title` -- equivalent to displayName but permits HTML markup
* `summary` -- permits HTML markup
* `content` -- defaults to `text/html`, `mediaType` can be used to specify other media types for the `content` property

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Note",
  "summary": "Summary, with &lt;o> markup",
  "mediaType": "text/html",
  "content": "<p>HTML content goes <b>here</b></p>"
}
```

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Note",
  "summary": "Summary without markup",
  "mediaType": "text/html",
  "content": "<p>HTML content goes <b>here</b></p>"
}
```

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Note",
  "summary": "Summary without markup",
  "mediaType": "text/plain",
  "content": "Plain text content"
}
```

**Comment by aaronpk** [comment]
I don't see how this addresses the issue of two values being different content types. Are you saying that if the object has a mediaType of text/html, then all values must be HTML? (Summary and content must be the same type)?

**Comment by jasnell** [comment]
`summary` is *always* text/html, regardless of anything else.
`mediaType` on the object *only* impacts the `content` field

**Comment by aaronpk** [comment]
Okay, then this should be updated: "HTML markup, including visual images such as images, may be included"

http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams-vocabulary/#dfn-summary

And same with title, since it also says MAY.

**Comment by aaronpk** [comment]
Further discussion in IRC: http://socialwg.indiewebcamp.com/irc/social/2015-11-04#t1446680783291

**Comment by aaronpk** [comment]
Summary:

* `displayName` is *always* plaintext
* `summary` is *always* HTML
* `content` is default HTML, unless otherwise specified by the `mediaType` attribute, which only applies to content

**Comment by elf-pavlik** [comment]
can we define separate *contentType* of *contentMediaType* instead of overloading *mediaType* used for as:Link ?

this should also make it more clear that we talk about media type for value   of content property

mediaType used on object seems like some kind of hint for content negotiation

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "type": "Note",
  "summary": "Summary without markup",
  "mediaType": [ "application/acivity+json", "text/turtle", "text/mf+html" ],
  "content": "<p>HTML content goes <b>here</b></p>"
}
```

**Comment by jasnell** [comment]
-1... I don't think a separate property is required.

**Comment by jasnell** [comment]
The editorial clarification is addressed in https://github.com/jasnell/w3c-socialwg-activitystreams/pull/253
