### ISSUE TITLE
Remove `title` attribute

### ISSUE THREAD

**Issue by aaronpk** [jasnell/w3c-socialwg-activitystreams#247]
Since title and name are essentially the same value, but title allows for HTML markup, we can simplify this by just removing title, especially since it hasn't had much (correct) use.

More discussion in IRC: http://socialwg.indiewebcamp.com/irc/social/2015-11-04#t1446680347483

**Comment by jasnell** [comment]
+1

**Comment by elf-pavlik** [comment]
:+1:

**Comment by kevinmarks** [comment]
+1

**Comment by azaroth42** [comment]
:+1:

**Comment by wilkie** [comment]
+1

**Comment by gobengo** [comment]
+1 iff 'title' is reserved in future and equivalencies set up in context and AS1 interpretation (non-normative) bit

**Comment by jasnell** [comment]
Resolved
