### ISSUE TITLE
Rename `displayName` to `name`

### ISSUE THREAD

**Issue by aaronpk** [jasnell/w3c-socialwg-activitystreams#248]
The "displayName" terminology is an artifact from storing given name and family name in different properties, and [`getDisplayName` was a function](https://opensocial.atlassian.net/wiki/pages/viewpage.action?pageId=527247#Opensocial.Person(v0.9)-opensocial.Person.getDisplayName) that returned the combination of them. Since we're using "name" to talk about things that are not just names of people, this doesn't really make sense anymore. We can simplify the spec by renaming the `displayName` property to `name`.

More discussion in IRC: http://socialwg.indiewebcamp.com/irc/social/2015-11-04#t1446680347483

**Comment by jasnell** [comment]
+0 ... as I said in the IRC chat, if this helps us move forward, then ok.

**Comment by tantek** [comment]
+1

**Comment by elf-pavlik** [comment]
:+1: also in line with http://schema.org/name

**Comment by jaywink** [comment]
:+1: I think this makes sense

**Comment by gobengo** [comment]
+0. If we do it, the mapping should be part of the AS1 conversion context http://www.w3.org/TR/activitystreams-core/activitystreams1-context.jsonld

**Comment by jasnell** [comment]
@gobengo ... the separation between the `displayName` and `displayNameMap` forms has to do with limitations in JSON-LD. Specifically, in order for the language map form to work correctly, the JSON-LD context definition has to use the `@container=@language` construction, which causes the compaction algorithm to produce bad results when the value is a simple string. For instance, see: http://tinyurl.com/zgzenok (JSON-LD Playground example).

**Comment by gobengo** [comment]
Interesting. Thanks James.

**Comment by kevinmarks** [comment]
The name/sumamry/content split is strong and maps well to many existing systems. The title/displayName split is confusing. so +1 on this and removing title

**Comment by azaroth42** [comment]
:+1:

**Comment by wilkie** [comment]
+0

**Comment by jasnell** [comment]
Marked as resolved
