### ISSUE TITLE
Ensure -vocabulary has examples of described class features

### ISSUE THREAD

**Issue by azaroth42** [jasnell/w3c-socialwg-activitystreams#249]
In reading the descriptions of the vocabulary terms, some of the classes have guidance on how properties should be used with them.  For example, Add says "The origin can be used to identify the context from which the object originated." I would expect the examples provided to include these features to demonstrate the specific use of the properties. Below is a list where this is not the case:

- [ ] Accept (target)
- [ ] Add (origin)  [compare Remove which does have it]
- [ ] Delete (origin)
- [ ] Offer (target)
- [ ] Profile (describes)

Proposal is to add these features to the examples.

**Comment by jasnell** [comment]
+1

**Comment by evanp** [comment]
I'm closing this in favour of the more specific issues.

**Comment by azaroth42** [comment]
:+1: thanks Evan
