### ISSUE TITLE
Inverse Activities?

### ISSUE THREAD

**Issue by azaroth42** [jasnell/w3c-socialwg-activitystreams#250]
Many of the Activities come in pairs, such as Create/Delete, Add/Remove, Like/Dislike.  The documentation makes no explicit link between these pairs. 

Proposal is that these links should be made explicit in the documentation.

- [ ] Accept / Reject
- [ ] TentativeAccept / TentativeReject
- [ ] Arrive / Leave [is this valid?]
- [ ] Create / Delete
- [ ] Like / Dislike 
- [ ] Join / Leave

There are also several Activities that are essentially state markers that lack inverses and would be difficult to use Undo to negate. For example there is no Unfollow, and the Follow activity could be from months or years in the past. Others include Block/Unblock, Ignore/Unignore, and Flag/Unflag.

**Comment by jasnell** [comment]
I agree with documenting the relationships better. I'm not convinced that we need any like Unfollow/Unblock/Unignore, etc. We tried to go down that road a bit in AS1 and it ended up being fairly cumbersome and I don't believe there was any significant implementation of the Un* variants.

**Comment by azaroth42** [comment]
:+1: on following implementation experience! :)

**Comment by tantek** [comment]
Indeed, given the experience that we don't actually see significant implementation of all the "inverse" activities (all the non-implementation/neglect/ignoring of Un* variants), reasoning or documenting or designing based on "inverse activity" thinking does not reflect real world adoption and practice. We've seen a similar conceptual disconnect in HTML between the theoretical (aspirational) attempts to specify/promote "rev" (reverse relationship attribute on links), and the nearly complete confusion and mis-use of the rev attribute in practice.

In addition, at first glance most of those activities seem more aspirational than empirical and should be dropped from this draft of AS2, e.g. "[Tentative]Accept / [Tentative]Reject" (too generic), "Leave", (keep "Arrive" assuming it is a generic synonym for "Check-in"), "Dislike" (not used in practice).

**Comment by azaroth42** [comment]
I think we should separate the documentation and model simplification issues, apologies for smushing the two together in the issue! If this issue can be the documentation one, we could create a second one for what should or should not be in the vocabulary?

**Comment by cwebber** [comment]
Follow / Unfollow, Like / Unlike, Create / Delete are all used actively
in pump.io.

**Comment by jasnell** [comment]
I'll relabel this is Editorial.

**Comment by csarven** [comment]
re: Like/Dislike/Unlike/Undo .. AFAIK, Dislike is not very common in the wild (probably more so to encourage or trigger positive behaviour or emotions), however Unlike (given that something was Liked before) is more common. It could be argued that one first Likes and then Undos that Like. While Unlike is a proper inverse of a previous Like activity (provided that Unlike references the previous Like activity), Undo is a blank activity to reverse activities like Like/Follow/CRUD (also referencing the previous activity).

**Comment by jasnell** [comment]
I'm not adverse to removing `Dislike` from the core. Let's just get it as a separate proposal.

**Comment by jasnell** [comment]
Addressed in https://github.com/jasnell/w3c-socialwg-activitystreams/pull/253
