### ISSUE TITLE
dfn-ojbect is pointed to by both "Object" and "object"

### ISSUE THREAD

**Issue by melvincarvalho** [jasnell/w3c-socialwg-activitystreams#252]
See: https://lists.w3.org/Archives/Public/public-socialweb/2015Nov/0046.html

Example in ( http://www.w3.org/ns/activitystreams#Activity )

**Comment by elf-pavlik** [comment]
* Class: http://www.w3.org/TR/activitystreams-vocabulary/#dfn-object
* property: http://www.w3.org/TR/activitystreams-vocabulary/#dfn-object-term

**Comment by jasnell** [comment]
Appears to be a ReSpec bug.
