### ISSUE TITLE
Add tag to Collection

### ISSUE THREAD

**Issue by kevinmarks** [jasnell/w3c-socialwg-activitystreams#254]
The most common collection type in the wild is the tag - this maps to blogs, twitter, instagram flickr, everything. Objects can have tags to say that they are in a tagged collection, so collection should have a tag to say which tag it is collecting. This solves the memberOf issue with something we can instantly map to every existing blog.

**Comment by jasnell** [comment]
Not following. `Collection` objects already have the 'tag' property. It is inherited from the base `Object`

**Comment by kevinmarks** [comment]
Ah, that wasn't clear in the spec, sorry. In that case I think we have everything we need for memberOf via tag.

**Comment by BigBlueHat** [comment]
Suggest closing in favor of moving conversation about using tag for the `partOf`/`memberOf` use case to issue #205
