### ISSUE TITLE
AS2 specs should have a section on privacy implications

### ISSUE THREAD

**Issue by tantek** [jasnell/w3c-socialwg-activitystreams#255]
Per the charter: http://www.w3.org/2013/socialweb/social-wg-charter.html

"Each specification must contain a section detailing any known security and privacy implications for implementers, Web authors, and end users." 

I note that there is a "Security Considerations" section already: 
http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams-core/index.html#security-considerations

Either expanding that into a "Security and Privacy Implications" or adding a separate "Privacy Implications" section would be fine, making sure to explicitly mention potential impacts on "implementers, Web authors, and end users".

Thanks!

**Comment by jasnell** [comment]
Any particular specific concerns that should be noted?

**Comment by akuckartz** [comment]
:+1:

**Comment by jasnell** [comment]
A PR with specific text or a listing of specific concerns would be the most helpful path forward

**Comment by jasnell** [comment]
ping @tantek ...

**Comment by jasnell** [comment]
Added to current editor's draft. Need to determine if more is needed

**Comment by jasnell** [comment]
ping @tantek ... can you take a look at the current editor's draft to see if the section added is sufficient?

**Comment by tantek** [comment]
Sorry, missed this. What's the fragment URL to the section on privacy implications in the current editor's draft?

**Comment by jasnell** [comment]
http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams-core/#privacy

**Comment by jasnell** [comment]
Privacy section added.
