### ISSUE TITLE
Add a "confirm" activity type to the vocabulary

### ISSUE THREAD

**Issue by rpeinl** [jasnell/w3c-socialwg-activitystreams#256]
My use case is collaborative skill management similar to what Linked.in or Researchgate are doing with their "endorsements". 
User A is saying about himself: I have skill X
Translates to an activity like: 
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "id": "http://www.test.example/user/a/skill/x",
  "actor": "user a",
  "type": "add",
  "object": {
      "type": "Skill",
      "displayName": "skill x"
    }
  "target": "user a"
}

Now what about user B stating suggesting that user A has skill Y, which Y not yet being present on the user profile of user A.
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "id": "http://www.test.example/user/a/skill/y",
  "actor": "user b",
  "type": "add",
  "object": {
      "type": "Skill",
      "displayName": "skill y"
    }
  "target": "user a"
}
I thought about offer as an activity type but I guess add makes more sense, if the skill is not yet present.

Now finally, user A's profile already states that user A has skill z, but user B wants to confirm that it is so.
`<code>`{
  "@context": "http://www.w3.org/ns/activitystreams",
  "id": "http://www.test.example/user/a/skill/x",
  "actor": "user b",
  "type": "???",
  "object": {
      "type": "Skill",
      "displayName": "skill z"
    },
  "target": "user a"
}`</code>`
What kind of activity do I use here? Is it "accept"? User b accepts skill z for user a?
Could be, but seems heavily overloaded. Is it again "add"? That would make no difference between initial suggestions and further confirmations.
Therefore I suggest introducing "confirm" as a new activity type.
Again, as posted on the mailing list, I also suggest making a list of use cases together with activities that should be used in these cases similar to my description here. That would largely increase interoperability.

**Comment by jaywink** [comment]
Wouldn't `Accept` be quite natural here?

**Comment by jasnell** [comment]
We had `Confirm` before but it was removed in favor of `Accept`. `Confirm` is something that could be added via an extension.
