### ISSUE TITLE
"@id" -> "id" etc

### ISSUE THREAD

**Issue by sgoendoer** [jasnell/w3c-socialwg-activitystreams#257]
Hi, sorry to come up with an issue like this, but I noticed that in the latest specification of AS2 (in GitHub from 24 November 2015), the "@" has been dropped from common JSON-LD keywords such as "id" and "type". Is this intentional?

In the docs, it is still stated that "JSON-LD keywords" are used (e.g. AS2Core from 11-24-2015 Section 3.1): 
> In addition to having a global identifier (expressed as an absolute IRI using the JSON-LD @id keyword) and an "object type" (expressed using the JSON-LD @type keyword)

Also, the latest JSON-LD spec does not seem to have dropped the "@" in any form.

**Comment by gobengo** [comment]
@sgoendoer I think the idea is that the AS '@context' will make 'id' equivalent to '@id'. So everything will still be mappable for the linked-data folks who are context-aware.

**Comment by jasnell** [comment]
Good point, I'll get this clarified in the text. PRs are also helpful :-)

**Comment by jasnell** [comment]
Addressed in https://github.com/jasnell/w3c-socialwg-activitystreams/pull/253
