### ISSUE TITLE
Change link relation type clause from MUST to SHOULD

### ISSUE THREAD

**Issue by gobengo** [jasnell/w3c-socialwg-activitystreams#259]
https://hypothes.is/a/28iF2d2ESHu55ZMRLnFOfw

> To promote interoperability, Activity Streams 2.0 implementations MUST only use link relations that are valid in terms of both the [RFC5988] and [HTML5] definitions.

Seems like this should be SHOULD. The former requires emailing someone at IESG. The latter is wiki-based.

Small issue, but the charter leaves option open to a conformance suite, and it would be a shame to not be conformant because using HTML5-only link rels.

**Comment by jasnell** [comment]
I'm fine with that

**Comment by kevinmarks** [comment]
+1 especially as RFC5998bis is changing the IANA process at the moment

**Comment by tantek** [comment]
SHOULD would allow folks to use [HTML5] method to register link relations (wiki edit) which is the minimum needed which is preferable to having to email IANA etc.

**Comment by jasnell** [comment]
Thinking about it further, the intent of this text is not to say that the link relation used must be registered but must conform to the syntax rules of both sources. The text can be clarified to indicate that.

**Comment by jasnell** [comment]
Include a change in https://github.com/jasnell/w3c-socialwg-activitystreams/pull/253 that addressed this

**Comment by jasnell** [comment]
@gobengo ... please take another look at the current editor's draft language. I think it's an improvement as it specifically indicates that the rel must conform to the syntax rules but allows for unregistered link rel values.

**Comment by jasnell** [comment]
Believe this is covered by current editor's draft. Can reopen the issue if necessary

**Comment by gobengo** [comment]
+1
