### ISSUE TITLE
IntransitiveActivity mentioned once

### ISSUE THREAD

**Issue by rhiaro** [jasnell/w3c-socialwg-activitystreams#260]
It's just linked to vocabulary (in Models), should remove the mention from core as with other Activity types?

**Comment by tantek** [comment]
+1 drop IntransitiveActivity

**Comment by jasnell** [comment]
-1 to dropping it entirely. We have vocabulary terms that are using it that deal with very common geo related use cases. 

It could be moved to just the vocabulary doc as @rhiaro is suggesting.
