### ISSUE TITLE
CR: Need lifecycle and naming convention guidance for extensions to help possible future convergence and standardization

### ISSUE THREAD

**Issue by tantek** [jasnell/w3c-socialwg-activitystreams#261]
Assuming AS2 succeeds with lots of implementations, and extensions succeed, and a few of those extensions themselves succeed among multiple implementations, how do we increase their chances of being formalized as standards?
E.g. failures: RSS extensions, Atom extensions - none every became standard.
Possible good example: Web Components naming convention of "prefix-tagname"

h/t Sandro for bringing it up in the f2f.

**Comment by kevinmarks** [comment]
A possible example of success would be the OpenSocial iteration process which did incorporate extensions in spec iterations.

**Comment by tantek** [comment]
Except that OpenSocial itself lost momentum and had massive implementer drop-off. So I'm not sure how much we can use that as a good / successful example overall.

**Comment by jasnell** [comment]
An example of a prefix tag name convention can be found here: http://asgh.mybluemix.net/page?limit=25

**Comment by jasnell** [comment]
What was discussed at the f2f was the possibility of having a kind of official "Extensions Registry" administered by a Community Group. The details of which would still need to be worked out.

**Comment by tantek** [comment]
Leaving as "CR:" per Sandro's request on today's telcon for more time to evaluate if this issue requires normative changes.

**Comment by elf-pavlik** [comment]
> Possible good example: Web Components naming convention of "prefix-tagname"

[Latest AS2.0 draft](http://www.w3.org/TR/2015/WD-activitystreams-core-20151215/#extensibility)  clearly states

> For extensions, [JSON-LD] is used as the primary mechanism for defining and disambiguating extensions. Implementations that wish to fully support extensions should use [JSON-LD] mechanisms.

Regarding Web Components 'pseudoprefix'-tagname convention, please note this issue in official W3C repo [Support renaming, aliasing, or namespacing imported elements](https://github.com/w3c/webcomponents/issues/344)

**Comment by jasnell** [comment]
WG chose to close without further action
