### ISSUE TITLE
"1.2 Serialization Notes" normative section should not have "Note(s)" in title

### ISSUE THREAD

**Issue by tantek** [jasnell/w3c-socialwg-activitystreams#262]
http://www.w3.org/TR/activitystreams-core/

Note tends to imply informative / non-normative. Normative sections should not have "note" in their labeling / intro text as in tends to imply non-normative.

Editor's choice of renaming of section / heading.

**Comment by jasnell** [comment]
Addressed in https://github.com/jasnell/w3c-socialwg-activitystreams/pull/253
