### ISSUE TITLE
Editorial: Clarify the description of Link

### ISSUE THREAD

**Issue by azaroth42** [jasnell/w3c-socialwg-activitystreams#263]
Clarify that the Link object represents the link to a resource, and the properties are not the properties of the resource.  Clarify that height, width, duration, hreflang and mediaType are hints to help rendering of the referred to resource.

Example from @aaronpk that image should be displayed at height x width, rather than that the image is height x width.

**Comment by azaroth42** [comment]
In `http://www.w3.org/TR/activitystreams-vocabulary/#dfn-link`:
> A Link is an indirect, qualified reference to a resource identified by a URL.

Suggest: A Link is an indirect, qualified reference to a resource identified by the URL in the href property. The Link properties of the Link object are not the properties of the referenced resource, but are provided as hints for rendering agents to understand how to make use of the resource. For example, height and width might represent the desired rendered size of a referenced image, rather than the actual pixel dimensions of the referenced image.

Happy to do a PR if the above captures the resolution accurately.

**Comment by gobengo** [comment]
This was helpful reading for me: http://patterns.dataincubator.org/book/qualified-relation.html
