### ISSUE TITLE
Are extensions possible without JSON-LD?

### ISSUE THREAD

**Issue by gobengo** [jasnell/w3c-socialwg-activitystreams#265]
Tantek made a good point today that the charter says JSON but not JSON-LD. But the charter does not specify that the Core Syntax must be extensible (in only JSON).

Is this a problem? How do we expect pure-JSON extensions to develop?

**Comment by gobengo** [comment]
Perhaps by specifying a JSON property registry in Core

**Comment by gobengo** [comment]
@rpeinl does this capture your concern from a second ago?

**Comment by rpeinl** [comment]
no (see #266)

**Comment by jasnell** [comment]
New language has been added to the editor's draft dealing with this.
