### ISSUE TITLE
CR: Reconsider height, width, duration on Link/Content

### ISSUE THREAD

**Issue by azaroth42** [jasnell/w3c-socialwg-activitystreams#267]
Issue: Related to #263 and coming proposal from @tantek, there are semantic inconsistencies with using height, width and duration for both Content and Link types. When used with Content, they are properties of the resource, whereas for Link they are hints about the resource referenced via href.  The semantics of the property should not be different based on the type of the resource that the property is associated with.  Consider also mediaType (the property of Link) vs type (the name of the property in 5988, that would conflict with @type) as precedent.

Proposal: If these properties are kept, then they could be renamed to hrefheight, hrefwidth, hrefduration with corresponding predicates in the vocabulary.  This would be consistent naming with hreflang and make the referent clear as the resource identified by the URI in href.

**Comment by azaroth42** [comment]
Alternative discussed with @jasnell face to face:
 * Drop height, width and duration from Content and keep them as-is on Link
 * Image / Audio / Video types would thus need an object in url with those properties

Also consistent and cleaner than the proposal but a larger change.

**Comment by jasnell** [comment]
+1 to dropping height, width and duration from Content object's. (which, btw, ought to allow us to drop the root Content type and flatten the hierarchy further).

**Comment by azaroth42** [comment]
:+1: to dropping Content completely. Simplification++

**Comment by jasnell** [comment]
@azaroth42 ... perhaps let's close this issue and open a new one specifically to remove Content and flatten the hierarchy a bit

**Comment by jasnell** [comment]
@azaroth42 ... now that we have another issue (#268) let's close this one

**Comment by azaroth42** [comment]
Agreed with the caveat that if #268 is not accepted, we would need to re-open this one as the original issue would still remain.
