### ISSUE TITLE
Dropping Content Objects

### ISSUE THREAD

**Issue by rhiaro** [jasnell/w3c-socialwg-activitystreams#268]
As briefly discussed at f2f; assuming there's a separate spec for describing content objects.

Presumably including objects which extend Content (Article, Document, Audio, Image, Video, Note, Page, Question(?), Profile; would be inclined to include Event though that doesn't extend Content currently) and all properties that only belong to these.

**Comment by azaroth42** [comment]
@rhiaro Is the proposal to drop Content _and all subClasses_ or to drop just Content and flatten the hierarchy, but keep the subClasses like Image etc?

**Comment by jasnell** [comment]
Things like Article, Document, Audio, Image, Video, Note, Page, Question and Profile should remain in the vocabulary but would extend from Object rather than Content. For most of these, type specific properties are not defined but the object type is common enough within social apps that common types should be provided. Removing Content, however, is an overall simplification that flattens the existing hierarchy by removing what is essentially a non-functional abstract class

**Comment by rhiaro** [comment]
Righto! Misunderstood. Makes sense.

**Comment by azaroth42** [comment]
Per #267 discussion, :+1: to dropping Content class and height, width and duration properties.

**Comment by jasnell** [comment]
Well, the `height`, `width` and `duration` would be retained as properties on `as:Link` only, but clarified as hints

**Comment by azaroth42** [comment]
Sorry, yes, that :)

**Comment by gobengo** [comment]
@jasnell So... comments on the internet and microblog posts, what are those? Documents?

Notes? The good ones are, on average, more than just a paragraph.
> Represents a short written work typically less than a single paragraph in length.

I suppose Article works.

**Comment by jasnell** [comment]
Notes or Article

**Comment by jasnell** [comment]
Have a PR that includes dropping Content --> https://github.com/jasnell/w3c-socialwg-activitystreams/pull/270

**Comment by tantek** [comment]
@gobengo in practice I've found comments to just be notes with in-reply-to. sometimes articles, sometimes photos. either way not their own type per se.

**Comment by gobengo** [comment]
Does this mean Person.height is uninterpretable?

**Comment by jasnell** [comment]
@gobengo ... yes, you could do that but it would define the person's height in device-independent pixels ;-)

**Comment by jasnell** [comment]
The WG approved this.
