### ISSUE TITLE
Proposal: Add `expires` property to allow for explicitly transient objects

### ISSUE THREAD

**Issue by jasnell** [jasnell/w3c-socialwg-activitystreams#269]
Adding an `expires` property to Object may provide an approach to explicitly transient objects / activities

/cc @cwebber

**Comment by jasnell** [comment]
After WG discussion at the F2F, it was decided to hold off on this but to continue investigating possible approaches.

**Comment by gobengo** [comment]
+1 . It's important to have 'expires' as part of object authoring/representation (by end-users) and not just processing requirements (of silos/etc)

**Comment by sandhawke** [comment]
As I understand it, this would be a MUST-UNDERSTAND extension, and AS2 doesn't have a way to have such things, so this can't be done as an extension.

**Comment by jasnell** [comment]
WG decided to close this without further action. @gobengo -1'd the proposal but @tantek indicated that @gobengo was not a WG member so the -1 was not counted.
