### ISSUE TITLE
`@id`s are vulnerable to unwelcome expansion

### ISSUE THREAD

**Issue by MerelyAPseudonym** [jasnell/w3c-socialwg-activitystreams#273]
As a brief illustration: `tag:search.twitter.com,2005:593895901623496704` gets expanded to `http://www.w3.org/ns/activitystreams#tagsearch.twitter.com,2005:593895901623496704`.
* [an example using the official (draft) context](http://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Factivitystreams%22%2C%22%40id%22%3A%22tag%3Asearch.twitter.com%2C2005%3A593895901623496704%22%2C%22%40type%22%3A%22Create%22%2C%22url%22%3A%22http%3A%2F%2Ftwitter.com%2FKidCodo%2Fstatuses%2F347769243409977344%22%2C%22actor%22%3A%7B%22%40id%22%3A%22id%3Atwitter.com%3A2993982541%22%2C%22%40type%22%3A%22Person%22%2C%22displayName%22%3A%22Kid%20Codo%22%2C%22url%22%3A%22http%3A%2F%2Fwww.twitter.com%2FKidCodo%22%2C%22image%22%3A%22https%3A%2F%2Fsi0.twimg.com%2Fprofile_images%2F3664410292%2F1d75c213a572873bf6797c5591475da5_normal.jpeg%22%7D%7D)
* [an example that uses the most recent `activitystreams2-context.jsonld` from the GitHub repository](http://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%22https%3A%2F%2Fraw.githubusercontent.com%2Fjasnell%2Fw3c-socialwg-activitystreams%2F437292ef86fb3cea3b543fb8c1c0c0380b1b5a74%2Factivitystreams-core%2Factivitystreams2-context.jsonld%22%2C%22%40id%22%3A%22tag%3Asearch.twitter.com%2C2005%3A593895901623496704%22%2C%22%40type%22%3A%22Create%22%2C%22url%22%3A%22http%3A%2F%2Ftwitter.com%2FKidCodo%2Fstatuses%2F347769243409977344%22%2C%22actor%22%3A%7B%22%40id%22%3A%22id%3Atwitter.com%3A2993982541%22%2C%22%40type%22%3A%22Person%22%2C%22name%22%3A%22Kid%20Codo%22%2C%22url%22%3A%22http%3A%2F%2Fwww.twitter.com%2FKidCodo%22%2C%22image%22%3A%22https%3A%2F%2Fsi0.twimg.com%2Fprofile_images%2F3664410292%2F1d75c213a572873bf6797c5591475da5_normal.jpeg%22%7D%7D)

## Background
[GNIP uses `tag` and `id` as schemes in the IRIs that it provides for Tweets and users of Twitter](http://support.gnip.com/sources/twitter/data_format.html). I'd expect that these should be preserved as-is in any Activity Stream 2.0 document.

**Comment by MerelyAPseudonym** [comment]
By the way, I'm pretty new to JSON-LD in addition to Activity Streams, so I apologize if (e.g.,) this is actually a JSON-LD problem and not an AS problem.

**Comment by MerelyAPseudonym** [comment]
It seems like one workaround is to "unmap" the terms, like:

```json
{
  "@context": [
    "http://www.w3.org/ns/activitystreams",
    {"tag": null}
  ],
  "@id": "tag:search.twitter.com,2005:593895901623496704",
  "@type": "Create",
  "url": "http://twitter.com/KidCodo/statuses/347769243409977344",
  "actor": {
    "@context": {"id": null},
    "@id": "id:twitter.com:2993982541",
    "@type": "Person",
    "displayName": "Kid Codo",
    "url": "http://www.twitter.com/KidCodo",
    "image": "https://si0.twimg.com/profile_images/3664410292/1d75c213a572873bf6797c5591475da5_normal.jpeg"
  }
}
```

But this seems kludgy, and I could imagine it having unintended consequences if other parts of the JSON document actually used the `tag` property and expected it to expand to `http://www.w3.org/ns/activitystreams#tag`.

**Comment by jasnell** [comment]
Yes, this is an unfortunate limitation of JSON-LD. Unfortunately there's not much we can actually do about it other than, perhaps, mention it briefly in the spec.

**Comment by MerelyAPseudonym** [comment]
@jasnell Thank you for clarifying, and I'm especially grateful/impressed that you replied so promptly!
