### ISSUE TITLE
CR: Require valid AS2 implementations to use AS2 vocab where applicable

### ISSUE THREAD

**Issue by rpeinl** [jasnell/w3c-socialwg-activitystreams#276]
In the current editors draft it is stated that
"An implementation that wishes, for example, to use http://schema.org/LikeAction as an Activity should identify that Object as being both a Like and an http://schema.org/LikeAction, as illustrated in the following" (section 4.4)
I think that we should require (MUST) that the respective AS2 vocabulary is used in such cases, because otherwise it could lead to implementations having an "AS2 compliant" label which do not even use AS2 vocabulary. That seems very strange to me.

**Comment by akuckartz** [comment]
I am not convinced that "must" is necessary: "should" has a defined meaning.

**Comment by rpeinl** [comment]
I'm aware of the definition of "should" in RFC2119. However, I don't see a case where particular circumstances would lead to the fact that it's better to NOT use the defined AS2 vocabulary and use some other vocabulary with the same meaning instead, while still wanting to be AS2 compatible in general. My primary goal when contributing to the AS2 specification is to achieve interoperability and in my eyes a SHOULD will lead to less interoperability. The example in the draft is a good compromise from my perspective and I don't see, why we should allow anything else than that.

**Comment by jasnell** [comment]
I understand the point but like @akuckartz I'm not sure "must" is completely necessary

**Comment by cwebber** [comment]
I think SHOULD is fine.

**Comment by melvincarvalho** [comment]
+1 SHOULD

**Comment by jasnell** [comment]
WG decided to close this without action

**Comment by jasnell** [comment]
Actually.. nevermind, this was held open

**Comment by tantek** [comment]
Making clear this issue affects normative spec requirements.

**Comment by jasnell** [comment]
WG resolved to close this and change this to MUST
