### ISSUE TITLE
Proposal: Drop "Actor" Type

### ISSUE THREAD

**Issue by jasnell** [jasnell/w3c-socialwg-activitystreams#277]
The `Actor` type currently serves as a base class for the five primary Actor types. It does not, however, define any actor specific properties and it would be highly unlikely for an implementation to use the `Actor` type directly. We can flatten the model a bit more by simply removing the `Actor` type and having `Person`, `Group`, `Organization`, `Service`, and `Application` extend directly from `Object`

**Comment by cwebber** [comment]
Hm... I kind of find Actor to be useful as a conceptual model of what's going on, and to understand what activitystreams terms most frequently fill in the "actor" slot.  I'm -0 on this... I think it would be a minor loss to lose that information, but I'm not strongly against it.

**Comment by jasnell** [comment]
WG decided to accept this change.

**Comment by jasnell** [comment]
Done
