### ISSUE TITLE
W3C Social WG members and other contributors missing in Acknowledgements section

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#278]
* http://www.w3.org/2000/09/dbwg/details?group=72531&public=1
* https://github.com/jasnell/w3c-socialwg-activitystreams/issues?utf8=%E2%9C%93&q=is%3Aissue+
* https://github.com/jasnell/w3c-socialwg-activitystreams/graphs/contributors

**Comment by jasnell** [comment]
Yep, the plan is to update this immediately before pushing the CR version.

**Comment by jasnell** [comment]
Updated
