### ISSUE TITLE
CR: What are the separate "features" of AS2?

### ISSUE THREAD

**Issue by sandhawke** [jasnell/w3c-socialwg-activitystreams#280]
Sorry for pointing this out so late.   At first I thought it could be in the Test Suite, but thinking about it more, esp in relation to the Conformance Clause (see #281), it seems like it might be important to have in the spec.

Basically, when you look at how other specs are adopted, you see people talking about whether certain features are implemented or not.   For example, in
https://kangax.github.io/compat-table/es6/

And our CR exit criteria is that every feature is implemented by two or more independent code bases, but ... what's a feature?      https://www.w3.org/wiki/Socialwg/2016-01-12-minutes#resolution03

To pick on one example, is paging a feature?  Or is having 'next' links a feature?

I'm imagining this being addressed by having a table of features, which vocabulary terms they use, and whether they are mandatory or optional in a conforming implementation.   Something like that.

**Comment by gobengo** [comment]
> I'm imagining this being addressed by having a table of features, which vocabulary terms they use, and whether they are mandatory or optional in a conforming implementation. Something like that.

Could this just be the set of all [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt) propositions? 'MUST' -> mandatory. 'SHOULD' -. Optional?

**Comment by sandhawke** [comment]
Yes, I'd expect it to use 2119 language.  Note that in 2119, OPTIONAL is MAY, not SHOULD.   In general, SHOULDs SHOULD be avoided.  :-)
