### ISSUE TITLE
Implementation of Relationships

### ISSUE THREAD

**Issue by rhiaro** [jasnell/w3c-socialwg-activitystreams#282]
> The Activity Streams vocabulary does not define normative values for use with the relationship property. It is expected that implementations will make use of several existing vocabularies that have been developed for the purpose of describing relationships. Examples of such vocabularies include the "Friend of a Friend" and "Relationship" vocabularies.

The Relationships vocabulary is pretty old and honestly seems a bit weird in some of the terms it provides (in my unprofessional opinion). Possibly there just isn't anything better or more up to date to suggest or add to this list (if there are "several" we should list more, if there aren't we shouldn't say "several"), but I wonder if anyone else is interested in softening the endorsement of it by rephrasing to something like:

"The Activity Streams vocabulary does not define normative values for use with the relationship property. It is expected that implementations will reuse existing vocabularies that have been developed for the purpose of describing relationships, or create their own guided by requirements of their particular implementation. Existing vocabularies include the "Friend of a Friend" and "Relationship" [and ideally add more] vocabularies."

This is editorial, as the Implementations section is non-normative.

**Comment by jasnell** [comment]
+1

**Comment by jasnell** [comment]
Addressing in next update

**Comment by dmitrizagidulin** [comment]
What's the plan to address this, in the next update?

**Comment by jasnell** [comment]
I used Amy's suggested text. It's in the current editors draft.

**Comment by dmitrizagidulin** [comment]
Thanks! (I didn't catch the verb tense of the comment, sorry bout that)
