### ISSUE TITLE
Extension Registry and tweet:id

### ISSUE THREAD

**Issue by gobengo** [jasnell/w3c-socialwg-activitystreams#283]
I would like to represent some tweets or tweet-equivalents in AS2. Let's assume the tweet with id_str '696429143659917312'

I believe this is not valid AS2 because the value of "id" is not an absolute IRI
```json
{ "id": "696429143659917312" }
```

There are many arbitrary ways I could try to make that an absolute IRI (e.g. "urn:twitter.com:status=696429143659917312"), but I don't think those are conducive to interoperability.

It seems like a better way would be to define an extension namespace like 'twitter' with a property in that namespace like 'id' or 'id_str'. Then I could be like

```json
{
  "@context": [
    "http://www.w3.org/ns/activitystreams",
    { "twitter": "http://www.w3.org/ns/activitystreams/extension-registry/twitter" }
  ],
  "twitter:id_str": "696429143659917312",
  "url": "https://twitter.com/bengo/status/696429143659917312"
}
```

Couple questions
1. Is there a better way for this use case than what I'm talking about (via an extension)?
2. I remember that we (e.g. @sandhawke) talked a lot in SF on Dec 1/2 2015 about 'the right way' of enabling extensions, including the creation of a registry of some sort. But I think we never settled on it. Where are we at now? I'm happy to author/host/strawman an extension enabling this use case, but how?

Advising on this will help me specify our implementation. We also aggregate social data from other networks like Instagram, Facebook, et al.

**Comment by MerelyAPseudonym** [comment]
> an extension namespace like 'twitter' with a property in that namespace like 'id' or 'id_str'

This is very similar to what we're doing in a prototype that my company is building. Any Twitter data that can't be mapped cleanly into AS2 gets prefixed with `twtr:`, and the context specifies that `twtr` expands to `http://example.com/uncontrolled-third-party-data/twitter#` (actual URI pending).

**Comment by MerelyAPseudonym** [comment]
Not to say there shouldn't be any sort of *official* extension/registration policy; I just figured it might be helpful to know what other implementers are doing.

**Comment by kevinmarks** [comment]
Surely https://twitter.com/bengo/status/696429143659917312 is the canonical absolute IRI for tweet id 696429143659917312  

Note that twitter will redirect tot he correct URL for any username in the first path slot, so you could construct a URL https://twitter.com/activity-streams/status/696429143659917312 and it would be valid.

Making a non URL id for something that is manifestly a URL is quixotic.

**Comment by gobengo** [comment]
We discussed in telecon today. http://socialwg.indiewebcamp.com/irc/social/2016-02-23#t1456252025876

Resolution is a bit of: No extension registry needed quite yet. Vendor-specfic vocabulary may be helpful. When in doubt, draft it on the SocialWG Wiki
https://dev.twitter.com/overview/api/tweets

**Comment by gobengo** [comment]
https://www.w3.org/wiki/Socialwg/Twitter-Vocabulary
