### ISSUE TITLE
Feedback on AS2 from django implementer of v1

### ISSUE THREAD

**Issue by kevinmarks** [jasnell/w3c-socialwg-activitystreams#285]
Yes, ive looked at v2 a while back like in the spring/summer. im sure things have changed a bit so ill catch up. i really like the use of json-ld which should let people implement their own context descriptors when they need to. a lot of the implementations out there diverge very far off v1 spec to implement the types of metadata that all the new context descriptors will address. 

I'm finding the default context a bit hard to understand since a lot of the entities i think are verbs (eg Add) are mixed in with obvious object types (eg Album). i think since there is so much data in the context it should be crystal clear to users (like the registry documentation) what types are used for what. for example, in the v1 spec the issue i see with a lot of implementations is that people often dont know which correct verb to use in their use case. ive seen all too often a verb of 'commented' when they mean to 'send' a comment object. 

For my django app, the context descriptors are going to make a hard layer of conformity vs customizability to introduce. id like users to be able to declare contexts easily within their django project in python and have the feeds interpret what the responses should be. additional contexts would have to be identified by the users or generated by the app. some of the spec types will apply to django models (eg Album) and others will apply to model fields (eg URLField). is there anything you'd like to see out of the app going forward or the current v1 implementation?

At one point i had thought about being really restrictive about the spec on which verb and objectTypes users are allowed to use. i had wanted to give a limited selection or even to have it error out if you didnt follow the spec but decided against it. im of the attitude, that ive expressed in tickets before, is "it aint my spec, i just hit people over the head with it"

**Comment by justquick** [comment]
for reference this is the Django application that implements the v1 specs https://github.com/justquick/django-activity-stream
