### ISSUE TITLE
Language in Appendix B [non-CR, action]

### ISSUE THREAD

**Issue by azaroth42** [jasnell/w3c-socialwg-activitystreams#286]
From action on 2016-02-16 call, I investigated the use of @id and @type in the current AS2 documents.
It's unclear where Natalie found the use of @id and @type in the examples, as both documents only have id and type for examples.  It seems like they were using an older version of the spec and this is just a solved problem :smile_cat: 

Section 5.1, example 103 uses @id and @type unaliased, but in a separate context document so this is appropriate, ditto example 106 in appendix C. There is a non normative reference in Appendix B that implementations should follow the context for the aliases ... which seems harmless. So, on to the issue...

Appendix B is marked as non-normative, but has RFC MUSTs, SHOULDs and MAYs at the same time as "ought to", "can" and "not required to". Non CR blocking request to normalize the language here to be all lowercase, or normatively uppercase.

**Comment by jasnell** [comment]
Addressing this in next update
