### ISSUE TITLE
What is the scope of rel value

### ISSUE THREAD

**Issue by dissolve** [jasnell/w3c-socialwg-activitystreams#287]
This came up in chat last week and i never got a clear answer.  What is the scope of the rel attribute?

The spec says

>  A link relation associated with a Link. The value must conform to both the [HTML5] and [RFC5988] "link relation" definitions.

But this is a bit confusing as HTML5's rel relation is always document scoped.  It looks like RFC5988 says that it doesn't mandate what the context should be and this should be specified in the serialization spec. (https://tools.ietf.org/html/rfc5988#section-3)

**Comment by dissolve** [comment]
Actually, must conform to both would mean it is related to the document as a whole (from html5).  I'm pretty sure this is not the intention.

**Comment by jasnell** [comment]
Conform is intended in terms of syntax, not scope. That can be clarified. The scope of the rel is object in which the link is present. e.g. 

```js
{
  "type": "Note",
  "image": {
    "type": "Link",
    "href": "http://example.org/foo.png",
    "rel": "preview"
  }
}
```

The Link provides a "preview" for the Note.

**Comment by dissolve** [comment]
Agreed, I think it needs to be clarified in the doc.

**Comment by jasnell** [comment]
Addressing in next update
