### ISSUE TITLE
Add a `deleted` timestamp property to Object

### ISSUE THREAD

**Issue by dmitrizagidulin** [jasnell/w3c-socialwg-activitystreams#292]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [x] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

In order to support the [Delete activity](http://w3c-social.github.io/activitypub/#delete-activity) in ActivityPub, add a `deleted` timestamp to Object (similar to the existing `published` property).
When present, this marks the fact that the object is now a "tombstone" object, and has been deleted.

**Comment by cwebber** [comment]
Hm.  Is this an ActivityStreams issue really?  It seems more like something that should go in an ActivityPub specific vocabulary.

Most applications of ActivityStreams won't likely need a "tombstone" concept (in an ideal world, neither would we, and modifications to ActivityPub may be done which drastically reduce the scope to which tombstone objects are at all required)

**Comment by rhiaro** [comment]
Wouldn't `updated` suffice if it was necessary to track this?

**Comment by dmitrizagidulin** [comment]
@cwebber - Does ActivityPub have its own vocabulary?

In general, though, distributed applications tend to need tombstones (because it's difficult to distinguish intentional deletion and data loss or failed operations). How else are you going to return a 410 Gone?

@rhiaro - maybe? How would you tell that this was a tombstone object (and return a 410) with `updated`?

**Comment by rhiaro** [comment]
Isn't a tombstone by definition an object with ~nothing in it that is
implicitly deleted?

**Comment by dmitrizagidulin** [comment]
Give an example? What would that look like, in AS2 format?

**Comment by jasnell** [comment]
@rhiaro ... no, an object that has nothing in it is not a tombstone, it's just an incomplete representation. For Atom, we had to create an explicit "Tombstones" draft: https://tools.ietf.org/html/rfc6721

A `deleted` property would make sense if it was felt that a similar use case was required in core.

**Comment by jasnell** [comment]
But then again, you could accomplish the same with...

```
{
  "type": "Delete",
  "object": {
    "type": "Note",
    "content": "This is a note"
  }
}
```

**Comment by jasnell** [comment]
Thinking about it further, I'm -1 on adding a new `deleted` property. AS2 already includes the ability to do tombstones.

Consider this scenario. I create a Note object with the id "http://example.org/notes/1", let's say the AS2 JSON for that note can also be retrieved from that same URL:

```json
{
  "type": "Note",
  "id": "http://example.org/notes/1",
  "content": "Hello world!",
  "updated": "2016-03-17T12:34:56Z"
}
```

I have an Activity Streams collection document that I use to notify the world about my new note. Hundreds of thousands of my subscribers receive their copy of this note.

```json
{
  "type": "Collection",
  "items": [
    {
      "type": "Create",
      "actor": "http://jasnell.me",
      "updated": "2016-03-17T12:34:56Z",
      "object": {
        "type": "Note",
        "id": "http://example.org/notes/1",
        "content": "Hello world!",
        "updated": "2016-03-17T12:34:56Z" 
      }
    }
  ]
}
```

Later I decide, whoops, I shouldn't have said that, so I delete the note. Deleting the note and creating the note are two entirely separate actions. There are two things that I'm going to do: (a) I'm going to delete the note located at `http://example.org/notes/1` so that any HTTP GET requests return a 404, then, (b) I'm going to let my subscribers know that the note was deleted but dropping a new activity entry into my Activity Streams collection document.

```json
{
  "type": "Collection",
  "items": [
    {
      "type": "Delete",
      "actor": "http://jasnell.me",
      "object": "http://example.org/notes/1",
      "updated": "2016-03-18T12:40:56Z"
    },
    {
      "type": "Create",
      "actor": "http://jasnell.me",
      "updated": "2016-03-17T12:34:56Z",
      "object": {
        "type": "Note",
        "id": "http://example.org/notes/1",
        "content": "Hello world!",
        "updated": "2016-03-17T12:34:56Z"
      }
    }
  ]
}
```

There's no need to add the `deleted` property to the original note. The create activity in the Activity Streams collection is a point in time description of something that definitely happened. If I wanted to delete the Creation activity along with the Note, I would assign the Create it's own `id` and would issue two Delete statements, e.g. 

```json
{
  "type": "Collection",
  "items": [
    {
      "type": "Delete",
      "actor": "http://jasnell.me",
      "object": "http://example.org/notes/1",
      "updated": "2016-03-18T12:40:56Z"
    },
    {
      "type": "Delete",
      "actor": "http://jasnell.me",
      "object": "http://example.org/activities/1",
      "updated": "2016-03-18T12:40:56Z"
    },
    {
      "type": "Create",
      "id": "http://example.org/activities/1",
      "actor": "http://jasnell.me",
      "updated": "2016-03-17T12:34:56Z",
      "object": {
        "type": "Note",
        "id": "http://example.org/notes/1",
        "content": "Hello world!",
        "updated": "2016-03-17T12:34:56Z"
      }
    }
  ]
}
```

**Comment by evanp** [comment]
I think the example we had was this. Here's a photo album:

```json
{
  "type": "OrderedCollection",
  "totalItems": 3,
  "name": "Vacation photos 2016",
  "orderedItems": [
    {
      "type": "Image",
      "id": "http://image.example/1"
    },
    {
      "type": "Image",
      "id": "http://image.example/2"
    },
    {
      "type": "Image",
      "id": "http://image.example/3"
    }
  ]
}
```

If image 2 is deleted, we could just exclude it from future versions of the collection:


```json
{
  "type": "OrderedCollection",
  "totalItems": 2,
  "name": "Vacation photos 2016",
  "orderedItems": [
    {
      "type": "Image",
      "id": "http://image.example/1"
    },
    {
      "type": "Image",
      "id": "http://image.example/3"
    }
  ]
}
```

We can also use a deleted flag:

```json
{
  "type": "OrderedCollection",
  "totalItems": 3,
  "name": "Vacation photos 2016",
  "orderedItems": [
    {
      "type": "Image",
      "id": "http://image.example/1"
    },
    {
      "type": "Image",
      "id": "http://image.example/2",
      "deleted": "2016-03-17T00:00:00Z"
    },
    {
      "type": "Image",
      "id": "http://image.example/3"
    }
  ]
}
```

The big problem we discussed with this is that naive implementations will handle them poorly. The second element in this collection is an image that is almost but not quite valid. If you don't support tombstoning well, you'll have images that have been deleted appearing in different places in an app.

The proposal that Ben came up with was that we have a Tombstone type, something like this:

```json
{
  "type": "OrderedCollection",
  "totalItems": 3,
  "name": "Vacation photos 2016",
  "orderedItems": [
    {
      "type": "Image",
      "id": "http://image.example/1"
    },
    {
      "type": "Tombstone",
      "formerType": "Image",
      "id": "http://image.example/2",
      "deleted": "2016-03-17T00:00:00Z"
    },
    {
      "type": "Image",
      "id": "http://image.example/3"
    }
  ]
}
```

The advantage here is that all implementations will need to ignore types they don't understand. So even very naive consumers will correctly skip over the Tombstone in their data.

**Comment by jasnell** [comment]
The problem with using Tombstones like this is that they end up sticking around forever. Consider what happens if your album contains 10k photos and you delete 1k of them. A better solution would be to have separate feeds: one for content, another for activity involving that content. Specifically:

```js
{
  "type": "OrderedCollection",
  "totalItems": 3,
  "name": "Vacation photos 2016",
  "x:activity": {
    "type": "Collection",
    "items": []
  },
  "orderedItems": [
    {
      "type": "Image",
      "id": "http://image.example/1"
    },
    {
      "type": "Image",
      "id": "http://image.example/2"
    },
    {
      "type": "Image",
      "id": "http://image.example/3"
    }
  ]
}
```

```js
{
  "type": "OrderedCollection",
  "totalItems": 3,
  "name": "Vacation photos 2016",
  "x:activity": {
    "type": "Collection",
    "items": [
      {
        "type": "Delete",
        "object": "http://image.example/2"
      }
    ]
  },
  "orderedItems": [
    {
      "type": "Image",
      "id": "http://image.example/1"
    },
    {
      "type": "Image",
      "id": "http://image.example/3"
    }
  ]
}
```

`x:activity` here is an extension property. This is just an example. The activity collection does not have to be included in-line. It can, instead, be a separate document altogether referenced by a link.

**Comment by dmitrizagidulin** [comment]
Is it not up to the original server (and the various consumers) to either perform garbage collection and actually cull the tombstones, OR keep them around forever so they can properly return a `410 Gone`? Permanently recording deletions is one of the usecases that this is trying to solve.

**Comment by jasnell** [comment]
My point is that the vocabulary already includes everything that is needed for this, a new property is not required.
