### ISSUE TITLE
Can Link-objects (the "qualified, indirect relationships") be used to express/mean the same thing as plain-string URLs (the "unqualified direct relationships")?

### ISSUE THREAD

**Issue by MerelyAPseudonym** [jasnell/w3c-socialwg-activitystreams#293]
# Please Indicate One: 
 * [ ] Editorial
 * [X] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

# Please Describe the Issue:
There are some scenarios in which AS2’s flexibility regarding the contents of the `url` attribute are problematic. For example, Elasticsearch doesn't support union types. One way to work around this limitation of Elasticsearch is to ensure a uniform representation of links beforehand. There are two options: ensure that every `url` attribute contains a plain-string URL (or an array of plain-string URLs); or ensure that every `url` attribute contains a Link-object (or an array of Link-objects). Choosing the former would remove the possibility of attaching metadata like `rel` or `mediaType`, so it makes sense to settle on using Link-objects as the standard representation.

Given the above justification for seeking a stricter, uniform representation of links, which of the following documents “mean” the same thing as `{"url": "http://example.org"}`?

```json
{
  "url": {
    "type": "Link",
    "href": "http://example.org"
  }
}
```

```json
{
  "url": {
    "type": "Link",
    "href": "http://example.org",
    "rel": "self"
  }
}
```
(Note the `self` relation in the latter)

**Comment by MerelyAPseudonym** [comment]
(By the way, this topic *was* discussed a bit on IRC, but a request for clarification was never followed up on so I brought it here.)

**Comment by jasnell** [comment]
The example `{"url": "http://example.org"}` is equivalent to `{"url": {"id": "http://example.org"}}`, in other words, the shorthand form is a direct link to the object. It's only a `Link` if `type` includes `Link`.

**Comment by rhiaro** [comment]
Hey @MerelyAPseudonym, does this answer your question? As AS2 is approaching CR, we just want to check that all the closed issues were handled okay. If you don't reply by 1300 EST Tuesday 28 June (the next WG meeting) we're going to assume you're satisfied and it will remain closed.

**Comment by lehors** [comment]
J
cloud 8
Arnaud J Le Hors - Senior Technical Staff Mppoe99mber,0p Open Web Technologies - IBM cloudcomputingp op u


   Amy Guy --- Re: [w3c/activitystreams] Can Link-objects (the "qualified, indirect relationships") be used to express/mean the same thing as plain-string URLs (the "unqualified direct relationships")? (#293) --- 
    From:"Amy Guy" <notifications@github.com>To:"w3c/activitystreams" <activitystreams@noreply.github.com>Date:Fri, Jun 24, 2016 08:27Subject:Re: [w3c/activitystreams] Can Link-objects (the "qualified, indirect relationships") be used to express/mean the same thing as plain-string URLs (the "unqualified direct relationships")? (#293)
  
  Hey @MerelyAPseudonym, does this answer your question? As AS2 is approaching CR, we just want to check that all the closed issues were handled okay. If you don't reply by 1300 EST Tuesday 28 June (the next WG meeting) we're going to assume you're satisfied and it will remain closed.
