### ISSUE TITLE
Is it ever justified for an AS2 object to have both `name` and `nameMap`? (also applies to `content` and `summary`)

### ISSUE THREAD

**Issue by MerelyAPseudonym** [jasnell/w3c-socialwg-activitystreams#294]
Please Indicate One: 
 * [ ] Editorial
 * [X] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

(Full disclosure: I actually have three interrelated questions regarding AS2’s “Natural Language Values”, but I think the question from this issue's title provides a good entry point.)

So, the initial question:
None of the examples in the spec demonstrate an AS2 object containing a `name` attribute *and* a `nameMap` attribute. Is that because any AS2 object containing both `name` and `nameMap` *should* instead incorporate the value from `name` into the value for `nameMap`?

The related/followup questions:
* Does `{"name": "foo"}` mean the same thing as `{"nameMap": {"und": "foo"}}`? Or perhaps `{"nameMap": {"en": "foo"}}`? (assuming the `@context` contains nothing but the default `"http://www.w3.org/ns/activitystreams"`.)
* Are `name`/`summary`/`content` *not* marked as “functional” solely because of `nameMap`/`summaryMap`/`contentMap`? Or are there actually situations in which it's desirable/sensible to have an array of strings be the value of `name`/`summary`/`content` (or as the values of the RFC5646 Language-Tag keys in `nameMap`/`summaryMap`/`contentMap`)?

**Comment by MerelyAPseudonym** [comment]
(I apologize if all of these questions just reduce to JSON-LD ignorance)

**Comment by jasnell** [comment]
It's *possible* but you shouldn't. Choose one. 

If there is no default language established in the context, there is no language tag for the strings. `und` would be appropriate as a fallback. If you do use language tagged strings, use the `*Map` form.

**Comment by MerelyAPseudonym** [comment]
Thank you for the clear recommendation regarding `name` and `nameMap` both being present at once!

**Comment by MerelyAPseudonym** [comment]
@jasnell To rephrase the second followup question from above: is mapping `name` to an array of strings also a "possible but you shouldn't" sort of thing?

**Comment by MerelyAPseudonym** [comment]
(Also: if you'd like me to create new GitHub issues for any followup questions instead of having a back-and-forth conversation in the comments of an GitHub issue, just let me know; I'd be happy to adapt to whichever is more convenient for you.)

**Comment by jasnell** [comment]
Either way is fine :-). And yes, technically with json-ld you can map `name` to an array of strings but don't do that.
