### ISSUE TITLE
Is "name" always a SHOULD for Object types?

### ISSUE THREAD

**Issue by evanp** [jasnell/w3c-socialwg-activitystreams#296]
Please Indicate One: 
 * [ ] Editorial
 * [x] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

**Comment by jasnell** [comment]
It's exactly the same rule as AS1, `name` *should* be provided but it is not required. For best interop, especially when using extension types, providing a `name` is strongly recommended.

**Comment by evanp** [comment]
OK. Many of the top-level objects in our example documents don't have a *name* -- especially Activity and Collection objects.

**Comment by evanp** [comment]
PROPOSAL: explain the reasons for this being a SHOULD

**Comment by evanp** [comment]
@jasnell I should probably be more specific. For the ~169 examples in core and vocabulary, 54 of them have a "name" for the top-level object in the example. 115 don't.

I think we either need to provide a "name" for all the examples, or we need to be more specific for which types of objects "name" is a should. Many of our examples are Activity or Collection types, which I think are probably fine not to have a "name".

**Comment by jasnell** [comment]
If there's a concise way to explain the differences then I'm all for it ;-) It's likely easier just to add a name to all of the examples tho.

**Comment by evanp** [comment]
Like I said, there are 115 of them, plus all the variant versions in different encodings.

**Comment by evanp** [comment]
@jasnell Do you have a tool for updating the examples in different encodings?

**Comment by jasnell** [comment]
heh... "tool" he says. ha!! unfortunately not

**Comment by evanp** [comment]
@jasnell I'm pretty close to unilaterally discarding the other encodings, and re-introducing them at the very end of the process.

**Comment by jasnell** [comment]
Works for me. I wanted to do that before but was blocked from doing so.

**Comment by jasnell** [comment]
Well, at least for microdata which has no canonical mapping

**Comment by evanp** [comment]
All right, it's done. I've removed the examples that aren't JSON-LD, and I've updated all the objects in examples so they have "name" properties.
