### ISSUE TITLE
How to denote a "Closed" poll or discussion thread?

### ISSUE THREAD

**Issue by dmitrizagidulin** [jasnell/w3c-socialwg-activitystreams#297]
Please Indicate One: 
 * [ ] Editorial
 * [x] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

Given that we have provisions for representing Polls and Qura/StackOverflow style Questions ([5.4 - Representing Questions](https://www.w3.org/TR/activitystreams-vocabulary/#questions)) -- is there any way to denote that a poll is closed, or that a question is locked?

**Comment by jasnell** [comment]
There's nothing in the vocabulary currently. That can easily be added as an extension.

**Comment by evanp** [comment]
Decision was made in F2F to move Question and Poll to extension

**Comment by jasnell** [comment]
-1 to removing Question. Seems pointless to do so.

**Comment by evanp** [comment]
@jasnell How do you feel about adding a "closed" timestamp to the Question and Poll types?

**Comment by jasnell** [comment]
Seems harmless.

**Comment by evanp** [comment]
Oops. There is no "Poll" type. I'll add "closed" to Question and then close this issue. It's a little weird to deal with the Question as an Activity and not an Object, though.
