### ISSUE TITLE
separate @context to include when processing AS1.0 documents

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#30]
We could try to create separate context to add when processing AS1.0 documents. It would provide *graceful degradation* requiring some additional post processing (seeAlso #14)

* [ ] #23 redefine *as:verb*
* [ ] [Activity Streams 1.0 Terms](http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams2-vocabulary.html#as1terms)

**Comment by akuckartz** [comment]
Currently I tend to agree with https://github.com/jasnell/w3c-socialwg-activitystreams/issues/30#issuecomment-61757869 Those who want to have more automatic RDF-support then will need to move to AS 2.0.

BUT also take note of this unresolved discussion regarding WKT, JSON-LD and GeoJSON: https://github.com/geojson/geojson-ld/issues/28 (see also: https://github.com/rvguha/schemaorg/issues/113). Converting GeoJSON to WKT might be something to be considered.
