### ISSUE TITLE
scope v context

### ISSUE THREAD

**Issue by jasnell** [jasnell/w3c-socialwg-activitystreams#300]
Consider the following:

```json
{
  "type": "Note",
  "content": "This is a note",
  "scope": {
    "type": "Organization",
    "name": "My Employer"
  },
  "to": ["john@example.com", "sally@example.com"],
  "context": {
    "type": "http://example.org/types/Project",
    "name": "A Project"
  }
}
```

The `scope` indicates that the audience for the note is only members of the Organization.
The `to` indicates specific people who should be actively notified.
The `context` indicates a larger context within which the note exists.

**Comment by jasnell** [comment]
To be clear: `scope` is not access control... it is closely related to `to`/`bto`/`cc`/`bcc` in that a consuming implementation can use it to determine who it ought to display the content to. So, for instance, given the note example above, a consuming implementation may include the note on the activity timeline of anyone associated with the 'My Employer' organization, but it would only activity notify two individuals listed by the `to` property. The `context` property, on the other hand, has absolutely nothing to do with audience targeting. The above note is essentially saying, "This is a note that was created in relation to `A Project`. Make the note available to anyone in the `My Employer` organization but specifically notify John and Sally"

**Comment by dmitrizagidulin** [comment]
> a consuming implementation can use it to determine who it ought to display the content to.

Isn't that a definition of access control? Determining who to display the content to?

**Comment by jasnell** [comment]
No. access control implies selective restriction of access. `scope` is advisory as to the publishers *intent*. A consuming application *may* use the scope/to/bto/cc/bcc to determine it's access control policy if it wishes, but is not required to do so.

In the example, a consuming provider could still choose to allow *anyone* to see the note, but only actively include the note on the activity streams of people in the company.

**Comment by jasnell** [comment]
`scope` *could* be renamed to `audience`

**Comment by dmitrizagidulin** [comment]
Heh, I was typing the very same suggestion, re `audience` :)

**Comment by gobengo** [comment]
An alternative to renaming: Link from the [reference definition](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-scope) of 'scope' to the more detailed explanation of how folks can use it in [5.1.1](https://www.w3.org/TR/activitystreams-vocabulary/#audienceTargeting)
