### ISSUE TITLE
Are the @ symbols going to stay?

### ISSUE THREAD

**Issue by natalieesk** [jasnell/w3c-socialwg-activitystreams#303]
Please Indicate One: 
 * [ ] Editorial
 * [X ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:
It's been suggested that the @ symbols before "type" and "context" are not going to be part of the standard. We are currently using @ symbols and would like to know:

1. If we need to change our keys by dropping the @ symbols?
2. If so, should @type and @context also be supported?

**Comment by jasnell** [comment]
The `@` has been dropped for `id` and `type` only. The `@` cannot be dropped from `@context` because of the way JSON-LD works. The `@` will also remain for all other JSON-LD constructs that happen to be used.

**Comment by evanp** [comment]
I think this question is answered, so I'm going to close the issue.
