### ISSUE TITLE
Definition of IntransitiveActivity is incorrect

### ISSUE THREAD

**Issue by evanp** [jasnell/w3c-socialwg-activitystreams#304]
Please Indicate One: 
 * [x] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [ ] Non-Blocking Issue

Please Describe the Issue:

Section 2 of Activity Vocabulary says, "Instances of IntransitiveActivity are a subclass of Activity whose actor property identifies the direct object of the action as opposed to using the object property." This is incorrect; the actor of the IntransitiveActivity is still the subject of the action. There is no direct object, so no need for an `<object>` property. Compare [intransitive verbs](https://en.wikipedia.org/wiki/Intransitive_verb).

**Comment by jasnell** [comment]
Agreed. +1
