### ISSUE TITLE
add an example with text/markdown content

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#305]
Please Indicate One: 
 * [ ] Editorial
 * [ ] Question
 * [ ] Feedback
 * [ ] Blocking Issue
 * [x] Non-Blocking Issue

Please Describe the Issue:

https://tools.ietf.org/html/rfc7763 specifies 'The text/markdown Media Type'. Markdown became very commonly used in various online social platforms. We also had it also discussed in #229.

seeAlso: https://tools.ietf.org/html/rfc7764

I could make a PR which would add the example of an Article written in Markdown to the Object section of the spec. As well as use 'text/markdown' in example of an Article in vocabulary spec.

**Comment by evanp** [comment]
Why?

**Comment by elf-pavlik** [comment]
I just realized that vocabulary spec already has markdown example in
http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams-vocabulary/#dfn-content
