### ISSUE TITLE
Add a paragraph with benefits of upgrade to 1.0 and 2.0

### ISSUE THREAD

**Issue by evanp** [jasnell/w3c-socialwg-activitystreams#313]
via @shevski

**Comment by shevski** [comment]
So: yes it breaks backward compatibility, but has meant we support diff languages, compatible with json-ld etc.. and the benefits of this

**Comment by evanp** [comment]
@jasnell can you help me out? Here's what I think they are.

* JSON-LD compatibility
* Extensibility framework
* Multi-lingual representation of activities
* Unify "verb" and "objectType" to "type"
* Consistent collection and paging representation
* Introduce Link type for richly-described links
* Incorporate audience targeting into the core spec
* Formalize the namespace of the base vocabulary of object types and activity types

**Comment by tantek** [comment]
This is a very good start @evanp. I would start with the strongest reasons first (i.e. why we had to break backcompat with AS1), and then list the secondary reasons later.

E.g.  (this is all off the top of my head attempting to cluster / group the items above in order of relative importance to existing AS1 developers — for example they would likely care more about simplification and internationalization benefits than say, anything to do with JSONLD)

* Better internationalization: Multi-lingual representation of activities
* Simplified: unify "verb" and "objectType" to "type"
* Dropped other AS1 things not used or never implemented:
** ???
** ???

(are there are other "strong" reasons that we broke backcompat?)

New features:
* Introduce Link type for richly-described links
* Incorporate audience targeting into the core spec

Fixes and extensibility:
* Consistent collection and paging representation
* Formalize the namespace of the base vocabulary of object types and activity types
* JSON-LD compatibility
* Extensibility framework
