### ISSUE TITLE
JSON-LD context needs updating

### ISSUE THREAD

**Issue by rhiaro** [jasnell/w3c-socialwg-activitystreams#316]
* [X] Editorial
 * [X] Non-Blocking Issue

The JSON-LD context doesn't contain the `@id` and `@type` aliases, which I guess means it's likely it's not up to date with other vocabulary changes as well.

I'm volunteering to update it when AS goes to CR if nobody else already has that on their todo list. Just noting here so I/we don't forget. 

(My implementation broke when I switched from `@id` to `id`)

**Comment by jasnell** [comment]
The context [doc itself](https://github.com/jasnell/w3c-socialwg-activitystreams/blob/master/activitystreams-core/activitystreams2-context.jsonld) is up to date but the version at the official w3c hosted url needs to be updated (it hasn't been in a while). You can use http://asjsonld.mybluemix.net/ temporarily.

**Comment by rhiaro** [comment]
Thanks! @sandhawke to update the w3c one.

**Comment by sandhawke** [comment]
Done.  

```bash
$ cd Repos/cvs.w3.org/WWW/ns
$ curl -o activitystreams.jsonld https://raw.githubusercontent.com/jasnell/w3c-socialwg-activitystreams/master/activitystreams-core/activitystreams2-context.jsonld
$ cvs commit -mnew-from-editor activitystreams.jsonld
```
