### ISSUE TITLE
Set up W3C Namespace URI to point to the @context Document

### ISSUE THREAD

**Issue by jasnell** [jasnell/w3c-socialwg-activitystreams#49]
The new W3C Namespace URI needs to point to the JSON-LD @context document with proper CORS headers and content type declaration

**Comment by akuckartz** [comment]
Is `http://www.w3.org/ns/activitystreams` the correct new namespace? I am in contact with Phil Archer regarding the future use of `http://www.w3.org/ns/opengov`, maybe I can help a bit with this one as well.

**Comment by jasnell** [comment]
This is done
