### ISSUE TITLE
To what extent should an Activity Streams 2.0 implementation be required to support external vocabularies?

### ISSUE THREAD

**Issue by jasnell** [jasnell/w3c-socialwg-activitystreams#50]
See: https://www.w3.org/wiki/Socialwg/Social_Vocabulary

**Comment by akuckartz** [comment]
The answer perhaps depends on the semantics of some keywords ("extent", "implementation", "support" :-)

When Activity Streams 2.0 documents are interpreted as simple JSON documents I would not care. But when they are interpreted as JSON-LD the context should reuse relevant external vocabularies as much as possible. The work to be done here therefore is to select those vocabularies. More precisely: the best relevant parts of those vocabularies. Avoid reinventing wheels (= properties etc.).

**Comment by elf-pavlik** [comment]
I understand this question little different. Not so much as reusing terms from already existing vocabularies but more as requirements on conformant implementations to handle data which uses non terms not from AS vocabulary.
IMO we may need to look at **graceful degradation**. People working on implementations should expect that **people will definitely use all kind of vocabularies in their data**. At the same time particular implementations will support only concepts relevant to certain domains. Some guidance on how to deal with data using terms not supported by particular implementation would come very useful here!

**Comment by jasnell** [comment]
I believe the current draft addresses this concern.
