### ISSUE TITLE
Proposal: remove lesser used properties from Activity Vocabulary, refactor others

### ISSUE THREAD

**Issue by jasnell** [jasnell/w3c-socialwg-activitystreams#54]
There were some additional properties added speculatively to the AS2 vocabulary earlier on it's it's dev cycle that are proving less than generally useful. There's also a couple carry overs from AS1 that ought to be deprecated.

1. The valid* properties. These were intended to offer a date-based validity bound for an Object's metadata. While useful, these can easily be provided as an extension where necessary. They are not generally useful for all objects and have a questionable processing model since we do not define exactly what "validity" means. These just just be removed.

2. The status property on Activity. This was one was added earlier in the AS2 dev cycle (pre-WG) and was always very speculative and has proven less than useful. This one should just be removed.

3. The existing "author" property on objects. This is a carryover from AS1. Not all objects have authors and there's a confusing overlap between "actor" and "author". This one should be deprecated but still allowed.

**Comment by elf-pavlik** [comment]
@tantek *author* != *agent*/*actor* for example:

@elf-pavlik posts activity: "@tantek ate an apple"
*author* - @elf-pavlik
*agent*/*actor* - @tantek 

I have impression that you might approach it from a blogger perspective, while people also want to post about all kind of other social interactions online...

**Comment by tantek** [comment]
Elf - it's a hypothetical example and thus ignorable compared to the plethora real world examples we have to work with. When you're making such posts with permalinks on your website, add them here and we can resume discussion.

**Comment by gobengo** [comment]
Relevant: This real-world use case.
https://github.com/gobengo/activity-mocks/blob/master/mocks/livefyre/add-topic-to-collection.json

In this activity, the actor, object, tag, and overall activity all have semantically different 'authors'
* actor - a Livefyre Site - authored by whatever subject initiated the creation of that Site
* object - a Livefyre Topic - authored by whichever subject initiated the creation of that Topic
* target - a Livefyre Collection - authored by whichever subject initiated the creation of that Livefyre Collection

In all cases, the subject that creates a Site, Topic, or Collection can be a UserProfile, Site, Network, or 'Client' (oAuth2 Client)

**Comment by tantek** [comment]
Not real-world - per ***mock***.

Again, "When you're making such posts with permalinks on your website, add them here and we can resume discussion.'

**Comment by gobengo** [comment]
@tantek http://bengo.is/notes/20150411-reply.html

**Comment by jasnell** [comment]
#1 and #2 contradict each other. "actor" is implemented in AS systems.
"author" less so.

**Comment by elf-pavlik** [comment]
Interesting example trying to talk about 'spoofing'  from ActivityPump draft

```json
{"verb":   "like",
         "actor":  "https://example.net/~mallory",
         "object": {
            "@id":      "https://example.org/~alice/note/23",
            "author":   "https://example.org/~alice",
            "content":  "I'm a goat"
          }
 }
```
http://w3c-social.github.io/activitypump/#obj

I still find it useful to have way to express sad but nowadays still true activities like: "Officer Harry **Attack**ed protester Jane" which clearly does require different agent and author...

**Comment by csarven** [comment]
re: https://github.com/jasnell/w3c-socialwg-activitystreams/issues/54#issuecomment-65703865

+1

**Comment by elf-pavlik** [comment]
> Elf - it's a hypothetical example and thus ignorable compared to the plethora real world examples we have to work with. When you're making such posts with permalinks on your website, add them here and we can resume discussion.

@tantek  I just [mentioned on IRC](http://socialwg.indiewebcamp.com/irc/social/2015-10-02/line/1443786991500) that all our teleconference/f2f minutes have different *agent/actor* (person who says something) and different *author* (person who scribes)
