### ISSUE TITLE
clarify consequences of choice between as:Object and as:Link

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#57]
Currently most terms have range set to
"rdfs:range": ["as:Object", "as:Link"]

I would see need for non-normative section eleborating on consequences of using one or the other. IMO many developers can find it confusing to face such choice and make such decision without realizing consequences. Also it may make sense to recommend implementations to expect and handle properly both.

Maybe we could use example from Link section

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "urn:example:types:application",
  "image": [
    "http://example.org/foo.jpg",
    {
      "@type": "http://www.w3.org/ns/activitystreams#Link",
      "href": "http://example.org/screens/1.jpg",
      "rel": "preview",
      "mediaType": "image/jpeg"
    }
  ]
}
```
with alternative

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "urn:example:types:application",
  "image": "http://example.org/foo.jpg",
  "preview": {
    "@type": "urn:example:types:image",
    "@id": "http://example.org/screens/1.jpg",
    "mediaType": "image/jpeg"
  }
}
```

**Comment by jasnell** [comment]
I believe this is addressed in the current working draft. If you disagree, please reopen the issue and let me know what additional would need to be said

**Comment by elf-pavlik** [comment]
I can not reopen this issue :worried: But maybe even better to raise it as ISSUE on W3C tracker!

I slowly prepare things to review [MediaObject patterns](https://www.w3.org/wiki/Socialwg/MediaObject) and will have more feedback on that issue from there! Please note reference there to TAG FPWD [URLs in Data](http://www.w3.org/TR/urls-in-data/)

As one of major observations: **Using as:Links breaks JSON-LD embedding** IMO this deserves mention in section discussing use of as:Link!
* http://www.w3.org/TR/json-ld/#embedding
* http://www.w3.org/TR/2015/WD-activitystreams-core-20150129/#link

**Comment by elf-pavlik** [comment]
I created issue in Social WG tracker for as:Link
https://www.w3.org/Social/track/issues/14
