### ISSUE TITLE
Best practices for @mentions

### ISSUE THREAD

**Issue by evanp** [jasnell/w3c-socialwg-activitystreams#62]
Many social systems use a in-band mechanism to let users define special addressing for messages. For example, "@username" often will route a note or image to a special "mentions" or "inbox" stream for a user.

It would be worthwhile to note that Activity Streams 2.0 processors should not have to parse the "content" or other properties of activity objects to determine this addressing information. Instead, the stream creator SHOULD put explicit addressing information into the activity using "to" or "cc", and MAY replace "@username" in the content with a link to an appropriate page for that user.

**Comment by akuckartz** [comment]
I do not like a special syntax like "@username" to be specified in the AS2 spec. It is just an example rendering by a client, correct?

**Comment by jasnell** [comment]
The WG decision was to indicate that these kinds of microsyntaxes should NOT be specified by the AS2 spec and that structured properties should be used (same as the  #63 discussion of hashtags)

**Comment by akuckartz** [comment]
I see. I do think that an interoperable specification would make sense, but I currently do not have a proposal. I will raise my voice here if/when that is the case.

**Comment by jasnell** [comment]
Addressed in the current published working draft
