### ISSUE TITLE
Automated Testing + CI

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#65]
I will track here setup for automated testing

* [ ] validate activitystreams2.owl
* [ ] validate *-context.jsonld
* [ ] test examples if JSON-LD, Turtle and RDFa serialize same graph (isomorphism)

**Comment by elf-pavlik** [comment]
I just used [TurtleValidator](https://github.com/mmlab/TurtleValidator) on [activitystreams2.owl](https://github.com/jasnell/w3c-socialwg-activitystreams/blob/72dc4f05bd6ef3a8abce779b6f0fa651c8700c17/activitystreams2.owl) and got error

```
$ node TurtleValidator.js activitystreams2.owl 
[Error: Expected subject but got bracketclose at line 45.]
Validation done: 1 errors and 0 warnings found.
```

**Comment by jasnell** [comment]
Closing this as there's no reason to keep it open at this time.
