### ISSUE TITLE
Represent Collections using JSON Text Sequences

### ISSUE THREAD

**Issue by dret** [jasnell/w3c-socialwg-activitystreams#69]
Currently, AS collections must use a JSON array (http://www.w3.org/TR/2015/WD-activitystreams-core-20150129/#collections). This can be cumbersome and problematic for scenarios with streaming activity data, and/or very large collections. One possibility would be to also allow JSON text sequences https://datatracker.ietf.org/doc/draft-ietf-json-text-sequence/, which probably very soon will become a stable RFC. Since they have their own media type, standard HTTP mechanisms could be used between a client and a server to negotiate the supported/preferred format for collections.

**Comment by jasnell** [comment]
+1... I've considered this a few times. The one thing that does make it a bit difficult would be the need to duplicate the JSON-LD @context across each individual entry but that's not too awful (unless an implementation is doing crazy things). Perhaps some implementation/experimentation is in order?

**Comment by akuckartz** [comment]
Yes, streaming is important. The relation between JSON and JSON Text Sequences seems to be somewhat similar to that between XML and XMPP.

**Comment by dret** [comment]
@akuckartz not really, no, but agreed that there are some minor similarities. not sure how @jasnell would be able to avoid repeating the context in either case, but i am pretty sure that for massive scale and streaming scenarios, it would be very useful to have support for a representation that allows for continuous processing.

**Comment by jasnell** [comment]
@dret ... pull requests accepted ;-) https://github.com/jasnell/activitystreams.js

Would be happy to get some experimentation in

**Comment by dret** [comment]
this all depends on how essential the processing model says a JSON-LD perspective is. if i can process AS as naked JSON, then i should be able to do so for collections as well, as well as their JSON text sequence variants, and there's no need to ever use contexts. there's no JSON-LD context needed at all, it's an optional post-processing step. if, on the other hand, JSON-LD becomes a required part of the processing model, then it might be necessary to repeat this every single time or define it as implicitly being there, being serialized or not.

**Comment by dret** [comment]
update: https://tools.ietf.org/html/rfc7464 is the official RFC for "JSON Text Sequences" that was published just yesterday.

**Comment by jasnell** [comment]
WG decision not to do this at this time.

**Comment by elf-pavlik** [comment]
Did you look by any chance how it relates to *[application/vnd.collection+json](http://www.iana.org/assignments/media-types/application/vnd.collection+json)* media type?

**Comment by dret** [comment]
if the WG decided not to do this, i am fine with closing this issue. if such a label exists, maybe some kind soul could label this issue as "possible enhancement" (or whatever the label is).
