### ISSUE TITLE
Excluding a natural language property from the language context

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#71]
Example 51 in a spec currently suggests

```jsonld
{
  "@context": [
    "http://www.w3.org/ns/activitystreams",
    { "@language": "en" }
  ],
  "displayName": {
    "@value": "This is the title",
    "@language": null
  }
}
```
but it doesn't work in JSON-LD playground http://json-ld.org/playground/#/gist/0d3cecac2b124f67b85f

looks like ```"@language": null``` causes some problem when parsed

when removed just use of  ```"@value": This is the title"``` removes the default language
http://json-ld.org/playground/#/gist/79291ee35c028fddf5bd

```jsonld
{
  "@context": [
    "http://www.w3.org/ns/activitystreams",
    { "@language": "en" }
  ],
  "displayName": {
    "@value": "This is the title"
  }
}
```
```n3
_:b0 <http://www.w3.org/ns/activitystreams#displayName> "This is the title" .
```

**Comment by akuckartz** [comment]
An error in the playground https://github.com/json-ld/json-ld.org/tree/master/playground ?

**Comment by elf-pavlik** [comment]
@dlongley maybe you understand this ```"@language": null``` issue?

**Comment by dlongley** [comment]
I think this may be another case of an inconsistency between the syntax and API specs that needs to be resolved, see: https://github.com/json-ld/json-ld.org/issues/375.

Step 7.4.7 of the [Expansion Algorithm](http://www.w3.org/TR/json-ld-api/#expansion-algorithm) requires `@language` to be a string; it can't be `null`.

**Comment by elf-pavlik** [comment]
thanks @dlongley :star2: nice to see that you keep track on all those issues!
@jasnell do we really need that null there? it looks like not including it also gives expected results.

**Comment by dlongley** [comment]
This will work now in the playground -- I think it's producing the proper behavior. But, as @elf-pavlik pointed out, specifying `@value` without an `@language` key will have the same meaning as specifying `@value` with an `@language` that is `null`.

**Comment by jasnell** [comment]
+1... leaving out the @language:null simplifies things just a bit, although it's a bit less obvious for implementations that choose not to do full JSON-LD processing. It'll just be something additional they'll need to look out for.

**Comment by jasnell** [comment]
Added this in the latest commit. @language: null removed but a warning to implementers to avoid if possible
