### ISSUE TITLE
[vocabulary]  owl:equivalentClass and rdfs:subClassOf relations with the same object?

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#73]
reported by @kidehen via twitter
* https://twitter.com/kidehen/status/567654832937648129

https://github.com/jasnell/w3c-socialwg-activitystreams/blame/master/activitystreams2.owl#L1325-L1326

**Comment by jasnell** [comment]
This will be fixed in the next merge
