### ISSUE TITLE
Objects and Activities based on User Stories

### ISSUE THREAD

**Issue by jasnell** [jasnell/w3c-socialwg-activitystreams#77]
If we look here: https://www.w3.org/wiki/Socialwg/Social_API/User_stories

There are a number of Object and Activity Types currently not covered by the Activity Streams vocabulary. There are also some that may need to be tweaked.

* `Profile` - We have "Page" and "Person" object types, but not a "Profile" object type. Should we add one? Example use "John updated his Profile"
* `Avatar` - We have an "Image" object type, but not one that is specifically "Avatar". Right now, we can associate an "image" with a "Person" which serves the same purpose, but do we need "Avatar" as a first class object type? Example use "Sally created her Avatar"
* `Hide`, `Revoke` and `Redact` - These are a bit odd but go along with the privacy user stories.

**Comment by elf-pavlik** [comment]
I proposed it as work for Social IG: Vocabulary TF
https://www.w3.org/wiki/Sicialig/Vocabulary_TF/Mapping_API_User_Stories_to_Vocabulary_terms
