### ISSUE TITLE
Use URLs not URNs as examples 

### ISSUE THREAD

**Issue by kevinmarks** [jasnell/w3c-socialwg-activitystreams#79]
Representing people as URNs is obscure and unhelpful. People have URLs and are widely represented by them on the web.

**Comment by elf-pavlik** [comment]
:+1: IMO we should also reconsider use of acct: but it at least offers improvement over urn:

**Comment by jasnell** [comment]
The URN's used are based on this: https://tools.ietf.org/html/rfc6963

The use of acct is there largely as a placeholder until the WG figures out what it ultimately wants to do around identity.

Quite a few social systems do not use URLs for representing people so we need to make sure we cover both bases. The vocabulary itself calls for @id's to be absolute URI/URL/IRIs. 

That all said, a pull request to update the examples would be accepted ;-)

**Comment by jasnell** [comment]
@kevinmarks interested in helping out with a PR? :-)

**Comment by dissolve** [comment]
Noticed there are still urn: values in,  I will update later with a PR for that as well.

**Comment by evanp** [comment]
I disagree with this. We're going to see all kinds of URIs as IDs and types; we don't explicitly prevent non-HTTP URIs. I'd like to see some acct: URIs in there, since it's what we use for pump.io.

**Comment by akuckartz** [comment]
Use https-URLs please.

**Comment by akuckartz** [comment]
How was this resolved?!

**Comment by jasnell** [comment]
https://github.com/jasnell/w3c-socialwg-activitystreams/pull/186
