### ISSUE TITLE
Don't use <llink> in HTML body examples, use <a>

### ISSUE THREAD

**Issue by kevinmarks** [jasnell/w3c-socialwg-activitystreams#80]
The &lt;link&gt; tag is purely for document-level references. See http://www.w3.org/TR/html5/document-metadata.html#the-link-element
>A link element must have a rel attribute.
>If the rel attribute is used, the element is restricted to the head element.

>Hyperlinks created with the link element and its rel attribute apply to the whole page. This contrasts with the rel attribute of a and area elements, which indicates the type of a link whose context is given by the link's location within the document.

**Comment by tantek** [comment]
As of HTML5, even a and area elements's rel attribute values (and relations) apply to the context of the entire document. The remainder of this issue is correct, examples should use <a href> markup, not <link>.

**Comment by kevinmarks** [comment]
bug filed on whatwg spec to remove that note https://www.w3.org/Bugs/Public/show_bug.cgi?id=28132 as https://html.spec.whatwg.org/multipage/semantics.html#the-a-element says
> rel— Relationship between the document containing the hyperlink and the
destination resource

**Comment by jasnell** [comment]
@kevinmarks ... A PR is helpful :-)

**Comment by dissolve** [comment]
As of the PR merge,  I think this issue cab be closed.
