### ISSUE TITLE
Activity Vocabulary link is broken

### ISSUE THREAD

**Issue by stevenroose** [jasnell/w3c-socialwg-activitystreams#81]
It points to `http://www.w3.org/TR/WD-activitystreams-vocabulary-20150129/`.

Section 2.2, 3 and 3.1 contain an occurrences of the link.

**Comment by akuckartz** [comment]
The broken links were replaced by http://jasnell.github.io/w3c-socialwg-activitystreams/activitystreams2-vocabulary.html in the Editor's Draft (ED). They are still broken in the current Working Draft (WD).

This issue therefore can be seen as having been resolved and it should perhaps be closed.

Or do we want to wait until a new WD is published? I usually review EDs only.

**Comment by jasnell** [comment]
Links will be regenerated in the next WD.
