### ISSUE TITLE
a Group also a Collection? / Collections associated with a Group

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#82]
## Background

as:Group
http://www.w3.org/TR/activitystreams-vocabulary/#dfn-group
"Represents a formal or informal collective of Actors."

as: Collection
http://www.w3.org/TR/activitystreams-vocabulary/#dfn-collection
"A Collection is a subclass of Object that represents ordered or unordered sets of Object or Link instances..."

as:items
http://www.w3.org/TR/activitystreams-vocabulary/#dfn-items
"Identifies the items contained in a collection. The items might be ordered or unordered."

as:memberOf
http://www.w3.org/TR/activitystreams-vocabulary/#dfn-memberof
"Identifies a collection this object can be considered a member of"

## Questions

1. How do we model members of the group? I proposed exercise with modeling SocialWG members in https://www.w3.org/wiki/Socialwg/Collection_Comparison

2. How do we model collection of events associated with this group?
e.g https://www.w3.org/wiki/Socialwg#Past_Telecons_.26_Meetings

## See also
* http://schema.org/event
* http://www.w3.org/TR/ldp/#ldpdc
* https://www.w3.org/community/hydra/wiki/Collection_Design

**Comment by elf-pavlik** [comment]
I think about something like this illustration, will add JSON-LD example later!

![Collection Design](https://docs.google.com/drawings/d/1oKPV9iSOZjuL7CkFbsc4LWjHNIW4V7Q3xSvqkS56ARY/pub?w=480&h=360)

**Comment by akuckartz** [comment]
Any relation with http://www.w3.org/TR/vocab-org/ ? (Trying to avoid reinventing wheels)

**Comment by jasnell** [comment]
@elf-pavlik without implementation experience that shows "as:Group" being used as an "as:Collection" this makes no sense to do yet. It's not inherently harmful to make as:Group a subclass of as:Collection but there is no evidence that implementers would actually treat it that way (or want to)

**Comment by jasnell** [comment]
That said, one could easily do something like the following if they did want to model an as:Group as an as:Collection...

```
{
  "@type": ["Group", "Collection"],
  "items": [ ... ]
}
```

**Comment by jasnell** [comment]
There is no implementation experience to draw from to justify making this change right now.
