### ISSUE TITLE
Fix microformats examples in spec to reflect actual minimal standard publishing / consuming practices

### ISSUE THREAD

**Issue by tantek** [jasnell/w3c-socialwg-activitystreams#83]
Fix microformats examples in spec to reflect actual minimal standard publishing / consuming practices, specifically to incrementally address https://www.w3.org/Social/track/actions/26

While reviewing the microformats examples I've found patterns of problems to fix that will likely apply to most if not all existing microformats examples in the spec.

This is issue is for documenting all of these issues in general, and I expect to submit multiple pull requests to fix specific instances of these problems.

Problems and fixes
* use "h-entry" instead of all the "h-as-*" class names
* use `<a class="p-author h-card" href="http://martin.example.org/">Martin</a>` instead of `<link class="u-author" href="urn:example:person:martin">Martin</link>`
* use `<img class="u-photo" href="http://martin.example.org/foo.jpg" alt="Photograph of foo"/>`
instead of `<a class="u-item" href="http://example.org/foo.jpg">"http://example.org/foo.jpg"</a>`

Use 
```html
<a class="p-author h-card" href="http://martin.example.org/">
<img src="http://martin.example.org/image.jpg" alt=""/>Martin Smith
</a>
```
instead of:
```html
<div class="p-author h-card">
<meta class="p-as-id" name="id" content="urn:example:person:martin" />
<a class="u-url p-name" href="http://example.org/martin">
Martin Smith
</a>
<img class="u-photo" src="http://example.org/martin/image.jpg" type="image/jpeg" />
</div>
```

Use 
```html
< a class="u-url p-name" href="http://martin.example.org/blog/2011/02/entry">
Why I love Activity Streams
</a>
```
instead of:
```html
<div class="p-item h-entry">
<meta class="p-as-id" name="id" content="urn:example:blog:abc123/xyz" />
<a class="u-url p-name" href="http://example.org/blog/2011/02/entry">
"Why I love Activity Streams"
</a>
</div>
To
<div class="p-as-target h-entry">
<meta class="p-as-id" name="id" content="http://example.org/blog" />
<span class="p-name">Martin's Blog</span>"
</div>
```

* use `<time class="dt-published" datetime="` instead of `<meta class="dt-published" name="published" content="` including /time instead of /meta.

This is just a start, I'll add more as I find more.

**Comment by tantek** [comment]
Bookmark: need to edit and send pull requests for examples starting at: https://github.com/jasnell/w3c-socialwg-activitystreams/blob/master/activitystreams2.html#L302

**Comment by tantek** [comment]
First pull request that attempts to fix first two examples as a start: https://github.com/jasnell/w3c-socialwg-activitystreams/pull/84

**Comment by jasnell** [comment]
@tantek : any more action on this?

**Comment by jasnell** [comment]
Actually, may I suggest that the microformats examples simply be removed from both documents until a well defined mapping between the two is spec'd.

**Comment by tantek** [comment]
"well defined mapping between the two" is not a reasonable requirement because it is unlikely anything like that will ever exist, given the different methodologies of the approaches. This is not just a difference in syntax (which the other example variants appear to be).

microformats markup of posts and activity-like posts has been following a very minimal design approach based on what information people actually publish (based on publishing evidence at real world URLs), whereas the AS model as expressed in JSON-LD is more designed based on anticipation - two completely different approaches - thus unlikely to ever have a global mapping.

The point of providing the microformats examples is to show clearly how much simpler they are when based on actual publishing practices rather than anticipation of what people might want to publish, and to provide consumers of either microformats or AS(in any syntax) to have a chance at converting between the two. If this document is not the place for that that's fine, but in that case this issue should be kept open until a URL is provided for that place.

**Comment by jasnell** [comment]
Given that a well defined mapping between the two is not likely to exist, it makes no sense to bundle the examples together in the core or vocabulary document. Producing a separate Note that shows a non-normative transformation between the JSON-LD syntax and Microformats would be far easier to create and maintain over time. Especially given, as you say, "This is not just a difference in syntax".

You claim that the "The point of providing the microformats examples is to show clearly how much simpler they are". Given that I am the one who initially added those examples, I can say with quite a bit of authority that that was *not* the point. The point of providing the microformats examples was to demonstrate a clear one-to-one mapping of the vocabulary model across alternative syntaxes, primarily to show that the vocabulary was not limited to strictly JSON-LD -- even tho JSON-LD was the only normative syntax being defined. 

As it currently stands, there are hundreds of examples within the two documents, each with five different variants of differing levels of complexity. I do not have the time available to devote to ensuring that every one of those variants is correct, nor do I currently have the time to define the mapping between the JSON-LD model and the Microformats model. Given that (a) most of the microformats examples were incorrect (b) there's been only a single pull request in six months correcting only *some* of the microformats examples and (c) the Microformats syntax is not a normative requirement in the spec, I made the editorial decision to remove that particular set of examples. 

I believe it would be further worthwhile to also remove the Microdata and RDFa examples as well, primarily for the purpose of simplifying the specification documents overall. 

What I would strongly encourage is for those members of the WG who have an interest in the Microformats syntax to produce a draft Note that details the mapping of the AS2 vocabulary to the Microformats model, with correct examples. I do not have the time to help edit such a draft Note. 

If someone wishes to take the time to submit a PR against the current drafts adding corrected Microformats examples back into the document, then I will merge it in. At this point in time, however, I do not have the free time to work on producing hundreds of non-normative examples that, in my opinion, add nothing but unnecessary complexity back into the document.

**Comment by jasnell** [comment]
Comments on the mailing list: https://lists.w3.org/Archives/Public/public-socialweb/2015Jun/0009.html

**Comment by csarven** [comment]
Raised this again based on current state of things and with more details about the issues: https://www.w3.org/Social/track/issues/44

**Comment by csarven** [comment]
Related issue https://github.com/jasnell/w3c-socialwg-activitystreams/issues/194
