### ISSUE TITLE
Alignment with `schema:image`

### ISSUE THREAD

**Issue by akuckartz** [jasnell/w3c-socialwg-activitystreams#85]
How well is AS2 `image` aligned with `schema:image` (http://www.schema.org/image) ?

**Comment by elf-pavlik** [comment]
http://www.w3.org/TR/activitystreams-vocabulary/#dfn-image-term

```ttl
as:image a owl:ObjectProperty ;
  rdfs:label "image"@en ;
  rdfs:range [
    a owl:Class ;
    owl:unionOf ( as:Image as:LinkNotHandler )
  ] ;
  rdfs:domain as:Object .
```

besides *as:Link* issue looks similar to me
*[ISSUE-14](https://www.w3.org/Social/track/issues/14) as:Link adds a lot of complexity, if we keep it we need to clarify consequences of using it instead of as:Object*

**Comment by jasnell** [comment]
@akuckartz as:image has no alignment with schema:image currently, at least not formally. One could easily use as:image and schema:ImageObject or schema:URL together, however. Nothing in the spec requires it tho.

```json
{
  "@type": "Article",
  "image": {
    "@type": "schema:ImageObject",
    "schema:caption": "This is the caption",
    ...
  }
}
```
