### ISSUE TITLE
Add `application/ld+json` as requirement for servers

### ISSUE THREAD

**Issue by akuckartz** [jasnell/w3c-socialwg-activitystreams#86]
I suggest to *add* a requirement for servers to provide media type `application/ld+json` in *addition* to `application/activity+json`. That would help those with an RDF view of the world without costing much for those with a non-RDF view.

See also #52 and #53.

**Comment by jasnell** [comment]
Is this specifically for the API?

**Comment by akuckartz** [comment]
Well, yes, but new media types are specified in the AS2 specification. For that reason I suggest to also explain the use of the JSON-LD media type in the same section of the spec.

**Comment by jasnell** [comment]
A PR would be welcome but I'm not convinced that this is useful from an interop point of view. What specific requirements would you expect? For instance, a document served as "application/activity+json" has an implied default context document if the @context field happens to be missing. A document served as "application/ld+json" would not carry the same assumption. Likewise, a document served as "application/activity+json" has the requirement that it must be in json-ld compact form using, at least, the normative AS2 @context document. A document served as "application/ld+json" could be any valid JSON-LD form, including expanded.

**Comment by akuckartz** [comment]
I will attempt to provide a PR or more details.

**Comment by jasnell** [comment]
@akuckartz ... just pinging... are you still expecting to do a PR?

**Comment by akuckartz** [comment]
> are you still expecting to do a PR?

Yes, at least I will propose some text for discussion. Sorry for being slow.

**Comment by elf-pavlik** [comment]
#132 looks relevant as it discusses implied by media types contexts

**Comment by jasnell** [comment]
RESOLVED on conf call: close this with no action

**Comment by melvincarvalho** [comment]
I could be wrong but I am unsure SoLiD apps will work with a non standard MIME type.  Could this be proposed for AS3, or something?

**Comment by akuckartz** [comment]
@melvincarvalho That is one of the problems which I see. Having to support a new media type makes it significantly more difficult to use existing LD software.

I have not yet read the minutes of the call, but maybe we "only" need to provide a reasonable pull request.

**Comment by akuckartz** [comment]
Discussion took place on 2015-07-07:
https://www.w3.org/wiki/Socialwg/2015-07-07-minutes#Github_Issue_86:_Add_.60application.2Fld.2Bjson.60_as_requirement_for_servers
