### ISSUE TITLE
an Object and its interaction collections and counters

### ISSUE THREAD

**Issue by elf-pavlik** [jasnell/w3c-socialwg-activitystreams#89]
1) How do we associate an Object with interactions which happened with it as *object*?
2) How do we keep count on particular interactions e.g. Listen

relevant issue from schema.org https://github.com/schemaorg/schemaorg/issues/137

**Comment by jasnell** [comment]
In the past this was done via "response" properties (see: http://activitystrea.ms/specs/json/replies/1.0/). These were an informal extension whose values were Collection objects with a totalItems properties. The AS2 vocabulary includes the "replies" term that is carried over from this but the mechanism is largely informal and is based largely on specific implementation decisions.

**Comment by jasnell** [comment]
Specifically, the model carried over from AS1 would look like:

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "Note", 
  "@id": "http://example.org/notes/1",
  "content": "This is a simple note",
  "replies": {
    "@type": "Collection",
    "totalItems": 2, 
    "items": [
      {
        "@type": "Note",
        "content": "This is a comment",
        "inReplyTo": "http://example.org/notes/1"
      },
      {
        "@type": "Note",
        "content": "This is another comment",
        "inReplyTo": "http://example.org/notes/1"
      }
    ]
  }
}
```

While there are some ways in which this is less than ideal, the model gives us a great deal of flexibility. For instance, we can use the Collection object's `url` property to point to the actual collection, using the inline document as just a summary placeholder:

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "Note", 
  "@id": "http://example.org/notes/1",
  "content": "This is a simple note",
  "replies": {
    "@type": "Collection",
    "totalItems": 2,
    "url": {
      "href": "http://www.example.org/notes/1/comments",
      "mediaType": "application/activity+json"
    }
  }
}
```

Or we can use paging on the replies collection object:

```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "@type": "Note", 
  "@id": "http://example.org/notes/1",
  "content": "This is a simple note",
  "replies": {
    "@type": "Collection",
    "totalItems": 4,
    "next": "http://www.example.org/notes/1/comments?p=2", 
    "items": [
      {
        "@type": "Note",
        "content": "This is a comment",
        "inReplyTo": "http://example.org/notes/1"
      },
      {
        "@type": "Note",
        "content": "This is another comment",
        "inReplyTo": "http://example.org/notes/1"
      }
    ]
  }
}
```

This model has worked very well in practice.

**Comment by jasnell** [comment]
Closing as there does not appear to be an actual issue here.

**Comment by elf-pavlik** [comment]
relevant pull request to schema.org introducing **InteractionCounter** class https://github.com/schemaorg/schemaorg/pull/514
