### ISSUE TITLE
On the Post and Share activities

### ISSUE THREAD

**Issue by oshepherd** [jasnell/w3c-socialwg-activitystreams#97]
[Amy's post on explicit vs implicit typing](http://rhiaro.co.uk/2015/04/post-and-activity-types) brought to mind something I've been mulling over for a while.

ActivityStreams is very focused on Activities. It's kind of in the name. Meanwhile, the IndieWeb has coalesced around the Post, which in ActivityStreams-ese would be the Object.

Both of them have a conceptual elegance: In the Indieweb, your feed is a stream of your posts. On ActivityStreams, your feed is a stream of your activities.

I think both of these are wrong, but I think that ActivityStreams is more wrong. And I refer specifically to the Post and Share activities.

These are the "major" activities of the network. In real deployments such as Pump.io, they're called out specially: These activities are placed in your "major feed*"; while other activities (such as liking and following) are placed in your minor feed. Posts and Shares create and spread content respectively.

The posts are perhaps the bigger offender. They're entirely synthetic. A "Post" activity carries no additional information than what is contained in the object, with the exception of the audience targetting properties. And, as it turns out, you'd much rather the audience targetting properties be on the object. Them being on the activity is very problematic when the object becomes detached from its' post activity.

The share activity also has major issues. Specifically, it doesn't let me add my own commentary visible on my own feed. Nigh every social network lets me do this (Twitter being the notable exception, though even there people substitute hacks), but ActivityStreams doesn't.

Ostensibly I could add commentary to the activity using its' "content" property but this feels rather nasty and like trying to work around what the object was intended

My opinion is that these activities should be removed. The audience targeting properties should be permitted on content objects (which are distinct from non-content objects - such as a person). The "post" activity would be replaced by simply inlining the content object in the user's feed in its' place, and the "share" activity would be replaced by a "repost" object. The action of "posting" becomes implicit in the placement of an object in your stream, and your stream would contain objects of types Content | Activity.

This would then tighten up the definition of Activity significantly, into two categories:

* Content free user actions: Like. Dislike. Checkin. Commited (code). Added an item to a list.
* Social graph actions: Follow. Unfollow. Joined a Group.

Removing those two activities actually makes our lives simpler. Activities unify with objects better - becoming more of a pattern than a special kind of object (though certainly some actions are special and will have impact on your social graph), and we remove the big modeling disconnect between ActivityStreams and Microformats/Atom/RSS/etc.

I think this would be a very worthwhile simplification.

(* With limitations: Pump.io filters out "posts" of an object of type "comment")

**Comment by jasnell** [comment]
The existing `Post` Activity is really equivalent to `Create`. It doesn't mean, "This is a post". It means "Joe create a new... something". In that sense, it's not equivalent to the IndieWeb notion of a "post". 

Regarding `Share`, all Activity types are Objects. So you could easily add additional commentary using the ordinary Object properties

```json
{
  "@context": "http://www.w3.org/ns/activitystreams#",
  "@type": "Share",
  "content": "I really like this article",
  "actor": "acct:joe@example.org",
  "object": {
    "@type": "Article",
    "content": "This is an article about nothing",
    "url": "http://www.example.org/article/123"
  }
}
```

**Comment by jasnell** [comment]
https://www.w3.org/Social/track/issues/40

**Comment by gobengo** [comment]
@jasnell It seems that semantically 'Create' and 'Post'. Consider an IoT easy-bake oven that publishes activities about what happens with it. When I bake (create) a cake, a reasonable activity would be

```json
{
  "@context": "http://www.w3.org/ns/activitystreams#",
  "@type": "Create",
  "actor": "acct:ben@bengo.is",
  "object": {
    "@type": "bengo.is/types/BakedGood",
    "@id": "urn:uuid:298745c6-c4c3-4180-9ba7-7bce4675aec9"
  }
}
```

Notably, this indicates that I created a Cake, but not much about it. Maybe later someone is eating it and having a great time and they want to Post more information about it somewhere later.

```json
{
  "@context": "http://www.w3.org/ns/activitystreams#",
  "@type": "Post",
  "actor": "acct:cake-lover@example.org",
  "object": {
    "@type": "bengo.is/types/BakedGood",
    "@id": "urn:uuid:298745c6-c4c3-4180-9ba7-7bce4675aec9"
    "attributedTo": "acct:ben@bengo.is"
  },
  "target": {
    "@id": "https://example.org/~cake-lover/favorite-cakes/,
    "@type": "Collection"
  }
}
```

In the model I've been using, "Post" doesn't necessarily imply canonical authorship. "Create" seems like it does. This distinction seems useful.

**Comment by gobengo** [comment]
In our implementation from last year, we use 'create' and not 'post'. https://gist.github.com/gobengo/c1fa46f51608fb2a69d3#file-real-world-json-L2393

**Comment by jasnell** [comment]
There seems to be significant confusion being caused by attempting to conflate overlay microformats terminology on top of AS2, which just doesn't work. The microformats notion of a "post" is *not* the same thing as the AS1 and AS2 notion of the "Post" activity. They are related, but are defined to describe different things. There are two things we can do to resolve this: (1) stop conflating microformats and AS2 and (2) deprecate the AS2 "Post" activity.

**Comment by jasnell** [comment]
(actually, it's not so much Deprecating "Post" as it is simply removing it. A note can be added that the original "verb": "post" from AS1 is no longer used and that it is equivalent to either "@type": "Create" or "@type": "Add" depending on the context.

**Comment by jasnell** [comment]
"Post" has been removed from the current editor's draft.
