### ISSUE TITLE
Connection is now modeled as an Activity, should we model is as a reified statement?

### ISSUE THREAD

**Issue by jasnell** [jasnell/w3c-socialwg-activitystreams#99]
e.g. 
{
  "@type": "Connection",
  "a": "acct:john@example.org",
  "predicate": "foaf:knows",
  "b": "acct:sally@example.org"
}

where `a` and `b` are subproperties of `rdf:subject` and `rdf:object` and `predicate` is a subproperty of `rdf:predicate`. This allows us to easily reuse other existing vocabularies for describing relationship types.

**Comment by elf-pavlik** [comment]
@jasnell please take a look at diagrams I just did around reification, relations, qualified relations and activities

![social vocab](https://docs.google.com/drawings/d/1NInXbCyPsRoNi9KXch4-Arq0sbC20a-2jwePHNa6Wlo/pub?w=920&h=1580)

@rhiaro

**Comment by jasnell** [comment]
@elf-pavlik that doesn't actually help address the question. On the call today it was decided to remodel the existing "Connect" and "FriendRequest" Activity types into a "Connection" object. That Connection object has to be able to describe a connection between two individuals. Such an object is naturally a form of reified statement. The question is only if we want to formally model it as such.

**Comment by elf-pavlik** [comment]
I think we do want to use reified statements and reuse predicates. It will also come handy when we query. Since systems can have *both* qualified and non qualified relations in used dataset.

```ttl
@prefix : <https://example.vocab/>
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix w3c: <http://ld.w3c.org/> .

:QualifiedRelation a owl:Class .
# not sure if we can make it rdfs:subClassOf rdf:Statement

:Following a owl:Class ;
  rdfs:subClassOf :QualifiedRelation .

w3c:elf-pavlik a :Person .
w3c:jasnell a :Person .

w3c:elf-pavlik-followed-jasnell a as:Follow ;
  as:actor w3c:elf-avlik ;
  as:object w3c:jasnell .

#qualified relation
w3c:elf-pavlik-following-jasnell a :Following ;
  rdf:predicate :follow ;
  rdf:subject w3c:elf-avlik ;
  rdf:object w3c:jasnell ;

# additional unqualified relation for ease of querying
#(most comnonly used in already existing data)
w3c:elf-pavlik :follows :w3c:jasnell .

```

**Comment by elf-pavlik** [comment]
I also started similar diagrams for *Container* #82 which also uses pattern similar to reification. Will update it later to use [ldp:DirectContainer](http://www.w3.org/TR/ldp/#ldpdc) so again we can reuse same predicates to follow our nose to containers with people i follow or who follow me :smile: 

![containers](https://docs.google.com/drawings/d/1gsyE3FlQzTrT6VYV24KLUQs3kbzGWNtVLQU52W7PkzY/pub?w=932&h=1114)

**Comment by elf-pavlik** [comment]
I also suggest reading [Defining N-ary Relations on the Semantic Web](http://www.w3.org/TR/swbp-n-aryRelations/)

Use Case 3 of N-ary Relation looks very much like as:Activity
![N-ary relation with no distinguished participant](http://www.w3.org/TR/swbp-n-aryRelations/purchase_example.jpg)
http://www.w3.org/TR/swbp-n-aryRelations/#useCase3

**Comment by elf-pavlik** [comment]
While working on *Travel* with actor staying multiple times in the same city. I found need that a qualified relation links to relevant activities which provide more detailed timeline. Similar can happen with *Connection* to another agent. I can *Follow*/*Unfollow*, *Friend*/*Unfriend* etc. multiple times. So Qualified Relation(s) between two agents serve distinct purpose than Activitiy(ies) which happen between them. I don't see question should we use on or the other a proper one, instead I think both have its place and we just need to clearly define and explain how one relates to the other...
